Bugfix/manager news
tediik/online_store pull request #108
Opened 2020-10-01 13:08 UTC by ZirPav

2020-10-01 15:01 UTC, ghost commented on src/main/java/com/jm/online_store/model/News.java
> +
лишняя строка

2020-10-01 15:01 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/model/News.java
> +
лишняя строка

2020-10-01 15:14 UTC, dshishkaryan commented on src/main/resources/static/js/newsManagementRenderAndFunctions.js
> +
лишние строки

2020-10-01 15:25 UTC, dshishkaryan commented on src/main/resources/static/js/newsManagementRenderAndFunctions.js
> +
лишняя строка

2020-10-01 15:26 UTC, dshishkaryan commented on src/main/resources/static/js/newsManagementRenderAndFunctions.js
> +
лишняя строка

2020-10-01 18:18 UTC, tediik requested changes

2020-10-01 18:18 UTC, tediik commented on src/main/java/com/jm/online_store/model/News.java
> +
согласен, лишняя

2020-10-01 18:18 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/NewsServiceImpl.java
> +            System.out.println("There are no news");
логируй, никаких System.out.println

2020-10-01 18:18 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/NewsServiceImpl.java
> +            System.out.println("There are no published news");
логирование

2020-10-01 18:18 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/NewsServiceImpl.java
> +            System.out.println("There are no unpublished news");
логирование

2020-10-01 18:18 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/NewsServiceImpl.java
> +            System.out.println("There are no archived news");
логирование

2020-10-02 07:02 UTC, ZirPav commented on src/main/java/com/jm/online_store/service/impl/NewsServiceImpl.java
> +            System.out.println("There are no news");
В чем смысл логировать не исключительную ситуацию? Нет архивных новостей вполне себе рабочая ситуция, не вижу в этом никакой ошибки? Просто в случае если мы убираем последнюю архивную новость вкладка не обновляется(без прямого обновления страницы), так как у нас "исключительная ситуация".

2020-10-03 15:11 UTC, tediik approved these changes

2020-10-03 15:11 UTC, merged