Feature/cabinet admin make edit
tediik/online_store pull request #127
Opened 2020-10-10 11:41 UTC by DeMaN357

2020-10-10 14:42 UTC, tediik requested changes
Почитай вот тут про автозаполнение
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#Preventing_autofilling_with_autocompletenew-password

2020-10-10 14:42 UTC, tediik commented on src/main/resources/templates/blocks/mainHeader.html
> +        <a sec:authorize="hasAnyAuthority('ROLE_CUSTOMER') and not hasAnyAuthority('ROLE_ADMIN')" class="btn btn-outline-secondary font-weight-bold secondarybtn"
точно нужно обязательно указывать?
and not hasAnyAuthority('ROLE_ADMIN')

2020-10-11 13:42 UTC, tudasuda93 commented on src/main/resources/templates/adminPage.html
> +            <a th:href="@{/}" class="btn btn-info ml-auto">Главная</a>
тестовая строка

2020-10-11 19:12 UTC, DeMaN357 commented on src/main/resources/templates/blocks/mainHeader.html
> +        <a sec:authorize="hasAnyAuthority('ROLE_CUSTOMER') and not hasAnyAuthority('ROLE_ADMIN')" class="btn btn-outline-secondary font-weight-bold secondarybtn"
да надо, т.к. у нашего админа две роли - кастомер и админ, и поэтому нужно следить чтобы они не перекликались

2020-10-11 19:46 UTC, tediik approved these changes

2020-10-11 19:46 UTC, merged