Merge branch 'dev' into bugfix/RedaktirovanieUserVKabineteAdmina2
tediik/online_store pull request #132
Opened 2020-10-12 15:07 UTC by Boitsovrich

# Conflicts:
#	src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
#	src/main/java/com/jm/online_store/controller/simple/CustomerController.java
#	src/main/resources/templates/customerPage.html

2020-10-13 01:08 UTC, DeMaN357 commented on src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
> +    public ResponseEntity<String> changechangemailReq(Authentication auth, Model model,
название метода

2020-10-13 01:10 UTC, DeMaN357 commented on src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
> +        User user = (User) auth.getPrincipal();
я думаю лучше вернуть userService.getCurrentLoggedInUser() - это уже готовый функционал

2020-10-13 01:11 UTC, DeMaN357 commented on src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +        User principal = (User) auth.getPrincipal();
тоже лучше верни как было userService.getCurrentLoggedInUser()

2020-10-13 01:12 UTC, DeMaN357 commented on src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +        User user = (User) auth.getPrincipal();
userService.getCurrentLoggedInUser()

2020-10-13 01:13 UTC, DeMaN357 commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +
строка

2020-10-13 01:16 UTC, DeMaN357 commented on src/main/resources/static/js/profile.js
> +    console.log(formData);
console.log поубирай

2020-10-13 01:20 UTC, DeMaN357 commented on src/main/resources/templates/customerPage.html
> +            <script type="text/javascript">
Скрипт в js

2020-10-13 01:21 UTC, DeMaN357 commented on src/main/resources/templates/customerPage.html
> +                                                        <input type="button" id="pictureBtn" value="Upload Picture"
вот тут я хз, у тебя походу тут конфликты

2020-10-14 14:35 UTC, Boitsovrich commented on src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
> +    public ResponseEntity<String> changechangemailReq(Authentication auth, Model model,
исправил

2020-10-14 14:35 UTC, Boitsovrich commented on src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +        User principal = (User) auth.getPrincipal();
исправил

2020-10-14 14:35 UTC, Boitsovrich commented on src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +        User user = (User) auth.getPrincipal();
исправил

2020-10-14 14:35 UTC, Boitsovrich commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +
исправил

2020-10-14 14:35 UTC, Boitsovrich commented on src/main/resources/templates/customerPage.html
> +            <script type="text/javascript">
исправил

2020-10-14 14:35 UTC, Boitsovrich commented on src/main/resources/templates/customerPage.html
> +                                                        <input type="button" id="pictureBtn" value="Upload Picture"
все ок, косяки были выше
еще раз проверил все работает, пароль меняет, емайл меняет, 
сообщает об ошибках, отправляет уведомления, и выводит все на экран.

2020-10-14 14:48 UTC, Boitsovrich commented on src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
> +        User user = (User) auth.getPrincipal();
исправил

2020-10-14 15:01 UTC, Boitsovrich commented
все ок.

2020-10-14 15:04 UTC, Boitsovrich commented
1

2020-10-14 19:41 UTC, tediik requested changes
+ реши конфликты

2020-10-14 19:41 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
> +            log.debug("Вы ввели такой же Email.");
Кто вы? Логи будет разраб смотреть. Давай напишем
"Попытка ввести дублирующийся email: <email>"
ну и подставим туда конечно нужный email

2020-10-14 19:41 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +    public ResponseEntity<String> changePassword(Model model,
ну ежели он возвращает ResponseEntity - так может в REST-контроллер положим?

2020-10-14 19:41 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +                        log.debug("Пароль изменен!");
неинформативно - у кого пароль изменен?

2020-10-14 19:41 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +                    return new ResponseEntity("ok", HttpStatus.OK);
давай в общепринятом на проекте стиле - через фабричные статические методы, причем не только тут, а вообще все ResponseEntity поправь

2020-10-14 19:41 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +                user.getEmail(),
не очень понятно зачем 1 стринговую переменную причем не очень длинную превращать в 2 с помощью конкатенации, запиши в 1 строчку

2020-10-14 19:41 UTC, tediik commented on src/main/resources/static/js/profile.js
> +type = "text/javascript" >
какой то странный кусок кода.. что это?

2020-10-14 19:41 UTC, tediik commented on src/main/resources/templates/changePassword.html
> +                        <button type="submit" class="btn btn-primary btn-sm btn-block">Сохранить1</button>
почему Сохранить1 ??

2020-10-14 19:41 UTC, tediik commented on src/main/resources/templates/customerPage.html
> +        <div class="col-md-2" style="padding-right: 0px; padding-left: 0px">
убери style, задай тож самое с помощью bootstrap и его стилей

2020-10-14 19:41 UTC, tediik commented on src/main/resources/templates/customerPage.html
> +                                                                смайлики.
Спасибо!!

2020-10-14 19:41 UTC, tediik commented on src/main/resources/templates/customerPage.html
> +                        <div class="col-md-9" style="padding-right: 0px; padding-left: 0px">
убери тут и дальше style, используй стили и возможности bootstrap

2020-10-15 22:16 UTC, Boitsovrich commented on src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
> +            log.debug("Вы ввели такой же Email.");
исправил

2020-10-15 22:27 UTC, Boitsovrich commented on src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +                        log.debug("Пароль изменен!");
исправил

2020-10-16 09:12 UTC, Boitsovrich commented on src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
> +            log.debug("Вы ввели такой же Email.");
исправил

2020-10-16 09:14 UTC, Boitsovrich commented on src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +                        log.debug("Пароль изменен!");
исправил

2020-10-16 09:16 UTC, Boitsovrich commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +                user.getEmail(),
исправил

2020-10-16 09:17 UTC, Boitsovrich commented on src/main/resources/templates/changePassword.html
> +                        <button type="submit" class="btn btn-primary btn-sm btn-block">Сохранить1</button>
исправил

2020-10-16 21:30 UTC, Boitsovrich commented on src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
> +            log.debug("Вы ввели такой же Email.");
исправил

2020-10-21 13:31 UTC, Boitsovrich commented on src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +    public ResponseEntity<String> changePassword(Model model,
сделал

2020-10-21 13:36 UTC, Boitsovrich commented on src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +                        log.debug("Пароль изменен!");
Полностью изменил логику без куча if и else.
Лаконично и в соответствии с правилами проекта.  
User user = userService.getCurrentLoggedInUser();
        if (userService.findById(user.getId()).isEmpty()) {
            log.debug("Нет пользователя с идентификатором: {}", user.getId());
            return ResponseEntity.noContent().build();
        }
        if (ValidationUtils.isNotValidEmail(user.getEmail())) {
            log.debug("Wrong email! Не правильно введен email");
            return ResponseEntity.badRequest().body("notValidEmailError");
        }
        if (!userService.findById(user.getId()).get().getEmail().equals(user.getEmail())
                && userService.isExist(user.getEmail())) {
            log.debug("Пользователь с таким адресом электронной почты уже существует");
            return ResponseEntity.badRequest().body("duplicatedEmailError");
        }
        if (userService.changePassword(user.getId(), oldPassword, newPassword))
            log.debug("Изменения для пользователя с идентификатором: {} был успешно добавлен", user.getId());
        return ResponseEntity.ok().build();

    }

2020-10-21 13:43 UTC, Boitsovrich commented on src/main/resources/templates/customerPage.html
> +        <div class="col-md-2" style="padding-right: 0px; padding-left: 0px">
Брал по аналогии. подобный кусок кода в файлах.
1. newsDetails.html
2. managerPage.html
3. manger_settings.html
4. и еще в пяти файлах. 

исправил

2020-10-21 13:44 UTC, Boitsovrich commented on src/main/resources/templates/customerPage.html
> +                        <div class="col-md-9" style="padding-right: 0px; padding-left: 0px">
исправил

2020-10-21 14:18 UTC, Boitsovrich reviewed
Замечания исправил

2020-10-21 15:10 UTC, tediik requested changes
Исправляй замечания, я помню мы вроде смотрели этот код и он был лучше, ощущение, что тут какие-то траблы с гитом

2020-10-21 15:10 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
> +            log.debug("Вы ввели такой же Email.");
Не исправил

2020-10-21 15:10 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +        return ResponseEntity.ok().build();
если оно возвращает ResponseEntity  - это уже просится в РестКонтроллер

2020-10-21 15:10 UTC, tediik commented on src/main/resources/application.yml
> +    password: Logitech
нууу неее, не пойдет!

2020-10-21 15:10 UTC, tediik commented on src/main/resources/static/js/profile.js
> +    console.log(formData);
не исправил!

2020-10-21 15:10 UTC, tediik commented on src/main/resources/templates/changePassword.html
> +<!--                    </div>-->
лишний код убрать

2020-10-21 15:26 UTC, Boitsovrich commented on src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +        return ResponseEntity.ok().build();
исправил

2020-10-21 15:27 UTC, Boitsovrich commented on src/main/resources/templates/changePassword.html
> +<!--                    </div>-->
исправил

2020-10-21 15:27 UTC, Boitsovrich commented on src/main/resources/application.yml
> +    password: Logitech
понял))

2020-10-21 15:56 UTC, Boitsovrich commented on src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
> +            log.debug("Вы ввели такой же Email.");
@PostMapping("/changemail")
    public ResponseEntity<String> changeMailReq(@RequestParam String newMail) {
        User user = userService.getCurrentLoggedInUser();
        if (userService.isExist(newMail)) {
            log.debug("Попытка ввести дублирующийся email: " + newMail);
            return new ResponseEntity("duplicatedEmailError", HttpStatus.BAD_REQUEST);
        }
        if (ValidationUtils.isNotValidEmail(newMail)) {
            return new ResponseEntity("notValidEmailError", HttpStatus.BAD_REQUEST);
        } else {
            userService.changeUsersMail(user, newMail);
            return ResponseEntity.ok("Email будет изменен после подтверждения.");
        }
    }

2020-10-21 15:58 UTC, Boitsovrich commented on src/main/resources/static/js/profile.js
> +    console.log(formData);
понял исправил

2020-10-21 19:46 UTC, tediik approved these changes

2020-10-21 19:46 UTC, merged