Made the footer of main page and posted price list links.
tediik/online_store pull request #134
Opened 2020-10-16 09:27 UTC by Vyacheslav-Ko

2020-10-17 14:38 UTC, tediik requested changes
Поправь замечания, кроме того, одно из условий задания не выполнено - менеджер должен иметь возможность в кабинете менять время формирования прайса, у нас уже есть аналогичный функционал в кабинете менеджера, по моему по рассылке Акций, посмотри

2020-10-17 14:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/PriceListServiceImpl.java
> +    private static final String PATH_TO_ZIP_FILE = "uploads/files/prices/pricedaily.zip";
время точно сможет задавать в настройках менеджер?

2020-10-17 14:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/PriceListServiceImpl.java
> +    public void createPrice() {
у нас есть специальный класс для целей запуска чего-либо по расписанию - перенеси запуск туда, саму логику можно оставить в этом сервисе

2020-10-17 14:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/PriceListServiceImpl.java
> +            e.printStackTrace();
неплохо бы еще и залогировать ошибку

2020-10-17 14:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/PriceListServiceImpl.java
> +    public void archiveFileWithPrice() {
JavaDoc напиши

2020-10-17 14:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/PriceListServiceImpl.java
> +             FileInputStream fis = new FileInputStream(new File(PATH_TO_XLS_FILE))){
что с кодстайлом?

2020-10-17 14:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/PriceListServiceImpl.java
> +            e.printStackTrace();
логируй эти моменты тоже

2020-10-17 14:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/PriceListServiceImpl.java
> +        archiveFileWithPrice();
если этот метод не используется больше нигде - он должен быть приватным, если вызываешь еще откуда-то - оставляй public

2020-10-17 14:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/PriceListServiceImpl.java
> +        row.createCell(4).setCellValue(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
Я бы создание самого файла xls вынес бы в отдельный приватный метод, такой код удобнее читать и поддерживать

2020-10-17 14:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/PriceListServiceImpl.java
> +        }
тут тоже логируй ошибку

2020-10-17 14:38 UTC, tediik commented on src/main/resources/templates/blocks/footer.html
> +                       th:text="'Создан: ' + ${#dates.format(#dates.createNow(), 'dd.MM.yyyy')} + ' 03:57'"></p>
а что такое 03:57??

2020-10-17 14:38 UTC, tediik commented on src/main/resources/templates/blocks/footer.html
> +                    <p th:style ="${'font-family: arial; font-size: 60%; color: white'}"
все стили вынести и определять через css-файл

2020-10-17 14:38 UTC, tediik commented on src/main/resources/templates/blocks/footer.html
> +                <p>© 2020 Компания Online store. Администрация Сайта не несет ответственности за размещаемые Пользователями информацию и изображения, их содержание и качество.
год тогда уж лучше формировать динамически, не?

2020-10-18 09:47 UTC, Vyacheslav-Ko commented on src/main/java/com/jm/online_store/service/impl/PriceListServiceImpl.java
> +    private static final String PATH_TO_ZIP_FILE = "uploads/files/prices/pricedaily.zip";
Давай я реализую настройку времени из кабинета менеджера, не используя ранее написанный функционал запуска чего-либо по расписанию? Потому что там все - от интерфейса до js-кода и контроллеров, там все заточено под email-рассылку и только под нее.

2020-10-18 20:56 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/PriceListServiceImpl.java
> +    private static final String PATH_TO_ZIP_FILE = "uploads/files/prices/pricedaily.zip";
Есть другие варианты? Делай. Потом расскажешь и покажешь на созвоне, чем твой вариант лучше.

2020-10-22 12:12 UTC, tediik requested changes

2020-10-22 12:12 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/PriceListServiceImpl.java
> +    private static final String PATH_TO_ZIP_FILE = "uploads/files/prices/pricedaily.zip";
вынеси настройку пути в application.properties

2020-10-22 18:36 UTC, tediik approved these changes

2020-10-22 18:36 UTC, merged