Feature/service center
tediik/online_store pull request #135
Opened 2020-10-16 10:47 UTC by ZirPav

Добавил сущность RepairOrder(Заказ на ремонт). Добавил для этой сущности дао слой, сервисный слой, прописал нужные рест контроллеры, добавил enum(по статусам заказа), добавил класс ошибок.
Создал новую роль Service.
Создал для этой роли кабинет. В данном кабинете осуществляется работа с сущностью RepairOrder(Заказ на ремонт), возможность удаления, редактирования и создание заказов на ремонт.
Добавил возможность проверки статуса своего заказа для не авторизованного пользователя.

2020-10-17 15:13 UTC, tediik requested changes
Кода ооочень много, проделана большая работа, тем не менее есть замечания, исправляй и уже есть конфликты, перед пушем не забудь слить свежий dev и аккуратно замерджить

2020-10-17 15:13 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/RepairOrderRestController.java
> +        return ResponseEntity.ok().body(repairOrderList);
проверь тут и везде в контроллере, по-моему можно писать сразу:
return ResponseEntity.ok(repairOrderList);

2020-10-17 15:13 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ServiceRestController.java
> +}
работник сервисного центра - такой же юзер, как и менеджер и покупатель и админ, почему мы не можем держать эту логику в userService? у нас что изменение например email сейчас у каждой роли происходит в своем отдельном сервисе??

2020-10-17 15:13 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/ServiceCenterController.java
> +    }
а зачем так? у нас же есть Ломбок, напиши в общем стиле, убери контроллер, поставь аннотацию

2020-10-17 15:13 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/ServiceCenterController.java
> +    }
мне кажется страничку профиля и прочие действия с ней тоже надо держать в каком-то едином для всех профилей месте, ощущение, что мы сейчас просто дублируем функционал

2020-10-17 15:13 UTC, tediik commented on src/main/resources/static/js/repairOrder.js
> +        fetch('http://localhost:9999/service/addRepairOrder', {
относительные ссылки!

2020-10-17 15:13 UTC, tediik commented on src/main/resources/static/js/repairOrder.js
> +    fetch('http://localhost:9999/service/getAllRepairOrder')
тут и везде далее проверь - ссылки только относительные!

2020-10-17 15:13 UTC, tediik commented on src/main/resources/static/js/serviceCheckStatus.js
> +    fetch('http://localhost:9999/api/checkStatus', {
тут и проверь везде далее - ссылки только относительные!

2020-10-17 15:13 UTC, tediik commented on src/main/resources/templates/blocks/mainHeader.html
> +           href="/service">Кабинет сервисного работника</a>
да, ну вот, я об этом и говорил - ссылка на профиль то одинаковая вроде как у нас

2020-10-17 15:13 UTC, tediik commented on src/main/resources/templates/products.html
> +    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
и зачем нам 2 ссылки на bootstrap??

2020-10-17 15:13 UTC, tediik commented on src/main/resources/templates/subcategoryPage.html
> +    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
почему тогда не удалил выше ссылку на bootstrap.min.css младшей версии?

2020-10-17 15:13 UTC, tediik commented on src/main/resources/templates/servicePage.html
> +</script>
я думаю это все же надо вынести в файл

2020-10-17 15:26 UTC, ZirPav commented on src/main/java/com/jm/online_store/controller/simple/ServiceCenterController.java
> +    }
ок

2020-10-17 15:28 UTC, ZirPav commented on src/main/java/com/jm/online_store/controller/rest/ServiceRestController.java
> +}
наверное можем, но у нас сделано отдельно для покупателя, и что-то сделано для менеджера и админа(что у меня вообщем-то не работает), поэтому я написал отдельно для сервиса.

2020-10-17 15:29 UTC, ZirPav commented on src/main/java/com/jm/online_store/controller/rest/RepairOrderRestController.java
> +        return ResponseEntity.ok().body(repairOrderList);
хорошо

2020-10-17 15:29 UTC, ZirPav commented on src/main/java/com/jm/online_store/controller/simple/ServiceCenterController.java
> +    }
Возможно так и есть, для этого надо сделать стабильный и рабочий профиль, унифицированный

2020-10-17 15:30 UTC, ZirPav commented on src/main/resources/static/js/repairOrder.js
> +        fetch('http://localhost:9999/service/addRepairOrder', {
хорошо

2020-10-17 15:30 UTC, ZirPav commented on src/main/resources/templates/blocks/mainHeader.html
> +           href="/service">Кабинет сервисного работника</a>
опять же у нас профиль для админа и менеджера одинаковый, но там функционал не ок

2020-10-17 15:31 UTC, ZirPav commented on src/main/resources/templates/servicePage.html
> +</script>
хорошо, просто думал слишком маленькие функции для отдельного файла

2020-10-17 16:46 UTC, ZirPav commented on src/main/resources/templates/products.html
> +    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
Странно чего я вообще полез в продукты) Наверное копировал стили.

2020-10-17 16:47 UTC, ZirPav commented on src/main/resources/templates/subcategoryPage.html
> +    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
Аналогично замечанию выше)

2020-10-18 21:32 UTC, tediik approved these changes
Покажешь завтра функционал в работе на созвоне, замечаний вроде нет

2020-10-19 16:21 UTC, merged