feature/ManagerActionsNews
tediik/online_store pull request #137
Opened 2020-10-18 23:24 UTC by IrekNabiullin

2020-10-26 15:03 UTC, tediik requested changes
Так не пойдет! У тебя тут кроме твоего кода еще куча из другой ветки, как минимум из ветки Кирилла, а может и еще чьи есть, разберись

2020-10-26 18:35 UTC, IrekNabiullin commented
Исправлено. Отклонения смёрджены

2020-10-26 18:55 UTC, tediik requested changes
+ разберись с тем, чтобы в PR не было всей этой массы картинок для акций - проект станет слишком тяжелым, если надо - оставь какую-то одну картинку по дефолту которая для акций и/или новостей, остальное коммитить не надо

2020-10-26 18:55 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/StockServiceImpl.java
> +
начни доброе дело в этом классе - напиши к своему методу JavaDoc

2020-10-26 18:55 UTC, tediik commented on src/main/resources/templates/mainPage.html
> +                                      href="stocks/" role="button">Подробнее &raquo;</a>
все инлайн-стили вынести в css-файл

2020-10-26 18:55 UTC, tediik commented on src/main/resources/templates/mainPage.html
> +            <h4 class="my-1 font-weight-normal" style="margin-left: -30px"><a class="text-secondary" href="/news">Обзоры
все инлайн-стили вынести в css-файл

2020-10-26 18:55 UTC, tediik commented on src/main/resources/templates/mainPage.html
> +                                          href="news/" role="button">Подробнее &raquo;</a>
все инлайн-стили вынести в css-файл

2020-10-26 18:55 UTC, tediik commented on src/main/resources/templates/stockGlobalPage.html
> +                    <img th:src="@{../../uploads/images/stocks/{name}(name = ${stock.stockImg})}" width="400"
все инлайн-стили вынести в css-файл

2020-10-26 18:55 UTC, tediik commented on src/main/resources/static/js/mainPage.js
> +                                <p><a class="btn btn-secondary" style="margin-top: 50px; margin-left: -252px"
стили должны подхватываться из внешнего css-файла

2020-10-26 18:55 UTC, tediik commented on src/main/resources/static/js/mainPage.js
> +                             src="/uploads/images/news/${key}.jpg" width="400" height="200"
стили должны подхватываться из внешнего css-файла

2020-10-26 18:55 UTC, tediik commented on src/main/resources/static/js/mainPage.js
> +                                <p><a class="btn btn-secondary" style="margin-top: 50px; margin-left: -252px"
стили должны подхватываться из внешнего css-файла

2020-10-26 18:55 UTC, tediik commented on src/main/resources/templates/stocksPage.html
> +                <img th:src="@{../../uploads/images/stocks/{name}(name = ${stock.stockImg})}" width="400"
стили должны подхватываться из внешнего css-файла

2020-10-26 19:44 UTC, IrekNabiullin commented on src/main/java/com/jm/online_store/service/impl/StockServiceImpl.java
> +
продолжил добрые дела и написал JavaDoc к своему методу

2020-10-26 20:51 UTC, IrekNabiullin commented on src/main/resources/templates/stocksPage.html
> +                <img th:src="@{../../uploads/images/stocks/{name}(name = ${stock.stockImg})}" width="400"
выполнено

2020-10-26 20:51 UTC, IrekNabiullin commented on src/main/resources/static/js/mainPage.js
> +                                <p><a class="btn btn-secondary" style="margin-top: 50px; margin-left: -252px"
выполнено

2020-10-26 20:51 UTC, IrekNabiullin commented on src/main/resources/static/js/mainPage.js
> +                             src="/uploads/images/news/${key}.jpg" width="400" height="200"
выполнено

2020-10-26 20:51 UTC, IrekNabiullin commented on src/main/resources/static/js/mainPage.js
> +                                <p><a class="btn btn-secondary" style="margin-top: 50px; margin-left: -252px"
выполнено

2020-10-26 20:51 UTC, IrekNabiullin commented on src/main/resources/templates/stockGlobalPage.html
> +                    <img th:src="@{../../uploads/images/stocks/{name}(name = ${stock.stockImg})}" width="400"
выполнено

2020-10-26 20:51 UTC, IrekNabiullin commented on src/main/resources/templates/mainPage.html
> +                                          href="news/" role="button">Подробнее &raquo;</a>
выполнено

2020-10-26 20:51 UTC, IrekNabiullin commented on src/main/resources/templates/mainPage.html
> +            <h4 class="my-1 font-weight-normal" style="margin-left: -30px"><a class="text-secondary" href="/news">Обзоры
выполнено

2020-10-26 20:52 UTC, IrekNabiullin commented on src/main/resources/templates/mainPage.html
> +                                      href="stocks/" role="button">Подробнее &raquo;</a>
выполнено

2020-10-27 13:45 UTC, tediik approved these changes

2020-10-27 13:45 UTC, merged