Feature/buyer profile add restore
tediik/online_store pull request #142
Opened 2020-10-23 12:01 UTC by DeMaN357

2020-10-23 17:22 UTC, ZirPav commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +     * @return
return пустой

2020-10-23 17:22 UTC, ZirPav commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +     * @return
тоже пустой return

2020-10-23 17:22 UTC, ZirPav commented on src/main/resources/static/js/customerProfilePageFunctions.js
> +        method: 'POST',
Какой смысл в этом маневре, если тела запроса нет?

2020-10-23 17:22 UTC, ZirPav commented on src/main/resources/static/js/loginNoLinkFacebook.js
> +            toastr.success(res, {timeOut: 50000});
50 секунд?

2020-10-24 15:07 UTC, tediik requested changes

2020-10-24 15:07 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AllUsersRestController.java
> +                return ResponseEntity.badRequest().body("Все хорошо, идет дальше!");
почему все хорошо, но при этом отдает badRequest??

2020-10-24 15:07 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
>       * Метод удаления профиля покупателя
Поправь тогда уж и описание, раз метод больше не удаляет покупателя.
Метод changeUserStatus лучше назвать конкретнее, например changeUserStatusToLocked

2020-10-24 15:07 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +import java.util.*;
asterisk import! У нас в настройке описано, как нужно настраивать Идею, чтобы этого не было! Верни обратно конкретные импорты

2020-10-24 15:07 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        if (user.get().getStatus() == null) {
Хочу описание к этому методу

2020-10-24 15:07 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +     * Метод, который изменяет статус пользователя при нажатии на кнопку "удалить профиль"
У нас в качестве статуса - время удаления, распиши понятнее, чтобы любой мог понять, что ты тут делаешь

2020-10-24 15:07 UTC, tediik commented on src/main/resources/static/js/loginNoLinkFacebook.js
> +/**
Весь остальной код не соответствует названию самого файла, похоже надо положить в отдельный файл!

2020-10-24 15:07 UTC, tediik commented on src/main/resources/templates/login.html
> +
для чего эта куча пробелов?

2020-10-24 15:07 UTC, tediik commented on src/main/resources/templates/login.html
> +<script src="../static/js/jquery.fias.min.js" type="text/javascript"></script>
а зачем тут /static/js/jquery.fias.min.js ??

2020-10-25 19:49 UTC, tediik requested changes
Ни одно замечание не исправлено (на самом деле я проверил только 4, остальное даже не стал смотреть) - проверь, вероятно забыл что то закоммитить и выложить

2020-10-25 22:49 UTC, tediik approved these changes

2020-10-25 22:49 UTC, merged