Feature/list questions and answers feedback
tediik/online_store pull request #143
Opened 2020-10-23 13:02 UTC by ZirPav

В кабинете покупателя, можно посмотреть все свои обращения и ответы на них.
В кабинете менеджера, отсортированы все обращения покупателей, можно давать на них ответы,
откладывать на потом.

2020-10-24 13:58 UTC, tediik requested changes
Мелкие замечания + поправь конфликты

2020-10-24 13:58 UTC, tediik commented on src/main/java/com/jm/online_store/model/Feedback.java
> +    @ManyToOne(fetch = FetchType.EAGER)
@ManyToOne - загляни во внутренности, она уже по умолчанию EAGER, можно это не писать

2020-10-24 13:58 UTC, tediik commented on src/main/resources/static/js/customer-feedback-form.js
> +                console.log('Что-то не ладное творится в наших чертогах.')
прикольно, но не информативно

2020-10-24 13:59 UTC, ZirPav commented on src/main/java/com/jm/online_store/model/Feedback.java
> +    @ManyToOne(fetch = FetchType.EAGER)
точно забыл

2020-10-24 14:00 UTC, ZirPav commented on src/main/resources/static/js/customer-feedback-form.js
> +                console.log('Что-то не ладное творится в наших чертогах.')
Блин, забыл исправить у покупателя)

2020-10-25 19:18 UTC, tediik approved these changes

2020-10-25 19:18 UTC, merged