Feature/favourites groups
tediik/online_store pull request #144
Opened 2020-10-24 16:00 UTC by vladstar25

Работа со списками избранных товаров

2020-10-25 13:56 UTC, ZirPav commented on src/main/java/com/jm/online_store/controller/rest/ProductForFavouritesGroupRestController.java
> +        //favouritesGroupProductService.getProductSet(favouritesGroup, user);
Наверное лишний.

2020-10-25 13:56 UTC, ZirPav commented on src/main/java/com/jm/online_store/model/FavouritesGroup.java
> +    User user;
Я не пойму, неужели необходимы все эти аннотации? JsonIgnoreProperties, JsonProperty, если в итоге мы поле просто игнорим JsonIgnore?

2020-10-25 13:56 UTC, ZirPav commented on src/main/java/com/jm/online_store/model/User.java
> +    //Попробовать это убрать!
Комментарий нужен?

2020-10-25 13:56 UTC, ZirPav commented on src/main/java/com/jm/online_store/model/User.java
> +    private Set<FavouritesGroup> favouritesGroups = new HashSet<>();
разве OneToMany не LAZY изначально?

2020-10-25 13:56 UTC, ZirPav commented on src/main/java/com/jm/online_store/repository/FavouritesGroupRepository.java
> +    FavouritesGroup getOneFavouritesGroupByUserAndById(@Param("user") User user, @Param("id") Long id);
Я не совсем понимаю, зачем прописывать запрос если уже используешь ключевые комбинации в написании методов.

2020-10-25 19:46 UTC, tediik requested changes

2020-10-25 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGoodsRestController.java
> +        //
эту строчку убрать

2020-10-25 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGoodsRestController.java
> +        //Добавляем продукт в список избранного "Все товары"
вынеси этот коммент в описание к методу

2020-10-25 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGoodsRestController.java
> +        // Удаляем продукт из списка "Все товары"
вынеси в описание метода

2020-10-25 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGoodsRestController.java
> +        //
строчку удалить

2020-10-25 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGroupRestController.java
> +}
JavaDoc ко ВСЕМ методам. Общую часть url - /customer/favouritesGroup - вынеси в заголовок класса

2020-10-25 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ProductForFavouritesGroupRestController.java
> +    }
JavaDoc ко всем методам, общую часть url вынести в заголовок контроллера

2020-10-25 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/model/FavouritesGroup.java
> +    @Id
Добавь описание для чего этот класс

2020-10-25 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/model/FavouritesGroup.java
> +    @JsonProperty(value = "user")
по моему что-то из этого лишнее

2020-10-25 19:46 UTC, tediik commented on src/main/resources/templates/wishlist.html
> +<script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
это что такое?

2020-10-25 19:46 UTC, tediik commented on src/main/resources/static/js/customer.js
> + //   if ($('.ch_select_all').is(':checked')){
лишний код везде в этом файле - пробегись и убери!

2020-10-25 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +import com.jm.online_store.model.FavouritesGroup;
так эта зависимость тут вроде не используется?

2020-10-25 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/FavouritesGroupProductServiceImpl.java
> +    }
добавь описания ко всем методам

2020-10-25 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/FavouritesGroupProductServiceImpl.java
> +        productSet.remove(product);
честно говоря очень странный подход, почему нам надо получать у юзера все группы, а потом искать в них первое совпадение с тем, что у нас пришло в параметрах? Почему сразу не сказать, что пришедшее в параметрах - это то, что нам нужно??
Если этот велосипед никак не исправить - тогда предлагаю хотя бы похожий во всех трех методах код вынести в отдельный приватный метод. Но лучше, конечно, понять, что за велосипед и зачем он нужен и как сделать хорошо.

2020-10-26 12:42 UTC, vladstar25 commented on src/main/resources/templates/wishlist.html
> +<script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
Это первая попытка сделать таску ). Подчистил.)

2020-10-26 12:42 UTC, vladstar25 commented on src/main/java/com/jm/online_store/controller/rest/ProductForFavouritesGroupRestController.java
> +        //favouritesGroupProductService.getProductSet(favouritesGroup, user);
Удалил

2020-10-26 12:43 UTC, vladstar25 commented on src/main/java/com/jm/online_store/model/User.java
> +    //Попробовать это убрать!
Удалил

2020-10-26 12:43 UTC, vladstar25 commented on src/main/java/com/jm/online_store/model/User.java
> +    private Set<FavouritesGroup> favouritesGroups = new HashSet<>();
Удалил

2020-10-26 12:43 UTC, vladstar25 commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGoodsRestController.java
> +        //
Ок

2020-10-26 12:43 UTC, vladstar25 commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGoodsRestController.java
> +        //Добавляем продукт в список избранного "Все товары"
Ок. Сделал

2020-10-26 12:43 UTC, vladstar25 commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGoodsRestController.java
> +        // Удаляем продукт из списка "Все товары"
Ок. Сделал.

2020-10-26 12:44 UTC, vladstar25 commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGoodsRestController.java
> +        //
Удалил

2020-10-26 12:44 UTC, vladstar25 commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGroupRestController.java
> +}
Ок. Сделал

2020-10-26 12:48 UTC, vladstar25 commented on src/main/resources/static/js/customer.js
> + //   if ($('.ch_select_all').is(':checked')){
Ок. Поправил

2020-10-26 12:51 UTC, vladstar25 commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +import com.jm.online_store.model.FavouritesGroup;
Убрал

2020-10-26 15:19 UTC, vladstar25 commented on src/main/java/com/jm/online_store/service/impl/FavouritesGroupProductServiceImpl.java
> +        productSet.remove(product);
Исправил

2020-10-26 15:19 UTC, vladstar25 commented on src/main/java/com/jm/online_store/service/impl/FavouritesGroupProductServiceImpl.java
> +    }
Исправил

2020-10-26 18:29 UTC, tediik requested changes
Замечания + конфликты

2020-10-26 18:29 UTC, tediik commented on src/main/java/com/jm/online_store/model/FavouritesGroup.java
> +    @JsonProperty(value = "user")
этот момент не решен, ответа нет

2020-10-26 18:29 UTC, tediik commented on src/main/java/com/jm/online_store/model/FavouritesGroup.java
> +    @Id
это замечание проигнорировал

2020-10-26 18:29 UTC, tediik commented on src/main/resources/static/js/customer.js
> + * Закрываем модулку
модалку

2020-10-27 02:01 UTC, vladstar25 commented on src/main/resources/static/js/customer.js
> + * Закрываем модулку
Исправил

2020-10-27 12:05 UTC, tediik approved these changes

2020-10-27 12:05 UTC, merged