Bugix/admin panel fixes
tediik/online_store pull request #15
Opened 2020-08-16 19:33 UTC by neuromanzer

2020-08-17 15:37 UTC, tediik requested changes
Ты бросаешь новые excepton но я правильно понимаю, что нигде это не обрабатываешь??

2020-08-17 15:37 UTC, tediik commented on docker-compose.yml
> +  db_vol:
Зачем нам лишние конфиги в проекте? Настрой у себя gitignore, файл убирай из коммита

2020-08-17 15:37 UTC, tediik commented on src/main/java/com/jm/online_store/model/User.java
> +            cascade = CascadeType.ALL)
Нам точно нужен будет ALL?

2020-08-17 15:37 UTC, tediik commented on src/main/java/com/jm/online_store/service/UserServiceImpl.java
> +        userSetRoles.add(userRole);
Чем не устроил старый вариант?

2020-08-17 15:37 UTC, tediik commented on src/main/resources/static/main.js
> +                    alert(jqXhr.responseJSON.message);
Хм.. не уверен, что нам нужны Алерты, давай уберем

2020-08-17 17:10 UTC, tediik commented
![](https://github.trello.services/images/mini-trello-icon.png) [Кабинет админа](https://trello.com/c/XBN5bNP4/34-%D0%BA%D0%B0%D0%B1%D0%B8%D0%BD%D0%B5%D1%82-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B0)

2020-08-21 10:55 UTC, tediik requested changes

2020-08-21 10:55 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/SecurityConfig.java
> +                .antMatchers("/test-reg").permitAll()
это что за url?

2020-08-21 10:55 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/SecurityConfig.java
> +                .and().and().authorizeRequests().antMatchers("/customer").hasRole("CUSTOMER");
мне кажется 1 .and() лишний

2020-08-21 10:55 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/TestRegController.java
> +}
Надо бы пояснить, для чего нам этот контроллер?

2020-08-21 10:55 UTC, tediik commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/online_store?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
убери, верни старую строчку

2020-08-21 10:55 UTC, tediik commented on src/main/resources/templates/test-reg.html
> +</body>
Нужно пояснение что это за страничка?

2020-08-21 19:45 UTC, neuromanzer commented on src/main/java/com/jm/online_store/config/security/SecurityConfig.java
> +                .and().and().authorizeRequests().antMatchers("/customer").hasRole("CUSTOMER");
изначально было также 2 .and
при попытке убрать один выделяется красным .authorizeRequests()

2020-08-22 18:34 UTC, tediik approved these changes

2020-08-22 18:34 UTC, merged