Stocks
tediik/online_store pull request #16
Opened 2020-08-18 09:51 UTC by AntonMoskvin

2020-08-19 19:58 UTC, tediik requested changes

2020-08-19 19:58 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/StockRest.java
> +    }
Давай сделаем констуктор через Ломбок

2020-08-19 19:58 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/StockRest.java
> +        return ResponseEntity.ok().body(stock);
Убери пустые строки, тут нет разделения на логические блоки

2020-08-19 19:58 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/StockRest.java
> +
лишняя пустая строка

2020-08-19 19:58 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/StockRest.java
> +
кодстайл

2020-08-19 19:58 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/StockRest.java
> +
Пробегись по всему контроллеру, очень много где пустые строчки, которые вообще не нужны

2020-08-19 19:58 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/StocksController.java
> +
убери 1 пустую строчку

2020-08-19 19:58 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/StocksController.java
> +
конструктор через Ломбок

2020-08-19 19:58 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/StocksController.java
> +
лишняя строчка

2020-08-19 19:58 UTC, tediik commented on src/main/java/com/jm/online_store/model/StockEnum.java
> +}
Назови это StockType и перенеси в Stock + сделай приватным, оно нужно только внутри класса Stock

2020-08-19 19:58 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/StockServiceImpl.java
> +    }
консструктор через Ломбок

2020-08-19 19:58 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/StockServiceImpl.java
> +
лишняя строчка

2020-08-19 19:58 UTC, tediik commented on src/main/resources/static/css/style.css
> +}
Если этот файл используется только внутри одной страницы, например Акции - ему нужно дать соответствующее странице имя

2020-08-19 19:58 UTC, tediik commented on src/main/resources/static/js/stocks.js
> +/////////////////////Вывод акций///////////////////////////
воу воу! )) давай ограничимся стандартным комментарием, почисти во всем файле, плиз

2020-08-19 19:58 UTC, tediik commented on src/main/resources/static/js/stocks.js
> +                );
Нет, только не таким способом, почитай/посмотри про шаблонные строки в JS и перепиши этот же код красиво, т.е. в том числе с нормальным выравниванием вложенных тегов

2020-08-19 19:58 UTC, tediik commented on src/main/resources/static/js/stocks.js
> +            // document.body.style.background = "red"
лишний код удаляем перед отправкой PR!

2020-08-19 19:58 UTC, tediik commented on src/main/resources/static/js/stocks.js
> +            // document.body.style.background = "green"
убрать лишний код

2020-08-19 19:58 UTC, tediik commented on src/main/resources/templates/stocks.html
> +                 style="background-color: #ffffff; border-radius: 10px;">
вот ты вроде подключил специально файл стилей и вынес туда оформление, но все равно используешь внутри inline стили, постарайся во всем файле убрать по максимуму работу со стилями в свой css

2020-08-20 10:39 UTC, tediik requested changes

2020-08-20 10:39 UTC, tediik commented on src/main/java/com/jm/online_store/model/Stock.java
> +        StockType(String title) { }
точно нужен публичный? где то еще используется?
первый раз просмотрел - зачем тебе конструктор и текстовое значение 1 в 1 соответствующее значению самого перечисления??

2020-08-20 10:39 UTC, tediik commented on src/main/resources/static/js/stocks.js
> +                + "</li>" );
Еще раз, почитай про шаблонные строки в JS и перепиши код без конкатенаций, за выравнивание большой жирный ПЛЮС!

2020-08-20 11:14 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/model/Stock.java
> +        StockType(String title) { }
нужен публичный, используется в контроллере

2020-08-20 12:15 UTC, AntonMoskvin commented on src/main/resources/static/js/stocks.js
> +                + "</li>" );
да, так красиво и удобно!

2020-08-20 12:19 UTC, tediik approved these changes

2020-08-20 12:19 UTC, merged