Merge branch 'dev' into Feature/productCategoriesCRUD
tediik/online_store pull request #160
Opened 2020-11-13 05:10 UTC by sudden-ignition

2020-11-13 08:27 UTC, tediik requested changes
Вот неполный список замечаний )))

2020-11-13 08:27 UTC, tediik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> -        favouritesGroupService.save(favouritesGroup);
А функционал инициализации списка избранных товаров куда делся?

2020-11-13 08:27 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/MainPageRestController.java
> +     *
учитывая что саму реализацию ты все равно удалил - перепиши и JavaDoc на актуальный

2020-11-13 08:27 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ManagerProductsRestController.java
> +    public ResponseEntity<Product> addProductM(@RequestBody Product product, @PathVariable Long id) {
кстати, а почему с префиксом М - addProductM??

2020-11-13 08:27 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ManagerProductsRestController.java
> -    }
Я думаю как раз таки этот функционал стоило закомментировать и написать комменть //todo: и описание, почему закомментирован и что нужно сделать

2020-11-13 08:27 UTC, tediik commented on src/main/java/com/jm/online_store/model/Categories.java
> +    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL) // ALL -??? EAGER - ?
если нам всегда при работе с категориями нужны все-все продукты, к ней привязанные, в чем я сомневаюсь, тогда да - пусть будет eager, в противном случае настаиваю, что нужно переделать на lazy

2020-11-13 08:27 UTC, tediik commented on src/main/java/com/jm/online_store/model/Categories.java
> +//    private List<Product> products;
это убирай

2020-11-13 08:27 UTC, tediik commented on src/main/java/com/jm/online_store/model/Product.java
> +    public Product(String product, double price, int amount) {
странно как-то, почему нет единообразия? в самом верхнем конструкторе у тебя это обертки, а тут поменял на примитивы?

2020-11-13 08:27 UTC, tediik commented on src/main/resources/static/js/mainPage.js
> +    let subdata = await fetch("/api/categories/sub/7").then(response => response.json());
а что тут цифра 7 означает??

2020-11-13 08:27 UTC, tediik commented on src/main/resources/static/js/mainPage.js
> +    console.log('subdata - ' + is.empty(subdata));
это убирай

2020-11-13 08:27 UTC, tediik commented on src/main/resources/static/js/mainPage.js
> +/*    for (let key in data) {
убирай лишний код

2020-11-13 08:27 UTC, tediik commented on src/main/resources/templates/products.html
> +    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet"> <!--это здесь зачем?-->
разберись и удали, если не нужно!

2020-11-13 08:27 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/CategoriesServiceImpl.java
> +        return resultArray;
не очень понимаю что за библиотека для создания JSONArray и чем плох встроенный Jackson, почему нельзя было его использовать?

2020-11-13 09:56 UTC, sudden-ignition commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> -        favouritesGroupService.save(favouritesGroup);
Да - косяк. Вернул на место.

2020-11-13 10:00 UTC, sudden-ignition commented on src/main/java/com/jm/online_store/controller/rest/ManagerProductsRestController.java
> +    public ResponseEntity<Product> addProductM(@RequestBody Product product, @PathVariable Long id) {
Он до меня так назывался уже - я тоже обратил внимание на М, но трогать не стал.

2020-11-13 10:23 UTC, sudden-ignition commented on src/main/java/com/jm/online_store/controller/rest/ManagerProductsRestController.java
> -    }
Вернул на место и закомментировал. Карточку в Трелло про функционал страницы рейтинга создал.

2020-11-13 10:27 UTC, sudden-ignition commented on src/main/java/com/jm/online_store/model/Categories.java
> +    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL) // ALL -??? EAGER - ?
Я так и хотел - забыл протестить. Исправил.

2020-11-13 10:27 UTC, sudden-ignition commented on src/main/java/com/jm/online_store/model/Categories.java
> +//    private List<Product> products;
done

2020-11-13 10:31 UTC, sudden-ignition commented on src/main/java/com/jm/online_store/model/Product.java
> +    public Product(String product, double price, int amount) {
Изначально везде были примитивы - вернул к первоначальному виду.

2020-11-13 10:37 UTC, sudden-ignition commented on src/main/resources/static/js/mainPage.js
> +    let subdata = await fetch("/api/categories/sub/7").then(response => response.json());
Это эксперименты были какие-то - удалил.

2020-11-13 10:37 UTC, sudden-ignition commented on src/main/resources/static/js/mainPage.js
> +    console.log('subdata - ' + is.empty(subdata));
удалил

2020-11-13 10:38 UTC, sudden-ignition commented on src/main/resources/static/js/mainPage.js
> +/*    for (let key in data) {
done

2020-11-13 10:39 UTC, sudden-ignition commented on src/main/java/com/jm/online_store/service/impl/CategoriesServiceImpl.java
> +        return resultArray;
Я сейчас точно не скажу - я пару дней с этим JSON'ом экспериментировал (долго прилетал кривой json на фронт) и видимо, тот способ, что заработал нормально первым - его и оставил.

2020-11-13 10:45 UTC, sudden-ignition commented on src/main/resources/templates/products.html
> +    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet"> <!--это здесь зачем?-->
Оказывается - нужно.

2020-11-14 15:48 UTC, tediik requested changes
Реши конфликт и в ManagerProductsRestController переименуй все же метод addProductM по нормальному :)

2020-11-14 16:01 UTC, tediik requested changes
в ManagerProductsRestController переименуй метод addProductM

2020-11-14 16:04 UTC, tediik approved these changes

2020-11-14 16:05 UTC, merged