add comments to review
tediik/online_store pull request #163
Opened 2020-11-15 15:22 UTC by moshkovdenis

2020-11-16 08:07 UTC, KuGa-Do reviewed
Функционал проверил , вроде все четко , отзыв оставляется ,  его можно комментировать ... вроде бы все норм . По java doc написал комменты , лучше уточнить у Эдуарда

2020-11-16 08:07 UTC, KuGa-Do commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +     */
Как по мне норм на английском , но вроде ,в правилах проекта написано писать java.doc на русском

2020-11-16 08:07 UTC, KuGa-Do commented on src/main/java/com/jm/online_store/controller/rest/ReviewRestController.java
> +     */
Тоже самое , ну наверно , это лучше у Эдуарда уточнить

2020-11-16 08:07 UTC, KuGa-Do commented on src/main/java/com/jm/online_store/model/Review.java
Здесь наверно тоже лучше добавить описание что это за сущность и зачем она , чтоб потом кому-нибудь долго не вникать

2020-11-16 08:13 UTC, KuGa-Do commented on src/main/java/com/jm/online_store/model/Review.java
Бля сори  , не то отметил .  Я имел в виду , там где класс сущностей , написать что это и зачем они .

2020-11-16 17:26 UTC, tediik requested changes

2020-11-16 17:26 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +     *
не нужны они на самом деле две пустые строчки тут, по крайней мере одна точно лишняя

2020-11-16 17:26 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +                    String.format("Request contains incorrect data = [%s]", getErrors(bindingResult)));
добавь также вывод ошибки в лог

2020-11-16 17:26 UTC, tediik commented on src/main/java/com/jm/online_store/model/dto/ReviewForCommentDto.java
> +public class ReviewForCommentDto {
добавь описание к сущности, что чего для чего

2020-11-16 17:26 UTC, tediik commented on src/main/resources/static/js/reviews.js
> +                            </div>`));
сделай плиз разметку, ну т.е. вложенные элементы должны быть сдвинуты на 1 табуляцию вправо, как это принято в html

2020-11-16 17:26 UTC, tediik commented on src/main/resources/static/js/reviews.js
> +                                    <div class="commentReviewBoxSpace" id='commentReviewBoxSpace${review.id}'></div>
и тут разметку

2020-11-16 17:26 UTC, tediik commented on src/main/resources/static/js/reviews.js
> +                                </div>`);
вот, отлично!

2020-11-16 17:26 UTC, tediik commented on src/main/resources/static/js/reviews.js
> +                toastr.error("ведите текст...");
введите

2020-11-16 17:26 UTC, tediik commented on src/main/resources/static/js/reviews.js
> +                            </div>`).last());
и тут поправь разметку!

2020-11-17 10:26 UTC, tediik requested changes

2020-11-17 10:26 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +            log.error(String.format("Request contains incorrect data = [%s]", getErrors(bindingResult)));
у логгера есть свой формат написания, форматированная строка тут не нужна, посмотри есть примеры в проекте

2020-11-17 10:26 UTC, tediik commented on src/main/java/com/jm/online_store/model/dto/ReviewForCommentDto.java
> + * для дальнейщей отправки в ResponseEntity в виде Json.
дальнейШей

2020-11-17 12:03 UTC, tediik approved these changes

2020-11-17 12:03 UTC, merged