Merge branch 'dev' into refactor/toastr_no_product
tediik/online_store pull request #169
Opened 2020-11-23 08:13 UTC by kroveks

2020-11-23 10:56 UTC, Kirill1504 commented on src/main/java/com/jm/online_store/controller/rest/BasketRestController.java
> +import com.jm.online_store.exception.ProductsNotFoundException;
Дублируется импорт

2020-11-23 11:12 UTC, Kirill1504 commented on src/main/java/com/jm/online_store/controller/rest/BasketRestController.java
> +import com.jm.online_store.exception.ProductsNotFoundException;
Дублируется импорт

2020-11-23 11:12 UTC, Kirill1504 commented on src/main/java/com/jm/online_store/controller/rest/BasketRestController.java
> +            //return ResponseEntity.status(HttpStatus.NOT_MODIFIED).build();
Убрать закомменченный код

2020-11-23 11:12 UTC, Kirill1504 commented on src/main/java/com/jm/online_store/controller/rest/MainPageRestController.java
> +    //    return ResponseEntity.ok(productService.findAll());
Убрать закоменченный код

2020-11-23 11:12 UTC, Kirill1504 commented on src/main/java/com/jm/online_store/controller/rest/MainPageRestController.java
>          return ResponseEntity.ok(productService.findNumProducts(15));
Не нашел где используется метод. Не очень понял, почему именно 15

2020-11-23 11:12 UTC, Kirill1504 commented on src/main/java/com/jm/online_store/service/impl/BasketServiceImpl.java
> +import com.jm.online_store.exception.ProductsNotFoundException;
Дублируется импорт

2020-11-23 11:12 UTC, Kirill1504 commented on src/main/java/com/jm/online_store/service/impl/BasketServiceImpl.java
> +                System.out.println("Корзина не обновилась");
Как я понял, тут нужно использовать логгер

2020-11-23 11:12 UTC, Kirill1504 commented on src/main/java/com/jm/online_store/service/impl/BasketServiceImpl.java
> +            System.out.println("Закончился товар в бд");
И тут тоже - логгер

2020-11-23 13:18 UTC, kroveks commented on src/main/java/com/jm/online_store/controller/rest/BasketRestController.java
> +import com.jm.online_store.exception.ProductsNotFoundException;
Это два разных исключения

2020-11-23 14:57 UTC, tediik requested changes

2020-11-23 14:57 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/ProductServiceImpl.java
> +        return amount;
объедини в 1 строчку, не создавай отдельные переменные для таких случаев

2020-11-23 14:57 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/BasketServiceImpl.java
> +                throw new ProductsNotFoundException("products zakonchilis");
ужс.. или на англ. или уже по русски давай

2020-11-23 14:57 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/BasketServiceImpl.java
> +                   basket.setCount(basket.getCount() + 1);
а с инкрементом красивее ))

2020-11-23 14:57 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/BasketServiceImpl.java
> +       if(amount <= 0) {
если ты больше нигде не используешь переменную amount - нечего ее и заводить ради одной строчки, убирай

2020-11-23 15:37 UTC, kroveks commented on src/main/java/com/jm/online_store/service/impl/BasketServiceImpl.java
> +       if(amount <= 0) {
Да, до этого использовал, в итоге сделал как сделал, окей, исправлю

2020-11-25 00:06 UTC, kroveks commented on src/main/java/com/jm/online_store/service/impl/ProductServiceImpl.java
> +        return amount;
done

2020-11-25 00:06 UTC, kroveks commented on src/main/java/com/jm/online_store/service/impl/BasketServiceImpl.java
> +                throw new ProductsNotFoundException("products zakonchilis");
done

2020-11-25 00:09 UTC, kroveks commented on src/main/java/com/jm/online_store/service/impl/BasketServiceImpl.java
> +                   basket.setCount(basket.getCount() + 1);
Чтобы сделать с инкрементом надо basket.getCount() присвоить переменной и потом её инкрементировать, поэтому оставил как есть

2020-12-02 17:07 UTC, tediik approved these changes

2020-12-02 17:14 UTC, merged