DataProductInitilizer
tediik/online_store pull request #17
Opened 2020-08-18 11:38 UTC by DaveShedar

Product Initilizer as a method of DataInitilizer class.

2020-08-18 15:41 UTC, tediik requested changes

2020-08-18 15:41 UTC, tediik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +    @PostConstruct
По умолчанию оставляйте закоментированным, надо будет всем сказать, забываю...

2020-08-18 15:41 UTC, tediik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +    public DataInitializer(UserService userService, RoleService roleService, CategoriesService categoriesService) {
Так давай Ломбок тут тоже подключим и не будем ручками писать конструктор, у нас потом сюда еще парочка зависимостей подтянется в будущем

2020-08-18 15:41 UTC, tediik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +        product9.setDescriptions(Arrays.asList(description9));
Не могу объяснить, но меня тут что то смущает, тут точно нужно сетить Description к продукту через Arrays.asList??

2020-08-18 15:41 UTC, tediik commented on src/main/java/com/jm/online_store/model/Product.java
> +    private String producttype;
ужс.. camelCase где?

2020-08-19 12:42 UTC, DaveShedar commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +        product9.setDescriptions(Arrays.asList(description9));
Поскольку связь использовалась OneToMany, то в качестве параметров требовалось указывать List, но если подходить, что у одного продукта может быть только одно описание, то тогда использовал связь OneToOne, и в качестве параметра указывается соответствующее единственное описание.

2020-08-19 14:14 UTC, tediik requested changes
Поправь 2 маленьких замечания и реши конфликты

2020-08-19 14:14 UTC, tediik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +    @PostConstruct
@PostConstruct оставляем закомментированным

2020-08-19 14:14 UTC, tediik commented on src/main/java/com/jm/online_store/model/Product.java
> +    @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
@OneToOne по умолчанию EAGER - убирай

2020-08-20 21:17 UTC, tediik requested changes

2020-08-20 21:17 UTC, tediik commented on src/main/resources/application.properties
> +spring.url.activate=http://localhost:9999
обе строчки убрать, spring.server.url - вернуть!

2020-08-20 21:17 UTC, tediik commented on pom.xml
> +
Это как сюда попало, вроде же в твоей задаче ничего про АПИ VK не было?

2020-08-20 21:17 UTC, tediik commented on pom.xml
> +
для чего лишняя строчка? мы же не индусы ))

2020-08-20 21:17 UTC, tediik commented on src/main/java/com/jm/online_store/OnlineStoreApplication.java
> +
лишняя строчка

2020-08-20 21:17 UTC, tediik commented on src/main/java/com/jm/online_store/OnlineStoreApplication.java
> +
строчка?

2020-08-20 21:17 UTC, tediik commented on src/main/java/com/jm/online_store/OnlineStoreApplication.java
> +
и? )))

2020-08-20 21:17 UTC, tediik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +
Ну зачем? Лишняя строчка..

2020-08-22 18:25 UTC, tediik approved these changes

2020-08-22 18:25 UTC, merged