Категории продуктов на главной странице теперь реагируют на нажатия
tediik/online_store pull request #170
Opened 2020-11-23 09:20 UTC by Iambme

2020-11-23 11:41 UTC, Kirill1504 commented on src/main/java/com/jm/online_store/controller/rest/ProductRestController.java
> +}
Код-стайл! Почти везде 2 пробела вместо 4

2020-11-23 11:41 UTC, Kirill1504 commented on src/main/java/com/jm/online_store/controller/simple/ProductController.java
>  }
Код-стайл

2020-11-23 11:41 UTC, Kirill1504 commented on src/main/resources/application.yml
> +    password: BEtlF0G23780
Поставь себе пароль root. Как я понимаю, если это замерджить, то он поменяется у всех)

2020-11-23 16:38 UTC, tediik requested changes

2020-11-23 16:38 UTC, tediik commented on src/main/java/com/jm/online_store/repository/ProductRepository.java
> +    List<Product> getProductsByCategoryId(@Param("id")Long id);
без value, лишних пробелов внутри самого запроса не нужно, а вот пробел тут нужен:
@Param("id") Long id

2020-12-14 09:58 UTC, closed without merging

2020-12-14 09:58 UTC, Iambme commented
pull request не актуален