1) Добавил в ProductService новый метод isExist, реализовал его в Pro…
tediik/online_store pull request #171
Opened 2020-11-23 09:56 UTC by Kirill1504

…ductServiceImpl и добавил описание.

2) В ManagerProductsRestController, в методе, добавляющем новый товар, прописал логику для товара с таким же именем и пустым именем
3) Пофиксил баг с чекбоксом "Спрятать удаленные товары", теперь работает корректно
4) Сделал уведомление toastr для добавления товаров с незаполненными полями

2020-11-24 07:12 UTC, timRybin commented on src/main/java/com/jm/online_store/service/impl/ProductServiceImpl.java
> +    public boolean isExist(String productName) {
Можно реализовать средствами Jpa, будет попроще

2020-11-24 07:41 UTC, timRybin reviewed
После добавления/изменения/удаления продукта, чекбокс работает некорректно.  
Не знаю насколько относиться к поставленной задаче, но при изменении/удалении продукта не всегда отображается текущая категория. 
Надо ли тестировать загрузку данных из файла?

2020-11-24 07:41 UTC, timRybin commented on src/main/java/com/jm/online_store/service/impl/ProductServiceImpl.java
> +        return product.isPresent();
Можно сделать через репозиторий, будет попроще

2020-11-24 07:41 UTC, timRybin commented on src/main/java/com/jm/online_store/controller/rest/ManagerProductsRestController.java
> +        if (product.getProduct().equals("")) {
Можно сделать проверку на фронте

2020-11-24 07:41 UTC, timRybin commented on src/main/resources/static/js/products.js
> +        return false;
Они и по отдельности нормально отработают)

2020-11-24 07:41 UTC, timRybin commented on src/main/resources/static/js/products.js
> +        return false;
Тоже самое

2020-11-24 10:29 UTC, Kirill1504 commented on src/main/java/com/jm/online_store/service/impl/ProductServiceImpl.java
> +        return product.isPresent();
Не очень понял, что имеешь ввиду, я же и так сделал через репозиторий)

2020-11-24 10:32 UTC, Kirill1504 commented on src/main/resources/static/js/products.js
> +        return false;
Не работают, если все поля пустые, выдает уведомление только о том, что нужно заполнить стоимость

2020-11-24 10:35 UTC, Kirill1504 commented on src/main/java/com/jm/online_store/controller/rest/ManagerProductsRestController.java
> +        if (product.getProduct().equals("")) {
Да, верно, сделал проверку на пустое наименование на фронте

2020-11-24 10:37 UTC, Kirill1504 commented on src/main/resources/static/js/products.js
> +        return false;
> После добавления/изменения/удаления продукта, чекбокс работает некорректно.
> Не знаю, насколько относиться к поставленной задаче, но при изменении/удалении продукта не всегда отображается текущая категория.
> Надо ли тестировать загрузку данных из файла?

Как я понял, такова логика. Когда меняешь удаленный товар, он восстанавливается. В чем неккоректность работы при добавлении и удалении?

2020-11-24 10:37 UTC, Kirill1504 commented
> После добавления/изменения/удаления продукта, чекбокс работает некорректно.
> Не знаю, насколько относиться к поставленной задаче, но при изменении/удалении продукта не всегда отображается текущая категория.
> Надо ли тестировать загрузку данных из файла?

2020-11-24 10:39 UTC, Kirill1504 commented
> После добавления/изменения/удаления продукта, чекбокс работает некорректно.
> Не знаю, насколько относиться к поставленной задаче, но при изменении/удалении продукта не всегда отображается текущая категория.
> Надо ли тестировать загрузку данных из файла?

Как я понял, такова логика, что при изменении удаленного товара, он восстанавливается. В чем некорректность работы при удалении и добавлении товар? Не очень понял

2020-11-24 20:15 UTC, tediik requested changes

2020-11-24 20:15 UTC, tediik commented on src/main/resources/static/js/products.js
> +        return false;
этот и нижеследующий код грамотно переписать на switch
https://learn.javascript.ru/switch

2020-11-25 09:48 UTC, tediik requested changes

2020-11-25 09:48 UTC, tediik commented on src/main/resources/static/js/products.js
> +            toastr.error('Заполните поле наименования товара');
нет, не так :(

2020-11-26 12:52 UTC, tediik approved these changes

2020-11-26 12:52 UTC, merged