Role moderator
tediik/online_store pull request #174
Opened 2020-11-24 07:43 UTC by moshkovdenis

2020-11-24 08:32 UTC, timRybin commented
Функционал работает корректно. Замечаний по коду нет

2020-11-24 20:03 UTC, tediik requested changes

2020-11-24 20:03 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ModeratorRestController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
давай в общем стиле через фабричные методы статические

2020-11-24 20:03 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ModeratorRestController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
давай в общем стиле через фабричные методы статические

2020-11-24 20:03 UTC, tediik commented on src/main/java/com/jm/online_store/enums/ReportReason.java
> + * Перечисление причин жалобы.
не понятно жалобы на что

2020-11-24 20:03 UTC, tediik commented on src/main/java/com/jm/online_store/repository/ReportCommentRepository.java
> +
лишняя пустая строчка

2020-11-24 20:03 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/ReportCommentServiceImpl.java
> +}
Правильнее написать модифицирующий hql-запрос на удаление всех комментов с нужным ParentId и Id, а подвязанная сущность reportComment у тебя по идее по каскаду должна удалиться.

2020-11-25 09:55 UTC, tediik approved these changes
Точно убедился, что reportComment по каскаду удаляется?

2020-11-25 09:55 UTC, merged

2020-11-25 10:01 UTC, moshkovdenis commented
> Точно убедился, что reportComment по каскаду удаляется?

Да,проверил,все удаляется