Feature/section with product rating
tediik/online_store pull request #179
Opened 2020-11-28 20:34 UTC by Kirill1504

2020-11-30 13:18 UTC, MaximMyDev reviewed
1) Вопрос, а можно их объединить в 1 функцию, там кроме 1 строчки код идентичен. 
filterByCategoryInAscOrder
filterByCategoryInDescOrder
2) удали не используемые импорт в контроллерах

2020-11-30 16:58 UTC, tediik requested changes

2020-11-30 16:58 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/CategoriesServiceImpl.java
> +        return categoriesRepository.findAll().stream().filter(category -> category.getParentCategoryId() > 0).collect(Collectors.toList());
фильтровать стрим данных полученных из БД всегда плохо, особенно если он потенциально может быть большим, попробуй переписать на запрос сразу нужных данных из БД

2020-11-30 16:58 UTC, tediik commented on src/main/resources/templates/productsRating.html
> +                               style="background-color: white">
постарайся минимизировать использование инлайн стилей, тут фон можно задать с помощью стиля бутстрап

2020-12-01 16:25 UTC, tediik approved these changes

2020-12-01 16:25 UTC, merged