Merge remote-tracking branch 'origin/dev' into bugfix/favorite-new-customer
tediik/online_store pull request #190
Opened 2020-12-05 16:00 UTC by f4nke

2020-12-06 17:00 UTC, tediik requested changes

2020-12-06 17:00 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/AdminRestController.java
> +        userService.updateUser(customer);
а зачем это тут если ниже мы его апдейтим??

2020-12-07 11:10 UTC, f4nke commented on basic_module/src/main/java/com/jm/online_store/controller/rest/AdminRestController.java
> +        userService.updateUser(customer);
@tediik запушил исправление, убрал лишний апдейт

2020-12-07 11:47 UTC, tediik approved these changes

2020-12-07 11:47 UTC, merged