Merge branch 'dev' of https://github.com/tediik/online_store into feature/maintenanceMode
tediik/online_store pull request #192
Opened 2020-12-07 11:26 UTC by info-ilya

Добавил возможность из под администратора включать на сайте технические работы с возможностью выбора ролей, которым будет открыт доступ

2020-12-13 12:52 UTC, KuGa-Do reviewed
Вроде , все четко , работает , только не понял, только если выйдешь из профиля , то в него уже не зайти )) Но как я понял так и задумано

2020-12-13 15:02 UTC, info-ilya commented
> 
> 
> Вроде , все четко , работает , только не понял, только только если выйдешь из профиля , то в него уже не зайти )) Но как я понял так и задумано

Привет!) я забыл в карточке написать - доступ к странице http://localhost:9999/login остается всегда открыт, поэтому даже если выйти из админки при включенном режиме, можно всегда заново зайти

2020-12-13 17:14 UTC, tediik requested changes

2020-12-13 17:14 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/config/DataInitializer.java
> +     * Вызов методов добавлять в этодcommonSettingsInit метод.
что это? поправь

2020-12-13 17:14 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/config/filters/MaintenanceFilter.java
> +    public MaintenanceFilter(CommonSettingsRepository commonSettingsRepository) {
используй LomBok

2020-12-13 17:14 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/config/security/SecurityConfig.java
> +import javax.servlet.annotation.WebFilter;
а зачем нам эти импорты тут?

2020-12-13 17:14 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/CommonSettingsRestController.java
> +     * in current class and return ResponseEntity with not found status/
??

2020-12-13 17:14 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/repository/CommonSettingsRepository.java
> +    int updateTextValue(@Param("textValue") String textValue, @Param("status") boolean status, @Param("settingName") String settingName);
ты точно уверен, что тем методом никто нигде не пользовался?

2020-12-13 17:14 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/CommonSettingsServiceImpl.java
> +       if(commonSettingsRepository.updateTextValue(settings.getTextValue(), settings.isStatus(),settings.getSettingName()) != 1){
во первых кодстайл, во вторых, опять же, ты уверен, что той старой версией этого метода точно никто не пользовался, потому что если ДА, то я уверен, старый чей то функционал просто сломается

2020-12-13 17:14 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/interf/CommonSettingsService.java
> +
импорт вижу, использования его не вижу

2020-12-13 17:14 UTC, tediik commented on basic_module/src/main/resources/templates/maintenanceMode.html
> +        display: inline-block;
приехали ))) выноси стили в отдельный css-файл

2020-12-13 20:39 UTC, info-ilya commented on basic_module/src/main/java/com/jm/online_store/repository/CommonSettingsRepository.java
> +    int updateTextValue(@Param("textValue") String textValue, @Param("status") boolean status, @Param("settingName") String settingName);
Привет! Этот метод используется в CommonSettingsServiceImpl для того, чтобы изменить шаблон рассылки в кабинете менеджера (Кабинет менеджера - Настройки - E-mail рассылка и Снижение цен). Перед тем, как пушить, я проверял работу измененного метода - если отредактировать шаблон рассылки, то в базу все изменения записывают без ошибок. Могу вернуть старый код и напосить отдельный метод, чтобы точно проблем не возникло.

2020-12-13 20:42 UTC, info-ilya commented on basic_module/src/main/java/com/jm/online_store/service/impl/CommonSettingsServiceImpl.java
> +       if(commonSettingsRepository.updateTextValue(settings.getTextValue(), settings.isStatus(),settings.getSettingName()) != 1){
Кодстайл поправил. Тут получается почему ничего не ломается, потому что я добавил settings.isStatus() - это проверка нового булевого поля, которое в БД всегда по умолчанию false, поэтому ни одной ошибки там, где он используется, я не нашел. Если так будет лучше и безопаснее, тогда давай я лучше напишу еще один метод, а этот оставлю с изначальным кодом.

2020-12-14 11:22 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/repository/CommonSettingsRepository.java
> +    int updateTextValue(@Param("textValue") String textValue, @Param("status") boolean status, @Param("settingName") String settingName);
Если проблем не возникло, зачем тогда возвращать старый код?

2020-12-14 11:22 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/CommonSettingsServiceImpl.java
> +       if(commonSettingsRepository.updateTextValue(settings.getTextValue(), settings.isStatus(),settings.getSettingName()) != 1){
а вообще да, напиши новый

2020-12-14 17:57 UTC, tediik approved these changes

2020-12-14 17:57 UTC, merged