Добавлена страница корзины
tediik/online_store pull request #193
Opened 2020-12-08 02:29 UTC by kroveks

Добавлена страница корзины, редирект на страницу корзины из кабинета пользователя и возможность вернуться в кабинет пользователя из корзины.

2020-12-08 10:26 UTC, DenisMalikovKzn reviewed
ок только вот кнопки увеличения и уменьшения количества товара  в корзине разные по размерам

2020-12-08 11:39 UTC, tediik requested changes

2020-12-08 11:39 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +     */
ну настолько детально не надо, убери этот javaDoc

2020-12-08 11:39 UTC, tediik commented on basic_module/src/main/resources/templates/basketPage.html
> +    <script src="../static/js/busket.js"></script>
пока я вижу просто ctrl +c / ctrl + v бездумное, уверен половина css и js для твоей страницы просто не нужна, зачем тогда ее тащить?

2020-12-08 11:39 UTC, tediik commented on basic_module/src/main/resources/templates/basketPage.html
> +</html>
проверь заодно и тут, что точно нужны все подключенные js

2020-12-08 11:54 UTC, kroveks commented on basic_module/src/main/resources/templates/basketPage.html
> +    <script src="../static/js/busket.js"></script>
Да, я там просто скопипастил,  разбирался не скриптах в основном, на bootstrap чет подзабил, сегодня исправлю

2020-12-09 17:48 UTC, tediik approved these changes

2020-12-09 17:49 UTC, merged