Feature/comment filter
tediik/online_store pull request #196
Opened 2020-12-10 07:50 UTC by MaximMyDev

Добавил фильтр стоп-слов для комментариев. 
- Полный список всех слов с полным crud управлением
- Стоп-слово статус ACTIVE, DEACTIVATED может содержаться в базе, но при DEACTIVATED по нему не будет фильтроваться.
- Добавил общий рубильник, включающий и отключающий фильтрацию. Параметр хранится в базе таблице common_settings, параметр bad_words_enabled.
- Добавил возможность импорта слов в окне импорта. Слова через запятую.
- Все операции через rest без перезагрузки страницы.

2020-12-10 08:05 UTC, KuGa-Do reviewed
Код просмотрел , замечаний нет .

2020-12-10 10:30 UTC, DenisMalikovKzn reviewed
ок

2020-12-10 11:15 UTC, tediik requested changes

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/config/DataInitializer.java
> +    }
погоди, но договорились же, что ты сделаешь в инициализаторе считывание из файла списка стоп-слов

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +     * @return
не заполнено

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +    CommonSettingsService commonSettingsService;
private final?

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +     * @return
не заполнено

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +     * @return
не заполнено

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +            log.debug("EmptyBadWord");
это не вижу смысла логировать

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +     * @return
тут и далее во всем файле, пробегись по JavaDoc - заполни как положено

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +    }
сделай метод, который помечается аннотацией @ ExeptionHandler - это будет единый метод, который будет перехватывать исключения определенного типа и возвращать нужный ответ, соответственно во всех методах тут убери блоки try / catch

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +        }
у нас для этого есть true / false и специальный тип данных

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/model/BadWords.java
> +    private BadWordStatus status;
почему было не сделать поле типа boolean и назвать например isEnabled и подставлять - true / false? Это самый верный вариант для двухвариантных предметов, тем более для состояния включено / выключено

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/enums/BadWordStatus.java
> +}
вероятно оно нам не надо, переделай поле на boolean

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/model/dto/BadWordsDto.java
> +}
почему понадобилась DTO если по сути мы передаем и принимаем ровно такие же поля что и в модели???

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/BadWordsServiceImpl.java
> +        return convertBadWordsToBadWordsDTO(badWordsRepository.findById(id).get());
вероятно это не понадобится

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/BadWordsServiceImpl.java
> +    }
вероятно будет не нужен

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +            log.debug("EmptyBadWord");
это можно не логировать

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +
это вообще по сути бизнес-логика, чего она у нас в контроллере делает?

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +            System.out.println(textToSave);
это точно убрать

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/resources/static/js/comments.js
> +                console.log('getFilter=' + getFilter)
?

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/resources/static/js/badWords.js
> +    }*/
возможно стоит убрать ненужный код?

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/resources/static/js/comments.js
> +                            //let tag = 'span'; textCheck = textCheck.replace(re, '<'+ tag +' class="text-danger">$&</'+ tag +'>');
не нужно

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/resources/static/js/comments.js
> +    }
я думаю архитектурно не очень правильно, потому что хранить список слов на клиенте - не очень хорошая идея, тем более там слова такие, что вслух не произносят, комментарий отправляется штатно на сервер и там уже идет проверка и формируется нужный ответ - или просто ОК, и тогда комментарий мы отображаем на странице, либо не ОК и описание какое слово в комментарии не прошло модерацию, короче переносим функционал на бэк

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/resources/templates/manager_settings.html
> +                       aria-controls="nav-categories-and-topics" aria-selected="false">Запрещенные слова</a>
У АДМИНА

2020-12-10 11:15 UTC, tediik commented on basic_module/src/main/resources/templates/manager_settings.html
> +<script src="/static/js/badWords.js"></script>  <!--!!!!!!!!!!!!!!!!!!!!!!!-->
зачем  <!--!!!!!!!!!!!!!!!!!!!!!!!--> ???

2020-12-10 11:20 UTC, MaximMyDev commented on basic_module/src/main/java/com/jm/online_store/config/DataInitializer.java
> +    }
Я в кабинете сделал окно массового импорта. Считаю, что это удобнее сделать из интерфейса, чем возится с файлами. Просто вставил и нажал кнопку.

2020-12-10 11:20 UTC, MaximMyDev commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +     * @return
Блин я просто метод один переименовал, и идея мне снесла все комменты. Ок исправлю.

2020-12-10 11:22 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/config/DataInitializer.java
> +    }
Тогда приложи файл со списком слов в проект, чтобы он у нас был под рукой

2020-12-10 11:22 UTC, MaximMyDev commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +            log.debug("EmptyBadWord");
понял уберу

2020-12-10 11:23 UTC, MaximMyDev commented on basic_module/src/main/java/com/jm/online_store/model/dto/BadWordsDto.java
> +}
я его делал для одного метода, а потом переделал по другому и забыл убрать.  переделаю

2020-12-10 11:24 UTC, MaximMyDev commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +
Засуну в сервис.

2020-12-14 12:31 UTC, tediik requested changes
и файл badword for import.txt
переименуй, чтобы не было пробелов в имени, это может быть источником проблем

2020-12-14 12:31 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +     * @return
не заполено

2020-12-14 12:31 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +     * @return
не заполено

2020-12-14 12:31 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +     * @return
не заполено

2020-12-14 12:31 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +     * @return
не сделано

2020-12-14 12:31 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/BadWordsServiceImpl.java
> +        System.out.println("allActiveBW=" + allActiveBW.toString());
убирай

2020-12-14 12:31 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/BadWordsServiceImpl.java
> +     * @return
нигде ни в одном твоем JavaDoc я не увидел правильно заполненного поля @return
и чаще всего и @param

2020-12-14 12:31 UTC, tediik commented on basic_module/src/main/resources/static/js/reviews.js
> +                                    success: function (response) {
опять плохой вариант, зачем мне еще раз пересылать данные, которые итак уже на сервере? Он что не может их проверить там у себя и сразу опубликовать пост, если все ОК и вернуть нам в ответ 200 и вернуть НЕОК, если что-то пошло не так?

2020-12-14 12:31 UTC, tediik commented on basic_module/src/main/resources/static/js/comments.js
> +                                        $('#showComments').append($(`
уже отписал по поводу архитектуры - надо переделать

2020-12-14 12:31 UTC, tediik commented on basic_module/src/main/resources/static/js/comments.js
> +                                }
я вижу очень похожий код (я не вникал особо) уже третий раз - там точно нельзя никак написать 1 функцию?

2020-12-14 12:31 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/BadWordsServiceImpl.java
> +        System.out.println("allActiveBW=" + allActiveBW.toString());
это убирай
System.out.println("allActiveBW=" + allActiveBW.toString());

2020-12-14 12:50 UTC, MaximMyDev commented on basic_module/src/main/java/com/jm/online_store/service/impl/BadWordsServiceImpl.java
> +        System.out.println("allActiveBW=" + allActiveBW.toString());
Я не понимаю что в JavaDoc надо заполнить. Я смотрел не созвоне, ты вроде так показывал сделать. Другие файлы смотрел, там примерно так заполнено. Короче не понимаю что не хватает.

2020-12-14 12:52 UTC, MaximMyDev commented on basic_module/src/main/resources/static/js/reviews.js
> +                                    success: function (response) {
Ну я старался как можно меньше правок вносить в работающий код. Сейчас мой код как бы отдельно идет от комментариев. Переделаю.

2020-12-14 12:54 UTC, MaximMyDev commented on basic_module/src/main/resources/static/js/comments.js
> +                                }
Код одинаковый был до меня. Один кусок для ответа на комментарий, второй для комментариев. Я его просто обернул своим условием.

2020-12-16 07:58 UTC, MaximMyDev commented
- Добавил в javadoc возврат и параметры где не было.
- убрал большие правки в (вернул старые файл) в commit, review  внеся на значительные изменения 
- убрал лишние запросы
- часть функционала перенес в контролеры комментов и ревью

2020-12-16 13:23 UTC, tediik requested changes

2020-12-16 13:23 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +     * @param saveSetting
поправь ошибки..
Что я имею ввиду, когда говорю, что твой JavaDoc плох.
* Сохраняет в CommonSettings парамаетр bad_words_enabled (true, false)
*
* @param saveSetting - вот тут надо не просто обозначить имя параметра, а дать описание, что это за параметр, да, так принято.

Тут вообще не очень понятно из имени параметра, что это, имя isEnabled например смотрелось бы куда понятнее

2020-12-16 13:23 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +        }
код дублируется, нельзя ли все же вынести общую часть до if и оставшуюся после? Нарушаешь DRY

2020-12-16 13:23 UTC, tediik commented on basic_module/src/main/resources/static/js/badWords.js
> +                    </td>
очень длинные строки, сделай аккуратно перенос строк, тем более что шаблонные строки позволяют делать это легко

2020-12-16 13:23 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/BadWordsServiceImpl.java
> +        return foundWords;
напиши тест к этому методу и javaDoc

2020-12-16 13:23 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/BadWordsServiceImpl.java
> +     * @return
Не исправлено же, что именно возвращает метод то? в описании написал, а у параметра @return НЕ написал! Параметр @param words тоже не обозначил что это и так везде.

2020-12-16 13:23 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/BadWordsServiceImpl.java
> +    }
напиши тест на этот метод тоже

2020-12-16 13:23 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/BadWordsServiceImpl.java
> +    }
в методе есть логика, а не просто вызов метода репозитория, назначение которого понятно из названия, соответственно пиши JavaDoc

2020-12-16 13:23 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/BadWordsServiceImpl.java
> +
описание к классу тоже напиши

2020-12-16 13:23 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/ReviewRestController.java
> +            CommonSettings templateBody = commonSettingsService.getSettingByName("bad_words_enabled");
мне показалось или ты нигде не используешь эту переменную??

2020-12-16 13:23 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/ReviewRestController.java
> +     * @return ResponseEntity<List < CommentDto>>
было нормально до твоего изменения

2020-12-16 13:23 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/ReviewRestController.java
> +     * @return ResponseEntity<List < ReviewDto>>
было нормально до твоего изменения

2020-12-16 13:23 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/ReviewRestController.java
> +    }
JavaDoc

2020-12-16 13:23 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +    }
честно говоря не вижу проблемы тут в коде вместо
List<String> resultText = checkText(checkText);
писать сразу 
List<String> resultText = badWordsService.checkComment(checkText);
Никакого профита от такого приватного метода нет

2020-12-16 13:23 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +    }
JavaDoc и + код дублируется, я бы вынес это в badWordsService и запрашивал бы оттуда, потому что у тебя и в ReviewRestController такой же точно метод, тогда стоит вынести в 1 место.

2020-12-16 16:56 UTC, MaximMyDev commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +     * @param saveSetting
Я не понимаю я смотрю те jd что есть в проекте и там все так же как у меня, вот первые пару примеров:
/**
     * rest mapping to modify user from admin page
     *
     * @param user {@link User}
     * @return new ResponseEntity<>(HttpStatus) {@link ResponseEntity}
     */
    @PutMapping
    public ResponseEntity editUser(@RequestBody User user) {

-------
* @param authentication
     * @return
     */
    @GetMapping("/getCurrent")
    public ResponseEntity<UserDto> getCurrentUser(Authentication authentication) {

-------
 * Метод для получение текущего статуса фильтра (true, false)
     * Возвращает ResponseEntity<CommonSettings>
     *
     * @return ResponseEntity<CommonSettings>
     */
    @GetMapping(value = "/status")
    public ResponseEntity<CommonSettings> getSetting() {
---------------------------------- 
В чем разница??? Или я не понимаю или ко мне придираются на ровном месте?

2020-12-16 17:01 UTC, MaximMyDev commented on basic_module/src/main/resources/static/js/badWords.js
> +                    </td>
Можно, взял этот код из имеющегося в проекте, products.js:
<button data-product-id="${product.id}" type="button" class="btn btn-success edit-button" data toggle="modal" data-target="#productModalWindow">Edit</button>
<button data-product-id="${product.id}" type="button" id="action-button-${product.id}" class="btn action" data-target="#productModalWindow">Delete</button>
------------------- от туда скопировано почему там пропустили, мой завернули?

2020-12-20 13:41 UTC, tediik requested changes

2020-12-20 13:41 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +            commonSettingsService.updateTextValue(setNo);
переписать как договаривались

2020-12-20 14:12 UTC, tediik approved these changes

2020-12-20 14:13 UTC, merged