Feature/comments crud
tediik/online_store pull request #198
Opened 2020-12-11 15:53 UTC by kossme

добавлена функция изменения и удаления своих комментариев, а также сортировка комментариев по новизне.

При удалении комментария, у которого остались ответы. он помечается как удаленный, но ответы остаются. 
В БД comments новый столбец deleted с boolean.

Функция "пожаловаться" интегрирована.

Исправлены ошибки

2020-12-11 17:43 UTC, KuGa-Do reviewed
Функционал проверил , все как заявлено в сообщении пулреквеста, работает .
По код стайлу ,я откомментил  в каком месте ,  несколько пустых строк , скорей всего, я честно говоря не супер мастер код стайла, особенно по js  , но Эдуард скорей всего тебе об этом скажет , так что смотри сам исправлять тебе это или нет, еще там были места , где больше двух пустых строк , по идее это не очень хорошо .

2020-12-11 17:43 UTC, KuGa-Do commented on basic_module/src/main/resources/static/js/comments.js
> -        $('#commentForm').on('submit', function (event) {
По идее Эдуард скажет удалить эту кучу пустых строк , но я не уверен ))) так что смотри сам

2020-12-12 10:08 UTC, kossme commented on basic_module/src/main/resources/static/js/comments.js
> -        $('#commentForm').on('submit', function (event) {
Исправил

2020-12-12 20:44 UTC, tediik requested changes

2020-12-12 20:44 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +            System.out.println(user);
это точно убрать

2020-12-12 20:44 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +                throw new RuntimeException();
неверно использовать бросание exeption для построения логики приложения

2020-12-12 20:44 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +            User user = userService.findByEmail(email).orElse(new User());
т.е. если мы не нашли пользователя, то просто создаем нового, а потом ниже пытаемся взять у него id?
Предлагаю пересмотреть логику этого метода

2020-12-12 20:44 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +        }
смотреть замечания выше - переделать

2020-12-12 20:44 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/model/Comment.java
> +
да, но мы ведь можем определять если ли kids просто запрашивая поле reportComments и если Лист пустой, то и kids нету, разве нет? Зачем нам тогда еще одно поле в БД?

2020-12-12 20:44 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/CommentServiceImpl.java
> +     */
оформить JavaDoc как положено

2020-12-12 20:44 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/CommentServiceImpl.java
> +     */
оформить JavaDoc как положено

2020-12-12 20:44 UTC, tediik commented on basic_module/src/main/resources/static/js/productPage.js
> +                toastr.success("Товар успешно удалён из избранного");
почему дублирование строк?

2020-12-12 20:44 UTC, tediik commented on basic_module/src/main/resources/static/js/comments.js
> +            if (commentData.deletedHaveKids) {
Причем чтобы не сломать логику в js, ты можешь добавить это булево поле в DTO, которое у тебя будет иметь значение в зависимости от того пустой ли список о котором я писал ранее

2020-12-14 10:37 UTC, kossme commented on basic_module/src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +            System.out.println(user);
System.out.println(user);
Вот это? удалил

2020-12-14 11:33 UTC, kossme commented on basic_module/src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +                throw new RuntimeException();
Переделал

2020-12-14 11:33 UTC, kossme commented on basic_module/src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +                throw new RuntimeException();
@DeleteMapping("/{commentId}")
    public ResponseEntity<?> deleteCommentById(@PathVariable Long commentId) {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        String email = auth.getName();
        if (userService.findByEmail(email).isPresent()) {
            User user = userService.findByEmail(email).get();
            if (commentService.findById(commentId).getCustomer().getId().equals(user.getId())) {
                commentService.removeById(commentId);
                return new ResponseEntity<>(HttpStatus.OK);
            }
        }
        return new ResponseEntity<>(HttpStatus.NOT_MODIFIED);
    }

2020-12-14 11:35 UTC, kossme commented on basic_module/src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +            User user = userService.findByEmail(email).orElse(new User());
В этом исполнении это неважно, т.к. кидалось бы исключение в любом случае при сравнении. Но согласен, что это коряво. Переделал

2020-12-14 11:37 UTC, kossme commented on basic_module/src/main/resources/static/js/productPage.js
> +                toastr.success("Товар успешно удалён из избранного");
Какой-то косяк, удалю

2020-12-14 17:53 UTC, tediik requested changes

2020-12-14 17:53 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +                return new ResponseEntity<>(HttpStatus.OK);
не очень красивая работа с Optional, он намного интереснее чем ты думаешь, попробуй использовать метод ifPresent()

2020-12-14 17:53 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +            if (commentService.findById(commentId).getCustomer().getId().equals(user.getId())) {
попробуй использовать метод ifPresent()

2020-12-17 14:54 UTC, tediik approved these changes

2020-12-17 16:13 UTC, merged