bugfix/stockImages
tediik/online_store pull request #200
Opened 2020-12-13 14:17 UTC by f4nke

исправил пункты в таске

2020-12-16 15:13 UTC, f4nke commented
![](https://github.trello.services/images/mini-trello-icon.png) [Акции - баги](https://trello.com/c/brEvQVYp/235-%D0%B0%D0%BA%D1%86%D0%B8%D0%B8-%D0%B1%D0%B0%D0%B3%D0%B8)

2020-12-16 18:41 UTC, tediik requested changes
@f4nke запилить отдельный контроллер и сервис для загрузки файлов - в принципе неплохая идея, но как быть с загрузкой картинки для профиля? Картинки в новостях (их вроде пока нет, но будут)?? Ты предлагаешь поддерживать несколько разных реализаций одного и того же функционала??? Это очень плохая идея. Либо ты делаешь по аналогии с уже написанным для установки картинки того же профиля и тогда убираешь свой сервис и контроллер, либо ты доводишь до ума свой контроллер и сервис - а именно делаешь его универсальным, потому что имя которые ты ему сейчас дал, намекает на универсальность как раз, иначе в твоей реализации он должен называться - ImageForStockUploadServiceImpl и никак иначе. Универсальность подразумевает, что он сможет сохранять картинки по любому указанному пути, для любого кейса - будь то картинка профиля, картинка акции или новости и т.д. Путь сложный в принципе я считаю, но выполнимый и не забудь при этом уже существующий функционал переписать на использование твоего универсального кода.

2020-12-17 15:01 UTC, tediik requested changes

2020-12-17 15:01 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/interf/FileService.java
> +}
а он где то используется? или я просто не увидел?

2020-12-17 15:08 UTC, f4nke commented on basic_module/src/main/java/com/jm/online_store/service/interf/FileService.java
> +}
@tediik  Удалить забыл, видимо. Сейчас доделаю через несколько минут, пока не дома

2020-12-17 15:47 UTC, tediik approved these changes

2020-12-17 15:50 UTC, merged