Redirect task
tediik/online_store pull request #202
Opened 2020-12-16 12:36 UTC by kroveks

Redirect to previous page after authorization

2020-12-16 12:40 UTC, tediik commented
![](https://github.trello.services/images/mini-trello-icon.png) [После входа под покупателем не перекидывать на главную - перенаправлять на ту страницу, где пользователь был до этого](https://trello.com/c/01ihOS1m/216-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D0%B2%D1%85%D0%BE%D0%B4%D0%B0-%D0%BF%D0%BE%D0%B4-%D0%BF%D0%BE%D0%BA%D1%83%D0%BF%D0%B0%D1%82%D0%B5%D0%BB%D0%B5%D0%BC-%D0%BD%D0%B5-%D0%BF%D0%B5%D1%80%D0%B5%D0%BA%D0%B8%D0%B4%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%BD%D0%B0-%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D1%83%D1%8E-%D0%BF%D0%B5%D1%80%D0%B5%D0%BD%D0%B0%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D1%82%D1%8C-%D0%BD%D0%B0-%D1%82%D1%83-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%83-%D0%B3%D0%B4%D0%B5-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C-%D0%B1%D1%8B%D0%BB-%D0%B4%D0%BE-%D1%8D%D1%82%D0%BE%D0%B3%D0%BE)

2020-12-16 12:40 UTC, tediik commented
![](https://github.trello.services/images/mini-trello-icon.png) [После входа под покупателем не перекидывать на главную - перенаправлять на ту страницу, где пользователь был до этого](https://trello.com/c/01ihOS1m/216-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D0%B2%D1%85%D0%BE%D0%B4%D0%B0-%D0%BF%D0%BE%D0%B4-%D0%BF%D0%BE%D0%BA%D1%83%D0%BF%D0%B0%D1%82%D0%B5%D0%BB%D0%B5%D0%BC-%D0%BD%D0%B5-%D0%BF%D0%B5%D1%80%D0%B5%D0%BA%D0%B8%D0%B4%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%BD%D0%B0-%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D1%83%D1%8E-%D0%BF%D0%B5%D1%80%D0%B5%D0%BD%D0%B0%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D1%82%D1%8C-%D0%BD%D0%B0-%D1%82%D1%83-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%83-%D0%B3%D0%B4%D0%B5-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C-%D0%B1%D1%8B%D0%BB-%D0%B4%D0%BE-%D1%8D%D1%82%D0%BE%D0%B3%D0%BE)

2020-12-16 18:30 UTC, tediik requested changes

2020-12-16 18:30 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/model/CurrentUrl.java
> +    private static String Url;
имена переменных со строчной буквы, дальше вместо сеттера геттера напиши уж аннотации, раз мы ломбок используем

2020-12-16 18:30 UTC, tediik commented on basic_module/src/main/resources/templates/mainPage.html
> +<script src="../static/js/rememberCurrentUrl.js"></script>
а зачем сюда, ты же вроде зацепил в заголовке, не? или у нас для mainPage другой заголовок?

2020-12-16 19:14 UTC, kroveks commented on basic_module/src/main/resources/templates/mainPage.html
> +<script src="../static/js/rememberCurrentUrl.js"></script>
Это я забыл потереть, пока пилил для перестраховки и туда и сюда подтягивал

2020-12-16 19:14 UTC, kroveks commented on basic_module/src/main/java/com/jm/online_store/model/CurrentUrl.java
> +    private static String Url;
Принял, исправлю

2020-12-17 03:45 UTC, kroveks commented on basic_module/src/main/java/com/jm/online_store/model/CurrentUrl.java
> +    private static String Url;
А дальше - у меня статическая переменная, тут без ломбока, ручками надо, поэтому оставил как есть

2020-12-17 11:44 UTC, tediik approved these changes

2020-12-17 11:44 UTC, merged