Feature/refactor/products characteristics
tediik/online_store pull request #204
Opened 2020-12-18 15:17 UTC by Kirill1504

2020-12-19 12:14 UTC, DenisMalikovKzn reviewed
ок

2020-12-19 19:47 UTC, tediik requested changes

2020-12-19 19:47 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/controller/rest/ManagerCharacteristicsRestController.java
> +        List<Characteristic> list = characteristicService.findAll();
зачем переменная list?

2020-12-19 19:47 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/model/Categories.java
> +    private List<Characteristic> characteristics;
это большой объем данных, его следует грузить только тогда, когда он нам реально нужен, так что убирай EAGER и выкручивайся с LAZY

2020-12-19 19:47 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/model/Characteristic.java
> +@AllArgsConstructor
точно нельзя было хотя бы часть заменить на @Data??

2020-12-19 19:47 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/CharacteristicServiceImpl.java
> +     * @param characteristic пользователь, полученный из контроллера.
пользователь??

2020-12-19 19:47 UTC, tediik commented on basic_module/src/main/java/com/jm/online_store/service/impl/ProductCharacteristicServiceImpl.java
> +
Давай JavaDoc

2020-12-19 19:47 UTC, tediik commented on basic_module/src/main/resources/static/js/products.js
> +//Метод для попробовать, убрать
эмммм??? ))

2020-12-19 19:47 UTC, tediik commented on uploads/import/products.xml
> +        <characteristicid>4,5,7</characteristicid>
т.е. получается чтобы импортить из файла, нам надо по идее знать какой в БД id у нужной категории? Хм... интересно, есть ли решение лучше..

2020-12-19 21:14 UTC, Kirill1504 commented on uploads/import/products.xml
> +        <characteristicid>4,5,7</characteristicid>
По ид категории не я делал))
Я переделал добавление по имени категории и имени харакетристики

2020-12-19 21:16 UTC, Kirill1504 commented on basic_module/src/main/java/com/jm/online_store/model/Characteristic.java
> +@AllArgsConstructor
Знаю, что data заменяет @RequiredArgsConstructor, но без него и с датой не компилится(
Добавил дату, убрал @Getter и @Setter

2020-12-20 12:35 UTC, tediik submitted a review, later dismissed
Я не увидел, чтобы ты внес изменения в репозитории после того как поменял EAGER на LAZY - завтра на созвоне покажешь, что точно все работает у тебя в таске.

2020-12-20 16:10 UTC, tediik approved these changes
Посмотрим завтра на созвоне еще

2020-12-21 15:53 UTC, tediik approved these changes

2020-12-21 15:53 UTC, merged