Добавил навигацию у Admin на главную страницу
tediik/online_store pull request #213
Opened 2020-12-25 15:21 UTC by Cotharsis

Добавил навигацию у Admin на главную страницу

2020-12-28 15:33 UTC, tediik requested changes

2020-12-28 15:33 UTC, tediik commented on src/main/resources/templates/blocks/header.html
> +           href="/">Главная</a>
Давай сделаем по другому, пусть на главную кидает щелчок по названию магазина в навбаре и это должно рабоатть для всех пользователей вообще

2020-12-29 02:36 UTC, Cotharsis commented on src/main/resources/templates/blocks/header.html
> +           href="/">Главная</a>
Поправил

2020-12-29 07:48 UTC, tediik approved these changes

2020-12-29 07:48 UTC, merged