Merge remote-tracking branch 'origin/dev' into feature/fioOnFeedBack
tediik/online_store pull request #215
Opened 2020-12-27 17:19 UTC by DenisMalikovKzn

2020-12-27 17:22 UTC, DenisMalikovKzn commented
![](https://github.trello.services/images/mini-trello-icon.png) [Обратная связь](https://trello.com/c/kO3JOvxH/239-%D0%BE%D0%B1%D1%80%D0%B0%D1%82%D0%BD%D0%B0%D1%8F-%D1%81%D0%B2%D1%8F%D0%B7%D1%8C)

2020-12-28 16:49 UTC, softozhik commented
замечания такие:
1. managerFeedback.js: переменная _managersId_ как я понял используется внутри только одного метода, объявить ее там, а то область видимости слишком большая
2. customer-feedback-form.js: можно формат даты в "Дата и время ответа" сделать таким же, как выше, где "дата обращения"?
3. не принципиально, но может быть в полях, где нет значений выводить не "null", а оставлять пустыми?
4. ну и console.log() убрать или закомментировать

2020-12-29 07:47 UTC, tediik requested changes

2020-12-29 07:47 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FeedbackRestController.java
> +import org.springframework.security.core.userdetails.UserDetails;
проверь импорты в классе, у меня ощущение, что ты их нигде не используешь и они лишние

2020-12-29 07:47 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FeedbackRestController.java
> +     */
разметку и описание для swagger - смотри образцы в других контроллерах

2020-12-29 07:47 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FeedbackRestController.java
> +     */
+ разметку и описание для swagger - смотри образцы в других контроллерах

2020-12-29 07:47 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/FeedbackServiceImpl.java
> +import org.springframework.security.core.userdetails.UserDetails;
проверь все импорты, наверняка есть лишние

2020-12-29 07:47 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +     */
перепиши на русском

2020-12-29 07:47 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +    }
тут добавь JavaDoc

2020-12-29 07:54 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/controller/rest/FeedbackRestController.java
> +import org.springframework.security.core.userdetails.UserDetails;
ок

2020-12-29 20:31 UTC, tediik requested changes
Имей ввиду, что я тоже человек и мог где-то ошибиться с замечанием, значит нужно мне как твоему временному руководителю указать и доказать, в чем я мог быть не прав.

2020-12-29 20:31 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FeedbackRestController.java
> +     */
по сути описание неверное - он возвращает у тебя именно текущего залогиненного пользователя, причем у нас уж есть в приложении такой функционал - поищи и вызывай оттуда, новый метод совершенно не стоило писать, если сам не найдешь - попроси помощи у ребят

2020-12-29 20:31 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FeedbackRestController.java
> +            return new ResponseEntity<>(HttpStatus.NO_CONTENT);
смотри.. логика такая, у тебя в методе, в его реализации нигде конкретно не задается, что этот искомый юзер - именно менеджер! Т.е. если я передам id пользователя админа, то мне и выдаст админа, что это значит? Это значит, что этот метод занимается выдачей юзера (неважно какой роли) по его id, а значит место ему в классе с более общим назначением, поищи, у нас наверняка уже есть какой-нибудь UserRestController или что-то в этом духе, так вот, лучше перенести этот метод туда

2020-12-29 20:31 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/FeedbackServiceImpl.java
> +import org.springframework.security.core.userdetails.UserDetails;
Еще раз - проверь все импорты, наверняка есть лишние!

2020-12-29 21:57 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/controller/rest/FeedbackRestController.java
> +            return new ResponseEntity<>(HttpStatus.NO_CONTENT);
точно

2020-12-29 22:39 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/controller/rest/FeedbackRestController.java
> +     */
исправил

2020-12-29 22:39 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/controller/rest/FeedbackRestController.java
> +            return new ResponseEntity<>(HttpStatus.NO_CONTENT);
переместил

2020-12-29 23:24 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/controller/rest/FeedbackRestController.java
> +            return new ResponseEntity<>(HttpStatus.NO_CONTENT);
попробовал переместить этот метод в UserRestController и вот что в консоле браузера после перехода по ссылки   
![image](https://user-images.githubusercontent.com/75420078/103320372-24c52c80-4a46-11eb-8285-4e7df67aff4c.png)
403
> ERROR CODE: "HTTP 403 Forbidden"

> ERROR DESCRIPTION: "Access Denied. You Do Not Have The Permission To Access This Page On This Server"

> ERROR POSSIBLY CAUSED BY: [execute access forbidden, read access forbidden, write access forbidden, ssl required, ssl 128 required, ip address rejected, client certificate required, site access denied, too many users, invalid configuration, password change, mapper denied access, client certificate revoked, directory listing denied, client access licenses exceeded, client certificate is untrusted or invalid, client certificate has expired or is not yet valid, passport logon failed, source access denied, infinite depth is denied, too many requests from the same client ip...]

> SOME PAGES ON THIS SERVER THAT YOU DO HAVE PERMISSION TO ACCESS: [ MAIN PAGE or LOGOUT ... ]

> HAVE A NICE DAY, STRANGER :-)

2020-12-29 23:25 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/controller/rest/FeedbackRestController.java
> +            return new ResponseEntity<>(HttpStatus.NO_CONTENT);
то есть он не дает

2020-12-29 23:26 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/controller/rest/FeedbackRestController.java
> +            return new ResponseEntity<>(HttpStatus.NO_CONTENT);
а вернул обратно все заработало снова

2020-12-31 11:21 UTC, tediik approved these changes

2020-12-31 11:22 UTC, merged