плохие слова подгружаются из файла, используются системные разделители
tediik/online_store pull request #216
Opened 2020-12-27 17:26 UTC by softozhik

если файл не найден, оставлен стартовый набор
для импорта только их можно поставить перед методом аннотацию @PostConstruct (хотя, это и так понятно, но на вс.пож.)

2020-12-27 17:27 UTC, softozhik commented
![](https://github.trello.services/images/mini-trello-icon.png) [Хочу чтобы плохие слова из приложенного файла bad_words импортировались в Иницилайзере](https://trello.com/c/aicJjtuv/252-%D1%85%D0%BE%D1%87%D1%83-%D1%87%D1%82%D0%BE%D0%B1%D1%8B-%D0%BF%D0%BB%D0%BE%D1%85%D0%B8%D0%B5-%D1%81%D0%BB%D0%BE%D0%B2%D0%B0-%D0%B8%D0%B7-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D1%84%D0%B0%D0%B9%D0%BB%D0%B0-badwords-%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BB%D0%B8%D1%81%D1%8C-%D0%B2-%D0%B8%D0%BD%D0%B8%D1%86%D0%B8%D0%BB%D0%B0%D0%B9%D0%B7%D0%B5%D1%80%D0%B5)

2020-12-28 16:20 UTC, ergeshmametuulukanat reviewed
Красавчик)

2020-12-28 18:34 UTC, tediik requested changes

2020-12-28 18:34 UTC, tediik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +            e.printStackTrace();
Нам тут на самом деле стектрейс вообще не важен, не велика ошибка, давай просто залогируем ситуацию

2020-12-29 08:56 UTC, softozhik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +            e.printStackTrace();
поправил - теперь сообщение в log-файл пишется

2020-12-29 20:18 UTC, tediik approved these changes

2020-12-29 20:18 UTC, merged