BasketAnonymous
tediik/online_store pull request #219
Opened 2020-12-29 14:40 UTC by Iambme

2020-12-29 14:41 UTC, Iambme commented
![](https://github.trello.services/images/mini-trello-icon.png) [Покупка товара для незалогиненного посетителя](https://trello.com/c/gI5kxfta/185-%D0%BF%D0%BE%D0%BA%D1%83%D0%BF%D0%BA%D0%B0-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D0%B0-%D0%B4%D0%BB%D1%8F-%D0%BD%D0%B5%D0%B7%D0%B0%D0%BB%D0%BE%D0%B3%D0%B8%D0%BD%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BE%D1%81%D0%B5%D1%82%D0%B8%D1%82%D0%B5%D0%BB%D1%8F)

2021-01-09 06:18 UTC, kanatsubanov321 reviewed
Проверил все по описанию работает) @Iambme

2021-01-09 10:30 UTC, softozhik commented
у меня при отправке из модалки regModalWindow пытается открыться страница /regNewCustomer и на почту письмо не отправляется

2021-01-10 19:37 UTC, tediik requested changes

2021-01-10 19:37 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/BasketServiceImpl.java
> +    public List<SubBasket> getBasket(String sessionID) {
надо поправить JavaDoc - у тебя появился входной параметр, опиши его

2021-01-10 19:37 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/BasketServiceImpl.java
> +    public void deleteBasket(SubBasket subBasket,String sessionID) {
тож самое, сигнатура метода поменялась, надо внести изменения в JavaDoc

2021-01-10 19:37 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/BasketServiceImpl.java
> +    public void addProductToBasket(Long id,String sessionID) {
аналогично, поправь доку

2021-01-11 11:28 UTC, tediik approved these changes

2021-01-11 15:06 UTC, merged