Bugfix/price change subscribe
tediik/online_store pull request #221
Opened 2020-12-29 21:25 UTC by kossme

Для проверки: Дропнуть БД и создать заново,

2020-12-30 08:43 UTC, kossme commented
![](https://github.trello.services/images/mini-trello-icon.png) [Проблема с отправкой почты: подписка на изменение цены товара](https://trello.com/c/4d8zcAHg/210-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0-%D1%81-%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%BE%D0%B9-%D0%BF%D0%BE%D1%87%D1%82%D1%8B-%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%BD%D0%B0-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D1%86%D0%B5%D0%BD%D1%8B-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D0%B0)

2021-01-03 20:58 UTC, tediik requested changes

2021-01-03 20:58 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +            System.out.println(userFromDB.getConfirmReceiveEmail());
это еще зачем?

2021-01-03 20:58 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +            User userFromDB = user.get();
вот эти три строки по сути заменяет метод ifPresent у Optional, перепиши, потренируешься заодно писать красивый правильный код

2021-01-03 20:58 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/ReceiveEmailSubscribeConfirmationImpl.java
> + */
отлично!

2021-01-03 20:58 UTC, tediik commented on src/main/java/com/jm/online_store/model/User.java
> +
глянь, вроде перечисления выносили в отдельный пакет же?

2021-01-03 20:58 UTC, tediik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +                        "<p>С Уважением</p><p>Online-store.ru</p>")
посмотри, у нас сейчас в application.yml есть константа вроде production-url - используй ее, это всяко лучше, чем потом по коду искать, кто где название вписал хардкорно

2021-01-03 20:58 UTC, tediik commented on src/main/java/com/jm/online_store/model/Comment.java
> +     private boolean deletedHasKids = false;
не понял как это изменение относится к твоей задаче, но если считаешь, что так нужно - ОК

2021-01-04 13:07 UTC, tediik approved these changes
Отлично

2021-01-04 13:07 UTC, merged