create swagger dockets for any role
tediik/online_store pull request #224
Opened 2021-01-07 13:14 UTC by Iambme

2021-01-07 13:19 UTC, Iambme commented
![](https://github.trello.services/images/mini-trello-icon.png) [Swagger добавить speces (докеты) - чтобы для каждой роли выдавало свой набор апи-методов](https://trello.com/c/3ShRET68/261-swagger-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-speces-%D0%B4%D0%BE%D0%BA%D0%B5%D1%82%D1%8B-%D1%87%D1%82%D0%BE%D0%B1%D1%8B-%D0%B4%D0%BB%D1%8F-%D0%BA%D0%B0%D0%B6%D0%B4%D0%BE%D0%B9-%D1%80%D0%BE%D0%BB%D0%B8-%D0%B2%D1%8B%D0%B4%D0%B0%D0%B2%D0%B0%D0%BB%D0%BE-%D1%81%D0%B2%D0%BE%D0%B9-%D0%BD%D0%B0%D0%B1%D0%BE%D1%80-%D0%B0%D0%BF%D0%B8-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%B2)

2021-01-10 07:00 UTC, kanatsubanov321 reviewed
Отлично!

2021-01-10 19:42 UTC, tediik requested changes

2021-01-10 19:42 UTC, tediik commented on src/main/java/com/jm/online_store/config/swagger/SpringFoxConfig.java
> +    public Docket api2() {
переименуй тут и далее, вместо цифры - apiManager и т.д., так нагляднее, где и что

2021-01-10 19:42 UTC, tediik commented on src/main/java/com/jm/online_store/config/swagger/SpringFoxConfig.java
> +    }
Я не увидел докета для сервисного работника

2021-01-10 19:42 UTC, tediik commented on src/main/resources/application.yml
> +    password: jm2020JM2020
это уже в свежем деве, обнови когда будешь переделывать

2021-01-11 11:26 UTC, tediik approved these changes

2021-01-11 11:26 UTC, merged