refactor/viewData
tediik/online_store pull request #228
Opened 2021-01-08 15:17 UTC by fRomans

2021-01-10 20:04 UTC, tediik requested changes

2021-01-10 20:04 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +     *
Вот вместо бесполезной пустой строчки, лучше бы описал комментарий правильно:
     * @param comment комментарий пользователя к продукту
     * @return ResponseEntity<?> ответ со статусом:
     * 304 - если то и то
     * 200 - когда комментарий был удачно обновлен
     */

2021-01-10 20:04 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +     *
смотреть предыдущее замечание, пустая строка ни к чему тут, столько времени я уже пытаюсь ее искоренить в проекте и объясняю, что она допускается когда текст комментария реально на несколько строчек и чтобы отделить визуально большой комментарий от описания параметоров и возвращаемого значения - можно использовать в качестве раздлеения пустую строчку. Доработай лучше комментарий как надо

2021-01-10 20:04 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +@ComponentScan({"com.delivery.request"})
не понял, это что такое и откуда?

2021-01-10 20:04 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
>      @GetMapping("/{productId}")
почему удалил комментарий??

2021-01-10 20:04 UTC, tediik commented on src/main/java/com/jm/online_store/model/dto/ProductForCommentDto.java
> +
убери лишнюю пустую строку

2021-01-10 20:04 UTC, tediik commented on src/main/java/com/jm/online_store/model/dto/CommentDto.java
> +            e.printStackTrace();
стектрейс думаю тут не нужен, давай уберем

2021-01-10 20:04 UTC, tediik commented on src/main/java/com/jm/online_store/model/dto/CommentDto.java
> +            commentDto.viewDataComment= commentEntity.getCustomer().getEmail();
viewDataComment - помнишь еще на ПП говорил тебе - учись сразу давать нормальные говорящие имена переменным!
переименуй например в userDescription - так понятнее, что поле представляет собой описание пользователя - фио либо логин

2021-01-10 20:04 UTC, tediik commented on src/main/java/com/jm/online_store/model/dto/CommentDto.java
> +            commentDto.viewDataComment = commentEntity.getCustomer().getLastName();
еще раз:
зачем так сложно?
проверили поле, если null - присвоили ему пустую строку: ""
В оконцовке склеили получившееся выражение и например проверили, если оно пустое или одни пробелы - значит вместо него выводим email.

2021-01-11 13:18 UTC, fRomans commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +     *
это не мои комменты и код тоже

2021-01-11 13:20 UTC, fRomans commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +     *
опять не мои коменты с кодом

2021-01-11 13:23 UTC, fRomans commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +@ComponentScan({"com.delivery.request"})
это муки творчества, сорри...

2021-01-11 13:24 UTC, fRomans commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
>      @GetMapping("/{productId}")
это ты мне в прошлый раз веле убрать

2021-01-11 13:25 UTC, fRomans commented on src/main/java/com/jm/online_store/model/dto/ProductForCommentDto.java
> +
выполнено

2021-01-11 13:26 UTC, fRomans commented on src/main/java/com/jm/online_store/model/dto/CommentDto.java
> +            e.printStackTrace();
код опять не мой, но стектрейс я убрал

2021-01-11 13:35 UTC, fRomans commented on src/main/java/com/jm/online_store/model/dto/CommentDto.java
> +            commentDto.viewDataComment= commentEntity.getCustomer().getEmail();
Выполнено. У меня плохо с английским. viewDataComment - обзор данных комментария( я так для себя переводил)))   )

2021-01-12 10:55 UTC, tediik approved these changes

2021-01-12 10:55 UTC, merged