Добавлен новый функционал Недавно просмотренные товары
tediik/online_store pull request #230
Opened 2021-01-11 15:47 UTC by DenisMalikovKzn

2021-01-11 15:50 UTC, DenisMalikovKzn commented
![](https://github.trello.services/images/mini-trello-icon.png) [Раздел Вы недавно смотрели эти товары](https://trello.com/c/NuYF7uKd/192-%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB-%D0%B2%D1%8B-%D0%BD%D0%B5%D0%B4%D0%B0%D0%B2%D0%BD%D0%BE-%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D0%BB%D0%B8-%D1%8D%D1%82%D0%B8-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D1%8B)

2021-01-13 12:08 UTC, tediik requested changes
Покажешь еще сегодня на созвоне

2021-01-13 12:08 UTC, tediik commented on src/main/java/com/jm/online_store/model/RecentlyViewedProducts.java
> +
одна строчка лишняя явно

2021-01-13 12:08 UTC, tediik commented on src/main/java/com/jm/online_store/model/RecentlyViewedProducts.java
> +    private String idProduct;
свяжи с продуками через id, тогда можно будет сразу доставать нужный продукт в запросе

2021-01-13 12:08 UTC, tediik commented on src/main/java/com/jm/online_store/repository/RecentlyViewedProductsRepository.java
> +    RecentlyViewedProducts findByIdProduct(String idProduct);
вот, тебе по моему этот метод фактически нужен только чтобы потом вытащить сами продукты из этого объекта, ты сможешь сразу вытаскивать Products если свяжешь через id продукта

2021-01-13 12:08 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/RecentlyViewedProductsServiceImpl.java
> +    public RecentlyViewedProducts findIdProduct(String idProduct) {
переименовать - findByIdProduct

2021-01-13 12:08 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/RecentlyViewedProductsServiceImpl.java
> +        else {
почему так? на одной строчке пишем по кодстайлу

2021-01-13 12:08 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/RecentlyViewedProductsServiceImpl.java
> +        }
смотри, т.е. получается, что с фронта ты по факту ожидаешь не полноценный объект RecentlyViewedProducts, а кастомизированный, без поля дата, т.к. дату ты всегда сам устанавливаешь, зачем тогда напрягать фронтов заполнением этого поля? Значит у тебя надо в контроллере принимать объект например RecentlyViewedProductsDTO, в котором будут только 2 поля - User и IdProduct

2021-01-13 12:08 UTC, tediik commented on src/main/resources/static/js/product-page.js
> +            toastr.error("Просмотренный товар не сохранился");
а вот тут давай просто в лог, не будем сообщать пользователю, что мы за ним пристально следим, переделай!

2021-01-13 12:08 UTC, tediik commented on src/main/resources/static/js/customer-profile-page-function.js
> +function fillSomeProducts1(data) {
зачем цифра в названии?

2021-01-13 12:08 UTC, tediik commented on src/main/resources/static/js/customer-profile-page-function.js
> +    let prodsView1 = document.getElementById('recentlyProductsViewDiv');
тут зачем цифры в именах переменных, что за костыли?

2021-01-13 12:08 UTC, tediik commented on src/main/resources/static/js/customer-profile-page-function.js
> +                        <img class="bd-placeholder-img" src="/uploads/images/products/0.jpg">
картинка продукта? у всех будет одна и та же??

2021-01-13 12:08 UTC, tediik commented on src/main/resources/static/js/customer-profile-page-function.js
> +            }
коряво конечно, ну да ладно, оставляй так, я понял, что ты хочешь сделать, но делается оно не так, есть flexbox для этого

2021-01-13 12:08 UTC, tediik commented on src/main/resources/static/js/customer-profile-page-function.js
> +        prodsView1.innerHTML = 'Ожидайте новые продукты'
может просто вывести надпись "Пока тут ничего нет"

2021-01-13 12:08 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +        session.setAttribute(String.valueOf(counterValue), recentlyViewedProducts.getIdProduct());
я упорно не могу понять, а зачем нам вообще нужно тут сохранять какой то номер??? почему нельзя хранить один и тот же атрибут, а в качестве значения - список идентификаторов продуктов??

2021-01-13 12:08 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +        RecentlyViewedProducts recentlyViewedProducts = (RecentlyViewedProducts) session.getAttribute("idProduct" + count.getAndIncrement());
это я так понял вообще нигде не используется??

2021-01-13 12:08 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +    }
когда ты переделаешь немного сущность RecentlyViewedProducts и свяжешь ее с продуктами - ты сможешь получать из БД запросом сразу продукты и уйдешь от использования этого некрасивого кода

2021-01-13 17:45 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +        session.setAttribute(String.valueOf(counterValue), recentlyViewedProducts.getIdProduct());
я просто не нашел как это делается поначалу и что так можно

2021-01-13 17:46 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +        RecentlyViewedProducts recentlyViewedProducts = (RecentlyViewedProducts) session.getAttribute("idProduct" + count.getAndIncrement());
да это просто как дополнительный какой то потенциал что бы потом где то может быть это пригодится

2021-01-13 17:50 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/model/RecentlyViewedProducts.java
> +
можно я ее удалю тогда ?

2021-01-13 19:42 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/model/RecentlyViewedProducts.java
> +    private String idProduct;
ломаю голову не знаю как связать @ManyToOne или @ManyToMany?

2021-01-16 16:12 UTC, tediik requested changes
Я уверен, что твой код не работает как надо. После того как поправишь все замечания (а были замечения которые ты почему то просто проигнорировал), сделай проверки:
Зайди под покупателем1 и попробуй пройтись по нескольким продуктам, потом по одному и тому же продукту пройдись 2 раза.
Дальше не закрывая этого окна браузера открой Приватное окно браузера и в нем зайди под ДРУГОЙ учеткой покупателя - покупатель2 и тоже пройдись по продуктам, причем желательно по тем же самым, что и покупатель 1.
Теперь иди в личные кабинеты обоих покупателей и проверяй, работает ли твой код.

2021-01-16 16:12 UTC, tediik commented on src/main/resources/static/js/product-page.js
> +            toastr.error("Просмотренный товар не сохранился");
Еще раз - не надо сыпать ненужными сбивающими с толку покупателя сообщениями, убери тостер, просто пиши в лог

2021-01-16 16:12 UTC, tediik commented on src/main/resources/static/js/customer-profile-page-function.js
> +function fillSomeProducts1(data) {
Вопрос остается - зачем цифра в названии??

2021-01-16 16:12 UTC, tediik commented on src/main/resources/static/js/customer-profile-page-function.js
> +    let prodsView1 = document.getElementById('recentlyProductsViewDiv');
тут зачем цифры в именах переменных, что за костыли?

2021-01-16 16:12 UTC, tediik commented on src/main/resources/static/js/customer-profile-page-function.js
> +                        <img class="bd-placeholder-img" src="/uploads/images/products/0.jpg">
картинка продукта? у всех будет одна и та же??

2021-01-16 16:12 UTC, tediik commented on src/main/resources/static/js/customer-profile-page-function.js
> +        prodsView1.innerHTML = 'Ожидайте новые продукты'
может просто вывести надпись "Пока тут ничего нет"

2021-01-16 16:12 UTC, tediik commented on src/main/java/com/jm/online_store/model/Product.java
> +
Зачем опять вставил пустую лишнюю строку?

2021-01-16 16:12 UTC, tediik commented on src/main/java/com/jm/online_store/model/Product.java
> +import java.util.ArrayList;
Если этот импорт не используешь - убирай!

2021-01-16 16:12 UTC, tediik commented on src/main/java/com/jm/online_store/model/Customer.java
> +import javax.persistence.ManyToMany;
если это лишние импорты - убирай и import javax.persistence.CascadeType; проверь также

2021-01-16 16:12 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +    public ResponseEntity<String> saveIdProductToSession(@RequestBody Long productParam, HttpServletRequest request)  {
почему такое имя - productParam при этом тип Long?
Это id продукта? Тогда и имя должно быть productId

2021-01-16 16:12 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +        List<Product> listProduct = recentlyViewedProductsService.findAllRecentlyViewedProductsByUserId(userService.getCurrentLoggedInUser().getId()).stream().map(RecentlyViewedProducts::getProduct).
все круто, только это можно сразу в return, все равно эту переменную нигде не используешь, и обязательно разбить строчку - слишком длинная, часть методов просто с новой строки

2021-01-16 16:12 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +     * Метод получает из базы коллекцию List Продуктов  которые просматривал юзер
переименуй: Метод получает из базы список Продуктов, которые просматривал пользователь

2021-01-16 16:12 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/RecentlyViewedProductsServiceImpl.java
> +     * Метод получает проверяет есть ли данная запись в таблице
так он получает или проверяет?

2021-01-16 16:12 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/RecentlyViewedProductsServiceImpl.java
> +     * @param productId просмотренного то вара
поправь ошибку

2021-01-16 16:12 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/RecentlyViewedProductsServiceImpl.java
> +        }
судя по коду выше у тебя в принципе теперь не может быть recentlyViewedProductsNew.getProduct() == null а значит  и проверка эта не имеет смысла!

2021-01-16 16:12 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/RecentlyViewedProductsServiceImpl.java
> +     * Метод получает из базы коллекцию List сущностей RecentlyViewedProducts в которых есть Product которые просматривал юзер
Замени на:
Метод получает из базы список сущностей RecentlyViewedProducts, в которых есть Product, которые просматривал пользователь

2021-01-18 13:00 UTC, tediik requested changes
Замечания, в основном повторые (по третьему разу!)

2021-01-18 13:00 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/RecentlyViewedProductsServiceImpl.java
> +     * @param productId просмотренного то вара
почему мне нужно повторять замечания из раза в раз, будь внимательнее - поправь ошибку!

2021-01-18 13:00 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/RecentlyViewedProductsServiceImpl.java
> +            recentlyViewedProductsRepository.save(recentlyViewedProductsNew);
почему этот код съехал правее? поправь

2021-01-18 13:00 UTC, tediik commented on src/main/resources/static/js/customer-profile-page-function.js
> +                        <img class="bd-placeholder-img" src="/uploads/images/products/0.jpg">
третий раз пишу - картинка продукта у всех будет одна и та же??

2021-01-20 19:08 UTC, closed without merging