Merge branch 'dev' into refactor/make_start_url_similar
tediik/online_store pull request #231
Opened 2021-01-12 23:04 UTC by ergeshmametuulukanat

2021-01-12 23:11 UTC, ergeshmametuulukanat commented
![](https://github.trello.services/images/mini-trello-icon.png) [Рефакторинг API](https://trello.com/c/FdKk7yar/280-%D1%80%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%BD%D0%B3-api)

2021-01-14 08:12 UTC, siedhe reviewed
+

2021-01-14 10:56 UTC, tediik requested changes

2021-01-14 10:56 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AddressRestController.java
> +    @GetMapping(value = "/rest/allShops")
/api/customer/rest/allShops ты серьезно? ))) зачем туда еще rest то?

2021-01-14 10:56 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AddressRestController.java
> +    @GetMapping(value = "/rest/allShops")
И ниже проверь - тоже убери /rest/
+ естественно проверь в тех местах, где идет ссылка сюда

2021-01-14 10:56 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AllUsersRestController.java
> +@RequestMapping(value = "/api/users")
смотри, тут есть эндпоинты 
@PostMapping("/uploadImage")
@DeleteMapping("/deleteImage")
Что как-то не очень относится к работе с юзерами, вынеси в отдельный рест-контроллер, пожалуйста

2021-01-14 10:56 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AuthorityRestController.java
> +@RequestMapping("/api/authority")
смотри, я вообще не вижу тут никакого authority, я бы вообще переименовал контроллер и эндпоинт например в /profile

И смотри, ниже два одинаковых по сути эндпоинта 
/changemail и /changeEmail
если бы тебе дали пользоваться таким АПИ, думаю, ты бы очень сильно ругался и плевался, убери один

2021-01-14 10:56 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/MainPageRestController.java
> +    @PostMapping("/currentUrl")
по этому контроллеру молчу, потому что по нему есть отдельная таска

2021-01-14 10:56 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/StockRestController.java
> +@RequestMapping("/api")
давай сделаем этот контроллер понятнее, пусть общий url будет
/api/stock
Ниже у тебя там опять есть приставка /rest - ее убери!

2021-01-14 10:56 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +@RequestMapping("/api/customer")
блин... эндпоинт /getManagerById/
тут конечно совершенно не к месту..
что с ним делать.. может куда-то перенести его вообще, но у меня пока нет мыслей куда, чтобы он по секьюрности был доступен покупателям

2021-01-14 10:56 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerCharacteristicsRestController.java
> +@RequestMapping("/api")
вынеси общую часть как /api/manager/product/ - что в нашем случае позволяет с помощью настроек секьюрности разделять кому можно сюда "ходить", ниже там опять убери /rest в одном месте
А сам контроллер предлагаю переименовать в более правильное ProductCharacteristicsRestController

2021-01-14 10:56 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerProductsRestController.java
> +@RequestMapping("/api")
просто добавить впереди /api это не решение вопроса, тут чет ты совсем схалявил )))
убирай везде внизу /rest
и я смотрю, что вроде можно в общий url вынести так
/api/product - обрати внимание без s - без множественного числа! Это тоже важно, проверь, что везде, кто на это ссылается, чтобы оно работало
Сам класс наверное тоже можно переименовать в ProductsRestController

2021-01-14 10:56 UTC, tediik commented on src/main/resources/static/js/bad-words.js
> +let badWordsRestUrl = "/api/rest/bad-words/"
ну вот, о чем я и говорил, чтобы не было таких метаморфоз, поправить надо контроллеры и мапинг

2021-01-14 19:46 UTC, ergeshmametuulukanat commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +@RequestMapping("/api/customer")
@tediik я не совсем понимаю куда это можно перенести(((

2021-01-14 19:48 UTC, ergeshmametuulukanat commented on src/main/java/com/jm/online_store/controller/rest/AllUsersRestController.java
> +@RequestMapping(value = "/api/users")
сделал новый контроллер ImageRestController

2021-01-14 21:03 UTC, tediik requested changes

2021-01-14 21:03 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/serviceWorker/RepairOrderRestController.java
> +    @GetMapping("//getDiagnosticsRepairOrder")
погоди, с двумя // вроде не будет работать же?

2021-01-14 21:03 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/serviceWorker/RepairOrderRestController.java
> +    @GetMapping("//getAcceptedRepairOrder")
погоди, с двумя // вроде не будет работать же?

2021-01-14 21:03 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/serviceWorker/RepairOrderRestController.java
> +    @GetMapping("//findAllWithoutCanceled")
погоди, с двумя // вроде не будет работать же?

2021-01-14 21:03 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AuthorityRestController.java
> +@RequestMapping("/api/profile")
Давай этот класс тоже переименуем в ProfileRestController

2021-01-15 08:36 UTC, tediik approved these changes

2021-01-15 08:36 UTC, merged