Fixed adding to favorites
tediik/online_store pull request #234
Opened 2021-01-16 16:02 UTC by DotsenkoS

Исправлено добавление товаров в избранное для новых пользователей.
При активации нового пользователя не создавалась их FavouritesGroup. Теперь ок

2021-01-19 13:12 UTC, dmitrykruglov1993 reviewed
В целом по заданию все норм (да и по коду тоже), получается что при подтверждении записи с мэйла, добавляется запись в favorites_group, и товар даже добавляется в избранное) но у меня не сработал метод удаления товара, также как и перенос его в корзину. Но скорей всего это уже не твоя проблема) 
Все хорошо

2021-01-19 13:59 UTC, tediik requested changes

2021-01-19 13:59 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +import com.jm.online_store.model.*;
нет, уберай импорты через звездочку, верни как было, для этого у тебя в Идее должна быть сделана соответствующая настройка - смотри в списке docs в Трелло

2021-01-19 13:59 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +import com.jm.online_store.service.interf.*;
нет, уберай импорты через звездочку, верни как было, для этого у тебя в Идее должна быть сделана соответствующая настройка - смотри в списке docs в Трелло

2021-01-19 13:59 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +
ну тут явно одна пустая строка лишняя же

2021-01-20 09:23 UTC, tediik approved these changes

2021-01-20 09:23 UTC, merged