Привязал эндпоинты из MainPageRestController к сущностям.
tediik/online_store pull request #235
Opened 2021-01-18 09:53 UTC by dmitrykruglov1993

2021-01-19 14:12 UTC, dmitrykruglov1993 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Рефакторинг РЕСТ-АПИ](https://trello.com/c/K8aCtW7U/281-%D1%80%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%BD%D0%B3-%D1%80%D0%B5%D1%81%D1%82-%D0%B0%D0%BF%D0%B8)

2021-01-20 15:08 UTC, MaksimovMA commented on src/main/java/com/jm/online_store/controller/rest/MainPageRestController.java
> -    @PostMapping("/currentUrl")
"/api/currentUrl -> зачем он нам вообще? "
 Без данного метода не корректно работает login. После "Sing in" выводится пустая страница.
И в консоли выводится " WARN  o.s.web.servlet.PageNotFound - No mapping for POST /api/currentUrl"

2021-01-20 20:32 UTC, tediik requested changes

2021-01-20 20:32 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CategoryRestController.java
> +@RequestMapping("/api")
почему не вынести в общий url и /categories/ ??

2021-01-20 20:32 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/LoginRestController.java
> +        return ResponseEntity.ok("Current URL was returned");
слушай, интересная получается ситуация же, он же никакой не get, он в явном виде setCurrentUrl!
поправь название и описание апи - @ApiOperation(value = "Returns current URL")
И строчку на фронт не возвращай, верни пока просто статус 200 и без тела

2021-01-20 20:32 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerNewsRestController.java
> +    @GetMapping("/publishednews")
а ты уверен, что секьюрити разрешит сюда доступ анониму? и вообще хоть кому-то, у кого права не менеджер?

2021-01-20 20:32 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerNewsRestController.java
> +     * Возвращает список опубликованных новостей На главную страницу - список передаётся в метод сервиса .findPublishedNews()
поправь, вроде список передается совсем в другой метод сервиса, да и вообще, я думаю, можно не указывать в какой метод сервиса он передается, давай уберем это

2021-01-20 20:32 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/StockRestController.java
> +     * Возвращает список опубликованных акций  - список передаётся в метод сервиса .findPublishedStocks()
и опять же, не нужно упоминание, куда передается список

2021-01-20 20:32 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/StockRestController.java
> +        List<Stock> publishedStocks= stockService.findPublishedStocks();
что с = почему знак прилип к слову?

2021-01-20 20:32 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/StockRestController.java
> +    @GetMapping("/publishedstocks")
проблема в том, что у нас в конфигурации секьюрити скорее всего доступ сюда разрешен только менеджеру, надо прописать аннотации доступа на самом методе в сервисе - типа можно всем, либо мутить что-то с настройкой в конфиге секьюрити

2021-01-20 20:32 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/LoginRestController.java
> +        return ResponseEntity.ok("Current URL was returned");
И надо проверить, что он точно доступен всем юзерам, которым должен был быть доступен

2021-01-20 20:32 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/RegistrationRestController.java
> + * Рест контроллер главной страницы.
поправить описание

2021-01-20 20:32 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/RegistrationRestController.java
> +@Api(description = "Rest controller of the Main page")
поправить описание

2021-01-20 20:32 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/RegistrationRestController.java
> +    @ResponseBody
хмм...??

2021-01-21 09:05 UTC, dmitrykruglov1993 commented on src/main/java/com/jm/online_store/controller/rest/RegistrationRestController.java
> +    @ResponseBody
хмм?)

2021-01-21 15:44 UTC, tediik requested changes

2021-01-21 15:44 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CategoryRestController.java
> +    @GetMapping("/categories")
не понял, мы получим итоговый url
/api/categories/categories ?? Что за ерунда?

2021-01-21 15:44 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/LoginRestController.java
> +    @ApiOperation(value = "Return HttpStatus 200")
Прикольно, я немного не это имел ввиду, когда писал прошлое замечание - получается, что делает этот контроллер? Возвращает статус 200 )))) Смешная ситуация ))))

2021-01-23 15:04 UTC, tediik approved these changes

2021-01-23 15:04 UTC, merged