недавно просмотренные товары и еще функционал удаления юзера
tediik/online_store pull request #236
Opened 2021-01-19 12:21 UTC by DenisMalikovKzn

2021-01-19 12:38 UTC, DenisMalikovKzn commented
![](https://github.trello.services/images/mini-trello-icon.png) [Раздел Вы недавно смотрели эти товары](https://trello.com/c/NuYF7uKd/192-%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB-%D0%B2%D1%8B-%D0%BD%D0%B5%D0%B4%D0%B0%D0%B2%D0%BD%D0%BE-%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D0%BB%D0%B8-%D1%8D%D1%82%D0%B8-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D1%8B)

2021-01-19 13:30 UTC, tediik requested changes

2021-01-19 13:30 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +import org.springframework.web.bind.annotation.*;
импорты со звездочкой мы не используем, у тебя должна быть сделана соответствующая настройка в Идее

2021-01-19 13:30 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +        return ResponseEntity.ok("Session is set");
если подумать, то лучше отдавать что-то вроде - Product is saved in session
Потому что мы все же сохраняем продукты в сессиии (должны были, но это ладно, не важно)

2021-01-20 18:14 UTC, tediik approved these changes

2021-01-21 16:53 UTC, merged