Feature/moderators
tediik/online_store pull request #239
Opened 2021-01-21 16:44 UTC by softozhik

много файловизменено, добавлен рест-контролер, новая роль, новый пользователь, новая таблица в бд, дополнен инициализатор, изменена таблица commentreport и т.д.

2021-01-21 16:45 UTC, softozhik commented
![](https://github.trello.services/images/mini-trello-icon.png) [Модераторы](https://trello.com/c/KkevXTZP/227-%D0%BC%D0%BE%D0%B4%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%D1%8B)

2021-01-21 17:46 UTC, MaksimovMA commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +
Достаточно одного пропуска строки

2021-01-21 17:46 UTC, MaksimovMA commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +        Role supermoderatorRole = new Role("ROLE_SUPERMODERATOR");
camel case мне кажется был бы тут уместен superModeratorRole 
и ROLE_SUPER_MODERATOR для удобства чтения

2021-01-21 17:46 UTC, MaksimovMA commented on src/main/java/com/jm/online_store/controller/rest/moderator/ModeratorRestController.java
> +//        System.out.println();
Зачем?

2021-01-22 16:02 UTC, softozhik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +
спасибо, убрал

2021-01-22 16:02 UTC, softozhik commented on src/main/java/com/jm/online_store/controller/rest/moderator/ModeratorRestController.java
> +//        System.out.println();
спасибо, убрал

2021-01-22 16:04 UTC, softozhik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +        Role supermoderatorRole = new Role("ROLE_SUPERMODERATOR");
предполагается, что это одно слово, а не два. и дело вкуса. поэтому... пусть ментор решает, переделать или нет :-)

2021-01-25 10:34 UTC, softozhik commented
вернул назад пути к файлам картинок

**!!!ВАЖНО!!!**
для работы нужно, чтобы папка uploads/images/ была в корне проекта, если ее нет - то создать или скопировать из resource, т.к. сама папка в gitignore, т.е. не обновляется при синхронизации с репозиторием

2021-01-25 16:00 UTC, tediik requested changes

2021-01-25 16:00 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/moderator/ModeratorRestController.java
> +     */
Лишняя пустая строка между комментариями НЕ нужна, используем только когда текста много, чтобы отделить от описания параметров.
Распиши комметарий к возвращаемому значению.

2021-01-25 16:00 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/moderator/ModeratorRestController.java
> +    @ApiOperation(value = "List moderators activities")
почему в названии и мапинге статистика, а в описании к апи появились какие то активности? Не надо путать людей и мешать понятия, придерживайся единообразия в коде

2021-01-25 16:00 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/ModeratorController.java
> +        model.addAttribute("user", user);
больше ничего не отдаем на фронт через таймлиф и обычные контроллеры, со страницы будет запрос на соответствующий рест-контроллер чтобы получить текущего залогиненного пользователя

2021-01-25 16:00 UTC, tediik commented on src/main/java/com/jm/online_store/model/ReportComment.java
> +@Table(name = "report_comment")
ну оно в общем и так же работало, аннотация не является обязательной

2021-01-25 16:00 UTC, tediik commented on src/main/java/com/jm/online_store/repository/ModeratorsStatisticRepository.java
> +    ModeratorsStatistic getByModeratorEquals(User moderator);
лучше - getModeratorsStatisticByModerator

2021-01-25 16:00 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/ModeratorsStatisticServiceImpl.java
> +     */
во всем классе убери пустую разделяющую строку в комментариях, пожалуйста

2021-01-25 16:00 UTC, tediik commented on src/main/resources/static/js/moderator-comments.js
> +                    )
это неправильное использование шаблонных строк js, пересмотри лекции

2021-01-25 16:00 UTC, tediik commented on src/main/resources/templates/moderator-profile.html
> +
а у нас разве не было странички модератора??

2021-01-25 16:00 UTC, tediik commented on src/main/resources/templates/moderator-statistic.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
выше ты добавил профиль модератора, тут страница статистики, но при этом тут тоже меню кабинета модератора?

2021-01-29 10:30 UTC, tediik approved these changes

2021-01-29 10:30 UTC, merged