починка тестов корзины и активации юзера и тестового метода обновления картинки профиля
tediik/online_store pull request #241
Opened 2021-01-24 11:49 UTC by DenisMalikovKzn

2021-01-24 11:50 UTC, DenisMalikovKzn commented
![](https://github.trello.services/images/mini-trello-icon.png) [Валятся тесты - починить!](https://trello.com/c/3PPRJKsJ/283-%D0%B2%D0%B0%D0%BB%D1%8F%D1%82%D1%81%D1%8F-%D1%82%D0%B5%D1%81%D1%82%D1%8B-%D0%BF%D0%BE%D1%87%D0%B8%D0%BD%D0%B8%D1%82%D1%8C)

2021-01-26 16:59 UTC, tediik requested changes

2021-01-26 16:59 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +    private static final String uploadDirectory = "src" + File.separator + "main" + File.separator + "resources" + File.separator + "uploads" + File.separator + "images";
хорошо, возможно ты прав, тогда проведи такой тест, запакуй наше приложение в jar-файл и запусти его, далее попробуй поменять картинку профиля и еще что-либо где требуется обращение к этому пути и убедись, что оно точно работает. В идеале бы после этого еще проверить тоже самое и на Линукс, но я понимаю, что у тебя вероятно нет сейчас такой возможности, но можно попросить ребят.
Иначе, объясняю, я разверну твой код на Хероку, где конечно Линукс во первых и во вторых запуск происходит нашего приложения из jar-файла, и оно бац и упадет при обращении к несуществующей папке, либо папке в которую запрещена запись.

2021-01-27 10:37 UTC, tediik approved these changes

2021-01-27 10:38 UTC, merged