Refactoring/authentication using jwt
tediik/online_store pull request #243
Opened 2021-01-25 19:41 UTC by Cotharsis

Сделал аутентификацию с помощью JWT-токенов

2021-01-25 23:27 UTC, ghost commented on src/main/java/com/jm/online_store/config/security/jwt/JwtTokenProvider.java
> +
лишний пропуск строки

2021-01-25 23:27 UTC, ghost commented on src/main/java/com/jm/online_store/config/security/jwt/JwtTokenProvider.java
> +
Достаточно одного пропуска строки

2021-01-25 23:27 UTC, ghost commented on src/main/java/com/jm/online_store/config/security/jwt/JwtTokenProvider.java
> +    private long validityInMilliseconds = 3600000;
@Value aннотация тут бы отлично смотрелась

2021-01-25 23:27 UTC, ghost commented on src/main/java/com/jm/online_store/config/security/jwt/JwtUserFactory.java
> +
Очень много лишних пустых строк в классе

2021-01-25 23:27 UTC, ghost commented on src/main/java/com/jm/online_store/controller/restjwt/AuthenticationRestControllerJVT.java
> +
Достаточно одного пропуска строки

2021-01-25 23:27 UTC, MaksimovMA commented on src/main/java/com/jm/online_store/controller/restjwt/AuthenticationRestControllerJVT.java
> +public class AuthenticationRestControllerJVT {
Название класса поправь: AuthenticationRestControllerJW

2021-01-25 23:27 UTC, MaksimovMA commented on src/main/java/com/jm/online_store/config/security/SecurityConfig.java
> +                .antMatchers("/api/auth/login").permitAll()
permitAll() ниже строчкой

2021-01-25 23:27 UTC, MaksimovMA commented on src/main/java/com/jm/online_store/config/security/jwt/JwtTokenProvider.java
> +    private long validityInMilliseconds = 3600000;
@Value aннотация хорошо бы тут смотрелась

2021-01-25 23:27 UTC, MaksimovMA commented on src/main/java/com/jm/online_store/controller/restjwt/AuthenticationRestControllerJVT.java
> +public class AuthenticationRestControllerJVT {
Название класса исправь на AuthenticationRestControllerJWT

2021-01-25 23:27 UTC, MaksimovMA commented on src/main/java/com/jm/online_store/model/JwtUser.java
> +
Достаточно одного пропуска строки

2021-01-25 23:27 UTC, MaksimovMA commented on src/main/java/com/jm/online_store/model/JwtUser.java
> +
Достаточно одного пропуска строки

2021-01-25 23:27 UTC, MaksimovMA commented on src/main/java/com/jm/online_store/config/security/jwt/JwtUserFactory.java
> +
Какая смысловая нагрузка данного пропуска строки?

2021-01-25 23:27 UTC, MaksimovMA commented on src/main/java/com/jm/online_store/config/security/jwt/JwtTokenProvider.java
> +
Какая смысловая нагрузка данного пропуска строки?

2021-01-25 23:27 UTC, MaksimovMA commented on src/main/java/com/jm/online_store/config/security/jwt/JwtTokenProvider.java
> +
Какая смысловая нагрузка данного пропуска строки?

2021-01-25 23:27 UTC, MaksimovMA commented on src/main/java/com/jm/online_store/controller/restjwt/AuthenticationRestControllerJVT.java
> +
Очень много пустых строк в коде в местах где они не нужны.

2021-01-27 11:33 UTC, tediik requested changes

2021-01-27 11:33 UTC, tediik commented on src/main/java/com/jm/online_store/model/dto/UserDto.java
> +    }
я не понял назначение этих методов, но вероятно нужны, проверь

2021-01-27 11:33 UTC, tediik commented on src/main/java/com/jm/online_store/model/dto/UserDto.java
> +    boolean enabled;
посмотри какие еще поля есть у нас в User, может чего полезное еще сюда закинешь в ДТО, и эту ДТО давай там при авторизации через JWT будет отдавать (+ токен, конечно)

2021-01-27 11:33 UTC, tediik commented on src/main/java/com/jm/online_store/model/dto/AuthenticationRequestDto.java
> +}
вероятно вообще не нужна!

2021-01-27 11:33 UTC, tediik commented on src/main/java/com/jm/online_store/model/JwtUser.java
> +public class JwtUser implements UserDetails {
попробуй вообще отказаться от этого класса в пользу User, мне кажется вполне должно получится

2021-01-27 11:33 UTC, tediik commented on src/main/java/com/jm/online_store/exception/JwtAuthenticationException.java
> + * Authetication exception for JwtAppDemo application.
почему JwtAppDemo  ))))

2021-01-27 11:33 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/jwt/JwtConfigurer.java
> +    }
можно через Ломбок

2021-01-27 11:33 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/jwt/JwtUserFactory.java
> +public final class JwtUserFactory {
вероятно вообще этот класс станет не нужен!

2021-01-27 11:33 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/jwt/JwtUserFactory.java
> +        return userRoles.stream().map(role -> new SimpleGrantedAuthority(role.getName())).collect(Collectors.toSet());
этот метод не забудь пристроить куда надо

2021-01-27 11:33 UTC, tediik commented on src/main/java/com/jm/online_store/controller/restjwt/AuthenticationRestControllerJWT.java
> +    }
можно тоже через ломбок!

2021-01-27 11:33 UTC, tediik commented on src/main/java/com/jm/online_store/controller/restjwt/AuthenticationRestControllerJWT.java
> +            "}")
тут потом описание обязательно поправь для фронтов!

2021-01-27 11:33 UTC, tediik commented on src/main/java/com/jm/online_store/controller/restjwt/AuthenticationRestControllerJWT.java
> +            response.put("email", email);
тут положим объект UserDTO

2021-01-28 16:01 UTC, tediik approved these changes

2021-01-28 16:01 UTC, merged