bugfix/deleteUserFromAdminPage
tediik/online_store pull request #247
Opened 2021-01-29 06:57 UTC by DotsenkoS

Исправлено:
- На странице юзера неправильно открывались и не работали модалки delete и edit из таблицы юзеров  
- Не работал выбор списка всех юзеров на странице админа (show all users) 
- Для незалогиненного пользователя при переходе на любую страницу выпадала ошибка
- При входе в кабинет админа появлялась ошибка Uncaught (in promise) ReferenceError: moment is not define.

2021-01-29 11:16 UTC, softozhik commented on src/main/java/com/jm/online_store/controller/rest/admin/AdminRestController.java
> +            e.printStackTrace();
stacktrace для отладки выводится, здесь он лишний, кмк

2021-01-29 11:16 UTC, softozhik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +            e.printStackTrace();
тоже stacktrace не нужен

2021-01-29 11:19 UTC, softozhik commented on src/main/resources/static/js/admin-page-render.js
> +                            .then(blockedUser => console.log('Customer: ' + blockedUser.email + ' with ID: ' + blockedUser.id + '. Status = Locked'))
console.log тоже для отладки, здесь не нужны

2021-01-29 11:23 UTC, softozhik commented on src/main/resources/static/js/profile-admin-manager-service.js
> +            $("#register_date").val(currentUser.registerDate);
это все в этой версии берется через thyamleaf из html, я поправил в ветке про модераторов и в поле типа span не вставляется  через .val, как выяснилось, через .html вставляется
т.е. думаю, эти правки не нужны или при мерже принять мои :-)

2021-01-29 12:01 UTC, softozhik commented
если я правильно понял логику, то customer при удалении блокируется, а user удаляется? причем, при неудавшемся удалении, из списка пропадает, а при обновлении страницы снова появляется

2021-01-31 18:23 UTC, tediik requested changes

2021-01-31 18:23 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/admin/AdminRestController.java
> +        User deletedUserInfo = new User(id, userService.findUserById(id).getUsername());
не понял этого "финта ушами", почему нельзя было просто:
User deletedUserInfo = userService.findUserById(id) ??

2021-01-31 18:23 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +        log.debug("User with id: {}, was deleted successfully", id);
по идее мы не удаляем и нехорошо вводить в заблуждение, надо написать, что просто блокируем

2021-01-31 18:23 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +        User deletedUser = userService.findUserById(id);
раз мы просто блокируем, а не удаляем, давай по уму и метод переименуем и переменную например:
User lockedUser

2021-01-31 18:23 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +            return  ResponseEntity.ok("User is not authenticated. Product is not saved to session");
2 пробела )))

2021-01-31 18:49 UTC, DotsenkoS commented on src/main/java/com/jm/online_store/controller/rest/admin/AdminRestController.java
> +        User deletedUserInfo = new User(id, userService.findUserById(id).getUsername());
User deletedUserInfo = userService.findUserById(id)  - не получится -  так deletedUserInfo будет ссылкой на юзера которого удаляем, и получится "не определен". Поэтому делаю отдельного с  необходимой информацией.

2021-02-01 19:38 UTC, tediik requested changes

2021-02-01 19:38 UTC, tediik commented on src/main/resources/static/js/profile-admin-manager-service.js
> +
погоди, на одном из созвонов мы решали, что запрещаем нашим сотрудникам (все, кто не покупатель) выпиливаться из системы самостоятельно, т.е. они не могут удалять свои профили! Их может удалять только админ!

2021-02-03 22:12 UTC, tediik approved these changes

2021-02-03 22:12 UTC, merged