Fiuture/make_picture_for_product
tediik/online_store pull request #251
Opened 2021-01-31 18:25 UTC by dmitrykruglov1993

2021-01-31 18:28 UTC, dmitrykruglov1993 commented
![](https://github.trello.services/images/mini-trello-icon.png) [У продуктов можно менять картинку](https://trello.com/c/dsjIezJE/289-%D1%83-%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D0%BE%D0%B2-%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE-%D0%BC%D0%B5%D0%BD%D1%8F%D1%82%D1%8C-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D1%83)

2021-02-05 20:49 UTC, DenisMalikovKzn reviewed
код вроде без нареканий 
только вот во фронте я  пока не силен

2021-02-06 16:15 UTC, tediik requested changes
В общем ты молодец! Но замечания все равно есть, придется исправлять

2021-02-06 16:15 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/PictureProductController.java
> +package com.jm.online_store.controller.rest;
Похоже надо переложить в пакет manager!

2021-02-06 16:15 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/PictureProductController.java
> +    public ResponseEntity<String> editPicture(@PathVariable("id") Long id, @RequestParam("pictureFile") MultipartFile pictureFile) {
почему нет описания для сваггера?

2021-02-06 16:15 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/PictureProductController.java
> +     * @param pictureFile
посмотри другие нормальные JavaDoc, описание полей должно присутствовать. Добавлять пустую строчку между основным описание метода и описанием полей не нужно.

2021-02-06 16:15 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/PictureProductController.java
> +    @DeleteMapping("/picture/delete/{id}")
то же самое, нет описания для сваггера (посмотри в других контроллерах) и оформи нормально JavaDoc

2021-02-06 16:15 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ProductsRestController.java
> +        return new ResponseEntity(product.getId(), HttpStatus.OK);
у нас все в одном стиле (по крайней мере я стараюсь отслеживать) - поэтому давай через статические фабричные методы, а не создание нового инстанса

2021-02-06 16:15 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/ProductController.java
> +import org.springframework.web.bind.annotation.PathVariable;
вроде не используешь тут

2021-02-06 16:15 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/ProductController.java
> +import com.jm.online_store.repository.ProductRepository;
вроде не используешь тут

2021-02-06 16:15 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/ProductController.java
> +        model.addAttribute("product", product);
нет, мы максимально будем сейчас уходить от передачи чего бы то ни было через атрибуты, потому что нам надо отдавать информацию фронтам через рест, так, что тут точно должна быть только отдача страницы, а на ней уже скрипт, который будет запрашивать нужные данные

2021-02-06 16:15 UTC, tediik commented on src/main/java/com/jm/online_store/model/Product.java
> +    private String product_picture = "";
давай все же переименуем в product_picture_name, мне кажется, так понятнее, но если ты готов возразить, то можем обсудить.
Да, и дай имя полю в CamelCase, а для базы пропиши сверху @Column и укажи имя для базы

2021-02-06 16:15 UTC, tediik commented on src/main/java/com/jm/online_store/model/TestWrapper.java
> +}
объясни назначение класса, плюс это не Entity, а значит должно лежать в пакете Dto как я понимаю и имя, что это за имя такое и хоть бы пояснение написал тогда к классу :)

2021-02-06 16:15 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/CategoriesServiceImpl.java
> +            if(!(categories.getProducts() == null)){
странный подход, почему не написать != null

2021-02-06 16:15 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/CategoriesServiceImpl.java
> +                for(Product product : categories.getProducts()){
поправь кодстайл во всем методе, не хватает пробелов

2021-02-06 16:15 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/CategoriesServiceImpl.java
> +                    product.setProduct_picture("00.jpg");
мне кажется тут решение через Стримы было бы красивее, но это конечно дело вкуса...

2021-02-06 16:15 UTC, tediik commented on src/main/java/com/jm/online_store/service/interf/ProductService.java
> +import org.springframework.web.multipart.MultipartFile;
в итоге же нигде не используешь импорт

2021-02-06 16:15 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/ProductServiceImpl.java
> +import org.springframework.web.multipart.MultipartFile;
проверь все свои импорты, по моему есть лишние

2021-02-06 16:15 UTC, tediik commented on src/main/resources/static/js/products.js
> +document.getElementById('addBtn').addEventListener('click', handleAddBtn )
верни обратно, не было там лишнего пробела ))))

2021-02-06 16:15 UTC, tediik commented on src/main/resources/static/js/products.js
> + * Функция рендера модального окна Добавить картинку?
почему вопрос в конце?

2021-02-08 12:07 UTC, tediik requested changes

2021-02-08 12:07 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/PictureProductController.java
> +public class PictureProductController {
контроллер доступен только менеджеру надо понимать, поэтому в связи с последними изменениями проекта (Далан добавил Authorization для рест-контроллеров) - надо указать аннотацию Authorization - смотри пример в других контроллерах

2021-02-08 12:07 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ProductsRestController.java
> -            authorizations = { @Authorization(value = "jwtToken") })
проверь весь контроллер, ты затер изменения Далана - надо вернуть authorizations = { @Authorization(value = "jwtToken") })

2021-02-08 12:07 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/ProductController.java
> +        model.addAttribute("product", product);
Не игнорируй замечание:
нет, мы максимально будем сейчас уходить от передачи чего бы то ни было через атрибуты, потому что нам надо отдавать информацию фронтам через рест, так, что тут точно должна быть только отдача страницы, а на ней уже скрипт, который будет запрашивать нужные данные

2021-02-08 12:07 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/ProductController.java
> +import org.springframework.web.bind.annotation.PathVariable;
дублирую: проверь импорты, я вижу, что часть ты не используешь в классе!

2021-02-08 12:07 UTC, tediik commented on src/main/java/com/jm/online_store/model/Product.java
> +    private String product_picture = "";
проигнорил, повторю:
давай все же переименуем в product_picture_name, мне кажется, так понятнее, но если ты готов возразить, то можем обсудить.
Да, и дай имя полю в CamelCase, а для базы пропиши сверху @Column и укажи имя для базы

2021-02-08 12:07 UTC, tediik commented on src/main/java/com/jm/online_store/model/TestWrapper.java
> +}
Повторюсь:
объясни назначение класса, плюс это не Entity, а значит должно лежать в пакете Dto как я понимаю и имя, что это за имя такое и хоть бы пояснение написал тогда к классу :)

2021-02-08 12:07 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/CategoriesServiceImpl.java
> +            if(!(categories.getProducts() == null)){
дублирую: странный подход, почему не написать != null

2021-02-08 12:07 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/CategoriesServiceImpl.java
> +                for(Product product : categories.getProducts()){
кодстайл, не хватает пробела

2021-02-08 12:07 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/CategoriesServiceImpl.java
> +                    product.setProduct_picture("00.jpg");
дублирую:
мне кажется тут решение через Стримы было бы красивее, но это конечно дело вкуса...

2021-02-08 12:07 UTC, tediik commented on src/main/java/com/jm/online_store/service/interf/ProductService.java
> +import org.springframework.web.multipart.MultipartFile;
дублирую: в итоге же нигде не используешь импорт

2021-02-08 13:27 UTC, dmitrykruglov1993 commented on src/main/java/com/jm/online_store/model/TestWrapper.java
> +}
упс, я хотел передать картинку вместе с телом запроса продукта, видел в гугле примеры с переходным классом. Пробовал с ним и закомитил его по ошибке

2021-02-09 11:52 UTC, tediik approved these changes

2021-02-09 11:52 UTC, merged