Восстановление аккаунта с помощью mail/password
tediik/online_store pull request #255
Opened 2021-02-02 06:49 UTC by fRomans

2021-02-02 20:20 UTC, DotsenkoS commented on src/main/java/com/jm/online_store/controller/rest/AllUsersRestController.java
> +                throw new UsernameNotFoundException("msgAlert");
"msgAlert" - кавычки тут лишние

2021-02-02 20:44 UTC, DotsenkoS commented on src/main/java/com/jm/online_store/controller/rest/AllUsersRestController.java
> +            User getUserByPassword = userService.findUserByEmail(email);
getUserByPassword вернее будет назвать getUserByEmail

2021-02-02 21:04 UTC, DotsenkoS commented on src/main/resources/static/js/login.js
> +            document.location.href = "/login";
Лучше тут не перекидывать на login. После сообщения "Проверьте введенные учетные данные" пусть просто закроет окошко с этим сообщением и проверит - может он опечатался

2021-02-02 21:35 UTC, DotsenkoS reviewed
В целом работает, замечания оставила

2021-02-04 11:48 UTC, tediik requested changes

2021-02-04 11:48 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AllUsersRestController.java
>          } catch (UsernameNotFoundException e) {
получилось слишком много кастомной логики для контроллера, вынеси в сервис

2021-02-06 16:43 UTC, tediik requested changes

2021-02-06 16:43 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +
поправь кодстайл, где JavaDoc? Метод что-либо отдающий должен начинаться со слова get

2021-02-06 16:43 UTC, tediik commented on src/main/java/com/jm/online_store/model/dto/RestoreAccountDto.java
> +    }
вот тут прям песня, вообще молодец!!

2021-02-07 18:11 UTC, tediik approved these changes

2021-02-07 18:11 UTC, merged