fix merge conflict in CustomerRestController
tediik/online_store pull request #256
Opened 2021-02-04 21:44 UTC by Dalan2692

2021-02-05 08:17 UTC, tediik requested changes

2021-02-05 08:17 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/SecurityConfig.java
> +//                .sessionCreationPolicy(SessionCreationPolicy.STATELESS);
подожди, почему отключил сессии?

2021-02-05 08:17 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AllUsersRestController.java
> +import io.swagger.annotations.*;
нет, значит не читал внимательно наши доки, мы не используем asterisk import, сделай соответвствующую настройку в Идее

2021-02-05 08:17 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CategoryRestController.java
> +            authorizations = { @Authorization(value = "jwtToken") })
проверь этот класс, насколько я помню, он вроде должен быть доступен всем, даже анониму, и значит нет смысла тут в authorizations = { @Authorization(value = "jwtToken") }

2021-02-05 08:17 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +import io.swagger.annotations.*;
верни импорты обратно

2021-02-05 08:17 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +            authorizations = { @Authorization(value = "jwtToken") })
проверь весь класс, насколько я вижу, часть методов точно должна быть доступна всем!

2021-02-05 08:17 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CommonRestController.java
> +            authorizations = { @Authorization(value = "jwtToken") })
ну этот то точно должен быть доступен без всякой авторизации же!

2021-02-05 08:17 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/LoginRestController.java
> +    @ApiOperation(value = "deletes images",
не понял, почему ты изменил описание тут?

2021-02-05 08:17 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ProductRestController.java
> +            authorizations = { @Authorization(value = "jwtToken") })
опять же проверь ВЕСЬ класс, тут точно часть эндпоинтов должна быть открыта всем!

2021-02-05 08:17 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ReviewRestController.java
> +            authorizations = { @Authorization(value = "jwtToken") })
опять же, вероятно и тут часть методов должны быть доступны в том числе и анониму

2021-02-05 08:17 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/StockRestController.java
> +            authorizations = { @Authorization(value = "jwtToken") })
не помню, есть ли отдельный контроллер для отображения на главной всех Акций, вероятно это как раз этот метод, а значит он тоже должен быть доступен для всех

2021-02-05 08:17 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/admin/AdminRestController.java
> +import io.swagger.annotations.*;
опять не то, верни обратно

2021-02-05 08:17 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +import io.swagger.annotations.*;
поправь

2021-02-05 08:17 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerNewsRestController.java
> +import io.swagger.annotations.*;
поправь

2021-02-05 08:17 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerRestController.java
> +import io.swagger.annotations.*;
поправь

2021-02-05 08:17 UTC, tediik commented on src/main/resources/application.yml
> +    password: prosto4ok
воууу!! ))) поаккуратнее с этим! Всегда проверяй что именно ты отправляешь в коммит! Верни нам наши значения!

2021-02-05 08:17 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ProductsRestController.java
> +import io.swagger.annotations.*;
поправь

2021-02-05 09:07 UTC, Dalan2692 commented on src/main/java/com/jm/online_store/config/security/SecurityConfig.java
> +//                .sessionCreationPolicy(SessionCreationPolicy.STATELESS);
Сессия в проекте не была отключена. Я дописал то что сверху когда тестировал , забыл убрать

2021-02-05 09:39 UTC, Dalan2692 commented on src/main/resources/application.yml
> +    password: prosto4ok
аааа) какая лажа

2021-02-05 09:47 UTC, Dalan2692 commented on src/main/java/com/jm/online_store/controller/rest/AllUsersRestController.java
> +import io.swagger.annotations.*;
ставил 9999 когда базу подключал , сейчас зашел а там 5 стоит..

2021-02-05 10:24 UTC, Dalan2692 commented on src/main/java/com/jm/online_store/controller/rest/CategoryRestController.java
> +            authorizations = { @Authorization(value = "jwtToken") })
убрал

2021-02-05 10:24 UTC, Dalan2692 commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +import io.swagger.annotations.*;
поправил

2021-02-05 10:24 UTC, Dalan2692 commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +            authorizations = { @Authorization(value = "jwtToken") })
поправил

2021-02-05 11:20 UTC, Dalan2692 commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +            authorizations = { @Authorization(value = "jwtToken") })
public ResponseEntity<List<CommentDto>> findAll(@PathVariable Long productId)  - вот этот метод должен быть доступен всем . Поправил .

2021-02-05 11:20 UTC, Dalan2692 commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +import io.swagger.annotations.*;
поправил

2021-02-05 11:20 UTC, Dalan2692 commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerNewsRestController.java
> +import io.swagger.annotations.*;
поправил

2021-02-05 11:20 UTC, Dalan2692 commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerRestController.java
> +import io.swagger.annotations.*;
поправил

2021-02-05 11:20 UTC, Dalan2692 commented on src/main/resources/application.yml
> +    password: prosto4ok
поправил

2021-02-05 11:20 UTC, Dalan2692 commented on src/main/java/com/jm/online_store/controller/rest/manager/ProductsRestController.java
> +import io.swagger.annotations.*;
поправил

2021-02-06 16:29 UTC, tediik requested changes
Не знаю как, но часть замечаний ты пропустил, исправляй

2021-02-06 16:29 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/SecurityConfig.java
> +import org.springframework.security.config.http.SessionCreationPolicy;
лишний импорт

2021-02-06 16:29 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/admin/AdminRestController.java
> +import io.swagger.annotations.*;
Дублирую: опять не то, верни обратно

2021-02-06 16:29 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/StockRestController.java
> +            authorizations = { @Authorization(value = "jwtToken") })
Дублирую: не помню, есть ли отдельный контроллер для отображения на главной всех Акций, вероятно это как раз этот метод, а значит он тоже должен быть доступен для всех

2021-02-06 16:29 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ReviewRestController.java
> +            authorizations = { @Authorization(value = "jwtToken") })
Дублирую: опять же, вероятно и тут часть методов должны быть доступны в том числе и анониму

2021-02-06 16:29 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ProductRestController.java
> +            authorizations = { @Authorization(value = "jwtToken") })
Дублирую: опять же проверь ВЕСЬ класс, тут точно часть эндпоинтов должна быть открыта всем!

2021-02-06 16:29 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/LoginRestController.java
> +    @ApiOperation(value = "deletes images",
ДУблирую: не понял, почему ты изменил описание тут?

2021-02-06 16:29 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CommonRestController.java
> +            authorizations = { @Authorization(value = "jwtToken") })
Дублирую: ну этот то точно должен быть доступен без всякой авторизации же!

2021-02-06 17:48 UTC, tediik approved these changes

2021-02-06 17:48 UTC, merged