Refactoring/user service impl
tediik/online_store pull request #259
Opened 2021-02-06 08:55 UTC by FanilBiktimirov

Добавил JavaDoc-и к методам, существующие сделал более понятными и подробными. Единственное переписать метод метод public User updateUserProfile(User user) не удалось. Перепробовал разные варианты, сталкивался с тем что передает User с id = null и сталкиваюсь с исключением. Переписал метод public boolean isExist(String email). Все тесты прошли

2021-02-06 09:07 UTC, FanilBiktimirov commented
![](https://github.trello.services/images/mini-trello-icon.png) [UserServiceImpl](https://trello.com/c/HFe5YHNB/290-userserviceimpl)

2021-02-09 18:02 UTC, tediik requested changes

2021-02-09 18:02 UTC, tediik commented on src/main/resources/application.yml
> +    password: ec3c54e3047872e2eb2075ec1e333e04aedb0ab4604410209771d31fe5042050
оппа! Косяк.. верни пожалуйста старые настройки подключения к БД, а эти просто закомментируй!

2021-02-09 18:02 UTC, tediik commented on src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +] }
не понимаю, как это вообще попало к тебе??

2021-02-09 18:02 UTC, tediik commented on src/main/java/com/jm/online_store/model/User.java
> +import lombok.AllArgsConstructor;
я думаю, что в итоге ни импорт ни аннотация эта нам тут не нужны

2021-02-09 18:02 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +
лишняя пустая строка

2021-02-09 18:02 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +     *
добавляем пустую строку только когда у нас ооочень большой комментарий, чтобы отделить его от описания параметров и возвращаемого значения

2021-02-09 18:02 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        return user.isPresent();
молодец!!

2021-02-09 18:02 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        log.debug("editUser: {}", editUser.getId());
лучше выводить логин, что у нас по сути email

2021-02-09 18:02 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +
лишняя пустая строка

2021-02-10 11:49 UTC, tediik approved these changes

2021-02-10 11:49 UTC, merged