Feature/logging
tediik/online_store pull request #26
Opened 2020-08-19 19:31 UTC by Yurikru

2020-08-19 19:45 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/config/security/facebook/LoginListener.java
> -    @Autowired
Не понял зачем ты конструктор удаляешь.

2020-08-19 19:47 UTC, Yurikru commented on src/main/java/com/jm/online_store/config/security/facebook/LoginListener.java
> -    @Autowired
Я вместо него ломбок заюзал

2020-08-19 19:49 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +
тут я бы убрал лишние строки

2020-08-19 19:52 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/config/security/facebook/LoginListener.java
> -    @Autowired
чет не понимаю при чем ломбок и userService

2020-08-19 19:53 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/service/impl/MailSenderServiceImpl.java
> +
лишние строки

2020-08-19 19:56 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +
лишняя строка

2020-08-19 19:57 UTC, dshishkaryan commented on src/main/resources/application.properties
> +
тоже наверное лишние строки

2020-08-19 20:08 UTC, Yurikru commented on src/main/resources/application.properties
> +
done

2020-08-19 20:09 UTC, Yurikru commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +
not mine

2020-08-19 20:09 UTC, Yurikru commented on src/main/java/com/jm/online_store/service/impl/MailSenderServiceImpl.java
> +
not mine

2020-08-19 20:09 UTC, Yurikru commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +
Removed

2020-08-19 20:09 UTC, Yurikru commented on src/main/java/com/jm/online_store/config/security/facebook/LoginListener.java
> -    @Autowired
Rolled back to Constructor

2020-08-19 20:24 UTC, tediik requested changes

2020-08-19 20:24 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/facebook/LoginListener.java
> +                log.info("Client registration Id from OAuth token is: " + clientRegistrationId);
это больше отладочная информация, чем info, давай в этом классе заменим все на debug

2020-08-19 20:24 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/AdminController.java
> -
Спасибо ))

2020-08-19 20:24 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/RegistrationController.java
> +            log.debug("BindingResult in registerUserAccount hasErrors " + bindingResult);
Давай везде использовать конструктор, который подразумевает вставку параметров через шаблоны подстановки, переши так везде:
log.debug("BindingResult in registerUserAccount hasErrors: {}", bindingResult);

2020-08-19 20:24 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/MailSenderServiceImpl.java
> +        log.info("Confirmation email was sent from" + username + "to " + emailTo + "with subject " + subject + "and message" + message);
вот, тут прям вообще просится переписать через подстановочные шаблоны!

2020-08-19 20:24 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +            log.debug("Servlet exception from ActivateUser Method " + e);
Через шаблоны подстановки + мне интересно, что у тебя выведется? Как думаешь? Мне кажется у объекта e надо позвать какие-то методы

2020-08-19 20:24 UTC, tediik commented on src/main/resources/application.properties
> +logging.file.name=src/main/log.log
нет, давай ка мы положим его по пути: logs/my.log

2020-08-22 18:41 UTC, tediik requested changes
Куча конфликтов - порешай и исправь 2 моих свежих замечания

2020-08-22 18:41 UTC, tediik commented on src/main/resources/application.properties
> +logging.level.root=info
оставь в debug

2020-08-22 18:41 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/MailSenderServiceImpl.java
> +
Это не важно, майн или не майн - увидел - переделай, тем более, что Гит как раз таки показывает, что эти строчки тобой добавлены.

2020-08-23 19:18 UTC, tediik approved these changes
Отлично

2020-08-23 19:18 UTC, merged