доделал редактирование шаблонов рассылки
tediik/online_store pull request #260
Opened 2021-02-06 12:37 UTC by DenisMalikovKzn

2021-02-06 12:39 UTC, DenisMalikovKzn commented
![](https://github.trello.services/images/mini-trello-icon.png) [Вынести настройки шаблонов рассылок (всех) в кабинет менеджера](https://trello.com/c/NRqXh1SX/266-%D0%B2%D1%8B%D0%BD%D0%B5%D1%81%D1%82%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B8-%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%BE%D0%B2-%D1%80%D0%B0%D1%81%D1%81%D1%8B%D0%BB%D0%BE%D0%BA-%D0%B2%D1%81%D0%B5%D1%85-%D0%B2-%D0%BA%D0%B0%D0%B1%D0%B8%D0%BD%D0%B5%D1%82-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%B0)

2021-02-09 17:38 UTC, tediik requested changes

2021-02-09 17:38 UTC, tediik commented on pom.xml
> +                </executions>
я не уверен, что это ничего не ломает, у меня jar-файл собирается нормально и без этого, так что давай уберем эти изменения

2021-02-09 17:38 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/TemplatesMailingSettingsRestController.java
> +    }
надо добавить еще 1 аннотацию в оба метода, которая включает авторизацию через jwt для сваггера - смотри примеры в других контроллерах, они уже есть в свежем деве
+ опиши к обоим методам стандартный наш JavaDoc

2021-02-09 17:38 UTC, tediik commented on src/main/java/com/jm/online_store/exception/TemplatesMailingSettingsNotFoundException.java
> +        super("Settings not found");
лучше уточнить какие именно Settings не найдены!

2021-02-09 17:38 UTC, tediik commented on src/main/java/com/jm/online_store/model/TemplatesMailingSettings.java
> +@ApiModel(description =  "Сущность TemplatesMailingSettings для настройки задач")
для настройки каких задач??

2021-02-09 17:38 UTC, tediik commented on src/main/java/com/jm/online_store/repository/TemplatesMailingSettingsRepository.java
> +    @Query("UPDATE TemplatesMailingSettings set textValue = :textValue WHERE settingName = :settingName")
Я хочу от тебя ответ почему тут используется @Modifying

2021-02-09 17:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/TemplatesMailingSettingsServiceImpl.java
> +     */
не занимайся смешением языков (прям Вавилон какой-то), пиши уже тогда все на русском

2021-02-09 17:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/TemplatesMailingSettingsServiceImpl.java
> +        }
интересная логика, а этот метод из репозитория не может возвращать например true/false?

2021-02-09 17:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        String templateBody = templatesMailingSettingsService.getSettingByName("reg_new_account").getTextValue();
упадет с NPE как только templatesMailingSettingsService.getSettingByName("reg_new_account") вернет null, а это обязательно когда-нибудь случится, поверь мне, надо добавить проверку

2021-02-09 17:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        String templateBody = templatesMailingSettingsService.getSettingByName("reg_new_account").getTextValue();
упадет с NPE как только templatesMailingSettingsService.getSettingByName("reg_new_account") вернет null, а это обязательно когда-нибудь случится, поверь мне, надо добавить проверку

2021-02-09 17:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +            messageBody = templateBody.replace("@@userEmail@@", userForm.getEmail())
если вдруг userForm.getEmail() вернет null, то опять получим NPE

2021-02-09 17:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        String templateBody = templatesMailingSettingsService.getSettingByName("change_users_mail").getTextValue();
тут тоже самое - возможна NPE

2021-02-09 17:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        String templateBody = templatesMailingSettingsService.getSettingByName("change_users_pass").getTextValue();
и тут NPE

2021-02-09 17:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        String templateBody = templatesMailingSettingsService.getSettingByName("send_confirmation_token_to_reset_password").getTextValue();
тут тоже.. NPE

2021-02-09 17:38 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        String templateBody = templatesMailingSettingsService.getSettingByName("activate_user").getTextValue();
и даже тут!

2021-02-09 17:38 UTC, tediik commented on src/main/resources/static/js/manager-price-change-setting.js
> +        })
эта часть кода постоянно повторяется, я бы вынес в отдельную функцию просто

2021-02-10 10:15 UTC, DenisMalikovKzn commented on pom.xml
> +                </executions>
ок , уже убрал. походу что это  и ломало нормальную сборку джарника

2021-02-10 11:38 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/controller/rest/TemplatesMailingSettingsRestController.java
> +    }
сделал

2021-02-10 11:38 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/exception/TemplatesMailingSettingsNotFoundException.java
> +        super("Settings not found");
сделал

2021-02-10 11:43 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/model/TemplatesMailingSettings.java
> +@ApiModel(description =  "Сущность TemplatesMailingSettings для настройки задач")
исправил

2021-02-10 12:02 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/repository/TemplatesMailingSettingsRepository.java
> +    @Query("UPDATE TemplatesMailingSettings set textValue = :textValue WHERE settingName = :settingName")
Упомяну лишь еще, что запросы могут быть и модифицирующие, для этого к ним добавляется еще аннотация @Modifying

@Modifying
@Query("update Employees e set e.firstName = ?1 where e.employeeId = ?2")
int setFirstnameFor(String firstName, String employeeId);

2021-02-10 12:21 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/repository/TemplatesMailingSettingsRepository.java
> +    @Query("UPDATE TemplatesMailingSettings set textValue = :textValue WHERE settingName = :settingName")
я убрал эту аннотацию,

Добавление аннотации @Modifying указывает, что запрос не для запроса SELECT.



Это вызовет запрос, аннотированный к методу, как обновление запроса, а не его выбор. Поскольку EntityManager может содержать устаревшие объекты после выполнения модифицирующего запроса, мы автоматически очищаем его (подробности см. В JavaDoc of EntityManager.clear()). Это позволит эффективно удалить все незаполненные изменения, все еще ожидающие рассмотрения в EntityManager. Если вы не хотите, чтобы EntityManager был очищен автоматически, вы можете установить @Modifying аннотацию clearAutomatically атрибут false,

2021-02-11 08:58 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/service/impl/TemplatesMailingSettingsServiceImpl.java
> +        }
может . поменял на булен

2021-02-11 11:23 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        String templateBody = templatesMailingSettingsService.getSettingByName("reg_new_account").getTextValue();
сделал

2021-02-11 11:23 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        String templateBody = templatesMailingSettingsService.getSettingByName("reg_new_account").getTextValue();
сделал

2021-02-11 11:24 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +            messageBody = templateBody.replace("@@userEmail@@", userForm.getEmail())
сделал

2021-02-11 11:24 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        String templateBody = templatesMailingSettingsService.getSettingByName("change_users_mail").getTextValue();
сделал

2021-02-11 11:24 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        String templateBody = templatesMailingSettingsService.getSettingByName("change_users_pass").getTextValue();
сделал

2021-02-11 11:24 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        String templateBody = templatesMailingSettingsService.getSettingByName("send_confirmation_token_to_reset_password").getTextValue();
сделал

2021-02-11 11:24 UTC, DenisMalikovKzn commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        String templateBody = templatesMailingSettingsService.getSettingByName("activate_user").getTextValue();
сделал

2021-02-13 16:40 UTC, tediik approved these changes

2021-02-13 16:40 UTC, merged