Bug fix/change password
tediik/online_store pull request #265
Opened 2021-02-12 04:22 UTC by siedhe

2021-02-12 04:24 UTC, siedhe commented
![](https://github.trello.services/images/mini-trello-icon.png) [Проблемы с изменением пароля.](https://trello.com/c/o6PfJHUQ/308-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D1%81-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5%D0%BC-%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%8F)

2021-02-12 04:24 UTC, siedhe commented
![](https://github.trello.services/images/mini-trello-icon.png) [Проблемы с изменением пароля.](https://trello.com/c/o6PfJHUQ/308-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D1%81-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5%D0%BC-%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%8F)

2021-02-16 13:18 UTC, tediik requested changes
Есть конфликты + замечания в связи с задачей Светланы, смотри очень внимательно, не затри изменения из dev!

2021-02-16 13:18 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ProfileRestController.java
> +    public ResponseEntity changePassword(@RequestBody PasswordDto passwords) {
теперь в свежем dev есть огромная работа Светланы, там изменился подход к рестконтроллерам, стал более правильным и четким, тебе надо посмотреть ее изменения (например AdminRestController) и отрефакторить свои контроллеры аналогичным образом - сейчас мы из всех контроллеров что либо возвращаем причем теле специальной сущности (DTO) созданной для ответа с полями success, data и error если нужно, разберись.

2021-02-16 13:18 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +        return new ResponseEntity<>("Ok", HttpStatus.OK);
теперь в свежем dev есть огромная работа Светланы, там изменился подход к рестконтроллерам, стал более правильным и четким, тебе надо посмотреть ее изменения (например AdminRestController) и отрефакторить свои контроллеры аналогичным образом - сейчас мы из всех контроллеров что либо возвращаем причем теле специальной сущности (DTO) созданной для ответа с полями success, data и error если нужно, разберись.

В этом контроллере у тебя есть конфликты! Будь аккуратен при их решении, не затри изменения из дева!
После мерджа и решения конфликтов, обязательно все перепроверь

2021-02-16 15:47 UTC, tediik approved these changes

2021-02-16 15:47 UTC, merged