Feature/address store
tediik/online_store pull request #267
Opened 2021-02-17 05:58 UTC by siedhe

2021-02-18 08:17 UTC, siedhe commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить возможность в кабинете Менеджера работать с адресами магазинов - все CRUD операции](https://trello.com/c/GLMrDnmG/311-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%B2-%D0%BA%D0%B0%D0%B1%D0%B8%D0%BD%D0%B5%D1%82%D0%B5-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%B0-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D1%82%D1%8C-%D1%81-%D0%B0%D0%B4%D1%80%D0%B5%D1%81%D0%B0%D0%BC%D0%B8-%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%D0%BE%D0%B2-%D0%B2%D1%81%D0%B5-crud-%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8)

2021-02-24 16:57 UTC, BuravtsevaEkaterina commented on src/main/resources/templates/manager-page.html
> +                <a class="btn btn-outline-primary" href="/manager/shops">Адреса магазинов</a>
Вкладка "Адреса магазинов" не отображается на других страницах, в частности - на страницах Отчеты, Рассылка... Наверно, нужно добавить)

2021-02-24 16:57 UTC, BuravtsevaEkaterina commented on src/main/resources/templates/manager-shops.html
> +                            <!--New user-->
user поменять на address

2021-02-24 16:57 UTC, BuravtsevaEkaterina commented on src/main/resources/templates/manager-shops.html
> +                                    </form>
нет кнопки submit. Новый адрес не добавляется

2021-02-24 17:42 UTC, siedhe commented on src/main/resources/templates/manager-page.html
> +                <a class="btn btn-outline-primary" href="/manager/shops">Адреса магазинов</a>
Насколько мне известно, карточка, касаемо боковой панели в кабинете менеджера в данный момент находится в работе: https://trello.com/c/AlrzFOrU/253-%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D1%81%D1%82%D0%B8-%D0%B2-%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA-%D0%BA%D0%B0%D0%B1%D0%B8%D0%BD%D0%B5%D1%82-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%B0-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%81-%D0%BD%D0%BE%D1%80%D0%BC%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%BC-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5%D0%BC-%D0%BB%D0%B5%D0%B2%D0%BE%D0%B3%D0%BE-%D0%BC%D0%B5%D0%BD%D1%8E-%D0%B2%D0%BE-%D0%B2%D1%81%D0%B5%D1%85-%D0%BF%D1%83%D0%BD%D0%BA%D1%82%D0%B0%D1%85-%D0%B8-%D1%83%D0%B1%D1%80%D0%B0%D1%82%D1%8C-%D0%BB%D0%B8%D1%88%D0%BD%D0%B8%D0%B9-%D0%BA%D0%BE%D0%B4.

2021-02-24 17:43 UTC, siedhe commented on src/main/resources/templates/manager-shops.html
> +                            <!--New user-->
Исправил подобные моменты.

2021-02-24 17:43 UTC, siedhe commented on src/main/resources/templates/manager-shops.html
> +                                    </form>
Вернул кнопку.

2021-02-24 18:53 UTC, tediik requested changes

2021-02-24 18:53 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AddressRestController.java
> +     * Контроллер для отображения адресов всех активных магазинов
метод а не контроллер, поправь во всем классе, пожалуйста

2021-02-24 18:53 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AddressRestController.java
> +     * @return ResponseEntity<ResponseDto<Address>>(ResponseDto, HttpStatus) {@link ResponseEntity}
тут и в других методах - несоответствие типа возвращаемого значения реальному, в реальности тут у тебя:
ResponseEntity<ResponseDto<List<Address>>> Список адресов, поправь во ВСЕХ методах контроллера

2021-02-24 18:53 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AddressRestController.java
> +        List<Address> allAddress = addressService.findAllShops();
лишняя переменная, пакуй сразу в return

2021-02-24 18:53 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AddressRestController.java
> +     * Контроллер для отображения адреса пользователя
и тут получается не адреса, а адресов, раз мы сет возвращаем

2021-02-24 18:53 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AddressRestController.java
> +     * @param address {@link Address}
* @param address {@link Address} - адрес пользователя
Проверь во всем классе, чтобы по 10 раз не переделать по моим замечаниям - везде должны быть комментарии к входным параметрам и к возвращаемому значению

2021-02-24 18:53 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerAddressRestController.java
> +     * Контроллер для отображения адресов всех магазинов
не контроллер, а метод, поправь во всем классе

2021-02-24 18:53 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AddressRestController.java
> +    public ResponseEntity<ResponseDto<Address>> addAddressToUser(@RequestBody Address address) {
посмотри в других контроллерах - надо еще для сваггера прописать, что можно по токену иметь доступ в данном случае для авторизованных

2021-02-24 18:53 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerAddressRestController.java
> +            return new ResponseEntity<>(new ResponseDto<>(false, "Address not found"), HttpStatus.NOT_FOUND);
сделай как в других контроллерах сейчас есть - бросай exception вместо:
return new ResponseEntity<>(new ResponseDto<>(false, "Address not found"), HttpStatus.NOT_FOUND);
Если готового класса исключения нет - делаешь свой по аналогии с существующими, далее у тебя 
@ExceptionHandler перехватывает НУЖНЫЕ exceptions и возвращает нужные ответы

Поправь во ВСЕМ своем контроллере - для единообразия

2021-02-24 18:53 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerAddressRestController.java
> +        return new ResponseEntity<>(new ResponseDto<>(true, address), HttpStatus.OK);
ужасный код, если findAddressById возвращает Optional, то есть нормальные методы для работы с ним, но вызывать одно и то же 2 раза, даже не смотря на кэширование результата запроса - это плохой подход

2021-02-24 18:53 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerAddressRestController.java
> +        return new ResponseEntity<>(new ResponseDto<>(true, address), HttpStatus.OK);
Я бы вообще оставил бы тут только addressService.deleteById(id); а все остальное пусть сервис проверяет, есть оно в БД или нет или там exception летит и т.д.

2021-02-24 18:53 UTC, tediik commented on src/main/java/com/jm/online_store/model/Address.java
> +    private String district;
округ нам вероятно не нужен, а вот квартира для адреса покупателя вполне нужна - предлагаю ее вернуть

2021-02-24 18:53 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/AddressServiceImpl.java
> +     * @param idAddress {@link Long}
вместо линка на Long, лучше бы написал - идентификатор адреса

2021-02-24 18:53 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/AddressServiceImpl.java
> +     *
кому пустая строчка? где описание возвращаемого типа?

2021-02-24 18:53 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/AddressServiceImpl.java
> +     * Метод для удаления адреса по id.
где описание принимаемого параметра?

2021-02-24 18:53 UTC, tediik commented on src/main/resources/static/js/manager-shops.js
> +        timeout: 3000,
это еще зачем????

2021-02-24 18:53 UTC, tediik commented on src/main/resources/static/js/manager-shops.js
> +})
оставь коммент в коде для чего этот код, я например не понял

2021-02-24 20:24 UTC, tediik requested changes

2021-02-24 20:24 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerAddressRestController.java
> +        return new ResponseEntity<>(new ResponseDto<>(true, address), HttpStatus.OK);
Вынеси логику проверки в сервис

2021-02-24 20:24 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerAddressRestController.java
> +        return new ResponseEntity<>(new ResponseDto<>(true, address), HttpStatus.OK);
Повторно
ужасный код, если findAddressById возвращает Optional, то есть нормальные методы для работы с ним, но вызывать одно и то же 2 раза, даже не смотря на кэширование результата запроса - это плохой подход

2021-02-24 20:24 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerAddressRestController.java
> +            return new ResponseEntity<>(new ResponseDto<>(false, "Address not found"), HttpStatus.NOT_FOUND);
Повторно
сделай как в других контроллерах сейчас есть - бросай exception вместо:
return new ResponseEntity<>(new ResponseDto<>(false, "Address not found"), HttpStatus.NOT_FOUND);
Если готового класса исключения нет - делаешь свой по аналогии с существующими, далее у тебя
@ExceptionHandler перехватывает НУЖНЫЕ exceptions и возвращает нужные ответы

Поправь во ВСЕМ своем контроллере - для единообразия

2021-02-24 20:24 UTC, tediik commented on src/main/java/com/jm/online_store/model/Address.java
> +    private String district;
Повторно:
округ нам вероятно не нужен, а вот квартира для адреса покупателя вполне нужна - предлагаю ее вернуть

2021-02-24 20:24 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/AddressServiceImpl.java
> +     * Метод для удаления адреса по id.
Повторно:
где описание принимаемого параметра метода?

2021-02-25 09:14 UTC, tediik requested changes

2021-02-25 09:14 UTC, tediik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +        Address address4 = new Address("Тамбовская область", "Тамбов", "Запорожская", "12", "2", "420080", false);
ну логично же, что у магазина вряд ли будет квартира присутствовать в адресе, ну сделай ты 2 разных конструктора, ну жалко тебе что ли?

2021-02-25 09:14 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerAddressRestController.java
> +        Address address = addressService.findAddressById(id).get();
просто get()? без проверки на пустое значение? Т.е. фронт попросит нас адрес по его идентификатору, а мы если его не найдем, вернем просто статус ОК и ответ null??
Плохо.. Смотри методы для работы с Optional, их куча: ifPresent(), isPresent(), orElse(), orElseGet(), orElseThrow и т.д.

2021-02-25 09:20 UTC, siedhe commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerAddressRestController.java
> +        Address address = addressService.findAddressById(id).get();
Я просто перенес проверку в сервис,
![image](https://user-images.githubusercontent.com/68646015/109131364-cb3a5f00-7763-11eb-8254-d34e72e41a68.png)

2021-02-25 09:21 UTC, siedhe commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerAddressRestController.java
> +        Address address = addressService.findAddressById(id).get();
Соответственно, если идентификатора нет, то ответ такой.
![image](https://user-images.githubusercontent.com/68646015/109131614-0472cf00-7764-11eb-9f2a-f61effd6cf33.png)

2021-02-25 11:35 UTC, tediik approved these changes

2021-02-25 11:35 UTC, merged