add link to main page to success registration email
tediik/online_store pull request #270
Opened 2021-02-19 19:04 UTC by BuravtsevaEkaterina

2021-02-19 19:06 UTC, BuravtsevaEkaterina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Регистрация юзера нового](https://trello.com/c/hMgHlQ5G/313-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D1%8E%D0%B7%D0%B5%D1%80%D0%B0-%D0%BD%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE)

2021-02-20 16:09 UTC, tediik requested changes

2021-02-20 16:09 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +                        .replace("@@url@@", "<a href='https://jm-online-store.herokuapp.com/'>online_store</a>");
Катя, все круто, но надо получать это из того же application.yml потому что сегодня 1 url, завтра другой, лазить по коду и искать где эта настройка - неправильно, сделай, чтобы подгружал из файла настроек.

2021-02-20 18:24 UTC, BuravtsevaEkaterina commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +                        .replace("@@url@@", "<a href='https://jm-online-store.herokuapp.com/'>online_store</a>");
Поправила. 
С коммитами произошло какое-то недоразумение... Надеюсь, в следующий раз будет нормально)

2021-02-20 18:38 UTC, tediik approved these changes

2021-02-20 18:38 UTC, merged