feature/BlockUserAccountFromAdminPage
tediik/online_store pull request #273
Opened 2021-02-21 08:10 UTC by FanilBiktimirov

2021-02-21 09:30 UTC, FanilBiktimirov commented
![](https://github.trello.services/images/mini-trello-icon.png) [В кабинете Админа добавить возможность Блокировки](https://trello.com/c/TjpoDplO/275-%D0%B2-%D0%BA%D0%B0%D0%B1%D0%B8%D0%BD%D0%B5%D1%82%D0%B5-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B0-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B8)

2021-02-24 19:12 UTC, tediik requested changes

2021-02-24 19:12 UTC, tediik commented on src/main/resources/templates/login.html
> +                            <strong>Ваш акаунт заблокирован.</strong>
код этот и выше где удаление надо менять - мы теперь не полагаемся на работу шаблонизатора, все общение с сервером только через rest-api, так что ты в контроллере больше не передаешь param.accountBanned, а запрашиваешь это из js-кода запросом AJAX

2021-02-24 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        return userRepository.save(user);
поправь и в JavaDoc тогда

2021-02-24 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        if (addressFromDB.isEmpty()) {
зачетно ))

2021-02-24 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/model/dto/UserDto.java
> +    private String password;
мы вроде специально уходили от того, чтобы передавать даже в шифрованном виде пароль на фронт, зачем понадобился?

2021-02-24 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/config/handler/LoginFailureHandler.java
> +            response.setStatus(HttpStatus.LOCKED.value());
зачем? мы же не делаем Expired! Мы делаем блокировку, кода выше в предыдущем условии по моему мнению вполне достаточно

2021-02-24 19:32 UTC, FanilBiktimirov commented on src/main/java/com/jm/online_store/config/handler/LoginFailureHandler.java
> +            response.setStatus(HttpStatus.LOCKED.value());
По моему скромному мнению, не достаточно. Мы делаем редирект "/login?accountBanned=true", на основе этого шаблонизатор Thymeleaf видя значение accountBanned = true кидает уже алерт о том что аккаунт заблокирован. Я не увидел что Thymeleaf берет эти значения из контроллеров

2021-02-24 19:36 UTC, FanilBiktimirov commented on src/main/java/com/jm/online_store/config/handler/LoginFailureHandler.java
> +            response.setStatus(HttpStatus.LOCKED.value());
С моментом с Expired я согласен, что-то не то. Но дело в том что Locked уже используется, и как считаю не совсем по назначению и вместо него как-раз таки должен использоваться Expired

2021-03-04 07:29 UTC, closed without merging