refactoring rest controllers
tediik/online_store pull request #275
Opened 2021-02-25 14:32 UTC by saiber342

2021-03-01 13:43 UTC, Dalan2692 commented on src/main/java/com/jm/online_store/controller/rest/NewsRestController.java
> +        return ResponseEntity.ok(news);
методы возвращали ResponseDto<СущностьDto>

2021-03-01 13:43 UTC, Dalan2692 commented on src/main/java/com/jm/online_store/controller/rest/NewsRestController.java
> +        return new ResponseEntity<News>(newsService.findById(id), HttpStatus.OK);
методы возвращали ResponseDto<СущностьDto>

2021-03-04 15:38 UTC, tediik requested changes

2021-03-04 15:38 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/NewsRestController.java
> +        return ResponseEntity.ok(news);
посмотри внимательно на существующие контроллеры, у нас теперь единый формат ответа, обертка ResponseDto - возвращать надо именно ее

2021-03-04 15:38 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/NewsRestController.java
> +        return new ResponseEntity<>(newsService.findById(id), HttpStatus.OK);
посмотри внимательно на существующие контроллеры, у нас теперь единый формат ответа, обертка ResponseDto - возвращать надо именно ее

2021-03-04 15:38 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/SearchRestController.java
> +
лишняя 1 строчка, некрасиво!

2021-03-04 15:38 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/SearchRestController.java
> +
эээээээ.... а логика? Вернуть обратно строчку, которую получил в параметрах????

2021-03-04 15:38 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ServiceCenterRestController.java
> +}
посмотри, у нас уже есть такой метод в других рест-контроллерах, этот будет точно третим, если не 4ым, не надо так!

2021-03-04 15:38 UTC, tediik commented on src/main/resources/static/js/login.js
> +// document.getElementById('linkForOpenRestoreModal').addEventListener('click', showModalForRestore)
почему закомментировал??

2021-03-04 15:38 UTC, tediik commented on src/main/resources/static/js/login.js
> +    then(url => document.location.href = url)
а это зачем раскоментил?

2021-03-04 15:38 UTC, tediik commented on src/main/resources/static/js/news-details.js
> +
прибери кодстайл, убери эти пустые строки где не нужны

2021-03-04 15:38 UTC, tediik commented on src/main/resources/static/js/news-page.js
> +        console.log(listOfNews[key].title);
логирование думаю можно убрать это

2021-03-04 15:38 UTC, tediik commented on src/main/resources/static/js/news-page.js
> +    }, 100)
почему пришлось делать таймаут?

2021-03-04 16:46 UTC, saiber342 commented on src/main/resources/static/js/login.js
> +// document.getElementById('linkForOpenRestoreModal').addEventListener('click', showModalForRestore)
Потому что эта строчка багует все функции, которые идут после нее и поэтому не работали кнопки авторизации через соц.сети. Эта функция для второй кнопки восстановления пароля, которую убрали(она там в login.html закомментирована).

2021-03-04 16:47 UTC, saiber342 commented on src/main/resources/static/js/login.js
> +// document.getElementById('linkForOpenRestoreModal').addEventListener('click', showModalForRestore)
Это правда не относится  к этому заданию, но я решил заодно добавить и это в коммит.

2021-03-04 16:47 UTC, saiber342 commented on src/main/resources/static/js/login.js
> +// document.getElementById('linkForOpenRestoreModal').addEventListener('click', showModalForRestore)
Все равно чинить пршилось бы

2021-03-04 16:50 UTC, saiber342 commented on src/main/resources/static/js/news-page.js
> +    }, 100)
Прост пробовал разные варианты вызова)

2021-03-04 16:56 UTC, saiber342 commented on src/main/java/com/jm/online_store/controller/rest/SearchRestController.java
> +
А вот здесь же получается что этот контроллер просто должен возвращать строку, которую мы вводим в окне поиска товара, а потом эта строка передается в параметры функции, которая использует методы для поиска товара по названию и описанию(2 метода разных), но каждый из них осуществляет поиск с помощью этой самой строки.
Если оно так и должно работать, то я тогда не понимаю чего здесь не хватает?

2021-03-04 18:56 UTC, saiber342 commented on src/main/java/com/jm/online_store/controller/rest/ServiceCenterRestController.java
> +}
А что мне в нем изменить тогда? Там же просто нужна инфа о юзере

2021-03-11 12:59 UTC, saiber342 commented on src/main/java/com/jm/online_store/controller/rest/NewsRestController.java
> +        return ResponseEntity.ok(news);
Там оказалось, что формат ответа все же нужно было менять на стороне фронта, а не бэка

2021-03-11 13:01 UTC, saiber342 commented on src/main/java/com/jm/online_store/controller/rest/ServiceCenterRestController.java
> +}
Если у этого контроллера всего один метод, который и то не нужен, то я решил его вообще удалить, потому что там метод для профиля, как ты и сказал, можно вызывать через другой контроллер
Информация о юзере там возвращается через ProfileRestController

2021-03-11 15:38 UTC, tediik approved these changes

2021-03-11 18:45 UTC, tediik approved these changes

2021-03-11 18:45 UTC, merged