refactor/users_table
tediik/online_store pull request #277
Opened 2021-03-01 00:10 UTC by Dalan2692

2021-03-01 15:12 UTC, FanilBiktimirov commented on src/main/java/com/jm/online_store/controller/rest/AddressRestController.java
>      }
Наверное лучше оставить как было, мы же специально переписывали рест-контроллеры чтобы они возвращали ResponseDto с success true/false

2021-03-01 15:12 UTC, FanilBiktimirov commented on src/main/java/com/jm/online_store/controller/rest/admin/AdminRestController.java
> +
Хорошее решение))

2021-03-02 12:43 UTC, FanilBiktimirov approved these changes
Замечании нет

2021-03-03 21:21 UTC, tediik requested changes

2021-03-03 21:21 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/CustomerServiceImpl.java
> +    }
можно точно красивее - переделай, не должно быть повторяющихся кусков кода, есть красивое решение

2021-03-03 21:21 UTC, tediik commented on src/main/java/com/jm/online_store/model/Employee.java
> +
лишняя строчка, некрасиво

2021-03-03 21:21 UTC, tediik commented on src/main/java/com/jm/online_store/model/Customer.java
> +
лишняя строчка, некрасиво

2021-03-03 21:21 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/EmployeeServiceImpl.java
> +
лишняя строчка, некрасиво

2021-03-03 21:21 UTC, tediik commented on src/main/resources/static/js/admin-page-render.js
> +    console.log(users)
давай это уберем

2021-03-12 04:25 UTC, Dalan2692 commented on src/main/java/com/jm/online_store/service/impl/CustomerServiceImpl.java
> +    }
Метод изначально я взял из UserServiceImpl. Посмотрел сейчас внимательно и решил разбить на 3 , каждый делает свое дело. private boolean customerAddressAlreadyExists заменил метод contains() , так как были с ним проблемы. Сейчас тут сравнивает игнорируя регистр, null и пробелы проверять не стал , думаю это нужно делать в контроллере, а еще лучше и на фронте. Кода стало чуток больше , но понятней.

2021-03-20 17:55 UTC, tediik approved these changes

2021-03-20 17:55 UTC, merged