for review
tediik/online_store pull request #278
Opened 2021-03-01 09:58 UTC by FanilBiktimirov

Переписал рест контроллеры:
AddressRestController
AllUsersRestController
BadWordsRestController
BasketRestController
CategoryRestController
CommentRestController
CommonRestController
CommonSettingsRestController
ExceptionController
FavouritesGoodsRestController
FavouritesGroupRestController
FeedbackRestController
GlobalSharedNewsRestController
GlobalSharedStockRestController

Переписал по принципу POST,PUT,GET возвращают сущность, a DELETE строку или boolean.

Также переписал некоторые методы в сервисе которые ничего не возвращали (void), теперь возвращают что-либо.

2021-03-01 13:40 UTC, FanilBiktimirov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Рефакторинг Рест-апи, возвращать всегда JSON! 3 часть](https://trello.com/c/BIISDPyW/302-%D1%80%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%BD%D0%B3-%D1%80%D0%B5%D1%81%D1%82-%D0%B0%D0%BF%D0%B8-%D0%B2%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%89%D0%B0%D1%82%D1%8C-%D0%B2%D1%81%D0%B5%D0%B3%D0%B4%D0%B0-json-3-%D1%87%D0%B0%D1%81%D1%82%D1%8C)

2021-03-13 22:07 UTC, Dalan2692 commented on src/main/java/com/jm/online_store/controller/rest/CommonRestController.java
> +        //return ResponseEntity.ok(commonSettingsService.getSettingByName("store_name").getTextValue());
комменты

2021-03-17 19:59 UTC, tediik requested changes
+ опять есть конфликты

2021-03-17 19:59 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/BadWordsRestController.java
> +        }
так у тебя же вроде есть внизу  @ExceptionHandler(BadWordsNotFoundException.class) - зачем тогда еще тут городить перехват ошибки?? Разберись

2021-03-17 19:59 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/BasketRestController.java
> +
лишняя строчка

2021-03-17 19:59 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/BasketRestController.java
> +            return new ResponseEntity<>(new ResponseDto<>(false, "User not found"), HttpStatus.NOT_FOUND);
давай в этом контроллере тоже вынесем обработку всех exceptions во всех методах в единый метод с аннотацией  @ExceptionHandler

2021-03-17 19:59 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ExceptionController.java
> +    public ResponseEntity<ResponseDto<Object>> handleNotFoundExceptions(RuntimeException ex, WebRequest request) {
а зачем параметризовать Object-ом? Это же тож самое, что и сырые типы!?

2021-03-17 19:59 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/BasketServiceImpl.java
> +                   //return;
не нужно - убирай значит

2021-03-18 19:08 UTC, tediik approved these changes

2021-03-18 19:08 UTC, merged