updated post date assignment by default and edit date
tediik/online_store pull request #28
Opened 2020-08-20 09:44 UTC by sirajDeveloper

updated post date assignment by default and edit date

2020-08-20 11:04 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
>      @PostMapping("/news/update")
Я бы поменял PostMapping на PutMapping. Для изменений вроде как Put используется.

2020-08-20 11:05 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
> +        if(news.getPostingDate() == null || news.getPostingDate().isBefore(LocalDateTime.now())) {
Мне кажется при изменении не надо подставлять сегодняшнюю дату. Это же дата публикации, а не дата изменений.

2020-08-20 15:59 UTC, sirajDeveloper commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
>      @PostMapping("/news/update")
Да, но пут не работает с отправкой данных из html формы, из формы можно отправлять только get/post. Если отправлять c помощью ajax или fetch тогда да пут будет работать. Так что юзаю post))

2020-08-20 16:05 UTC, sirajDeveloper commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
> +        if(news.getPostingDate() == null || news.getPostingDate().isBefore(LocalDateTime.now())) {
Ну смотри, когда мы делаем апдейт новости, у нас сохранится дата когда новость обновилась.  Ты предлагаешь оставить возможность выставлять дату прошедшего времени? Для чего это может понадобится?

2020-08-20 16:08 UTC, sirajDeveloper commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
> +        if(news.getPostingDate() == null || news.getPostingDate().isBefore(LocalDateTime.now())) {
Ну я к тому что мы же редактируем новость и получается публикуем ее заново.

2020-08-20 16:11 UTC, sirajDeveloper commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
> +        if(news.getPostingDate() == null || news.getPostingDate().isBefore(LocalDateTime.now())) {
На самом деле данная бизнес логика из серии пожеланий заказчика)

2020-08-20 16:22 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
>      @PostMapping("/news/update")
Этого ньюанса про put и форму не знал. Но на предпроектной я кажется отменял действия формы и в js прописывал обработку кнопки. Как лучше наверное Эдуард рассудит)

2020-08-20 16:24 UTC, ghost commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
> +        if(news.getPostingDate() == null || news.getPostingDate().isBefore(LocalDateTime.now())) {
Согласен. Но на всякий случай комент оставил. Всякое бывает, может так не задумывалось)

2020-08-20 17:29 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
> +        if(news.getPostingDate() == null || news.getPostingDate().isBefore(LocalDateTime.now())) {
Тогда может переименовать 
Дата публикации: 19-08-2020 16:54
на 
Дата последних изменений?

2020-08-20 20:05 UTC, tediik requested changes

2020-08-20 20:05 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
>      @PostMapping("/news/update")
Давайте ка все действия по созданию, редактированию и удалению - в рест контроллер, ато негоже - удалил новость, а страница перезагружается. Тогда действительно тут и PUT будет к месту

2020-08-20 20:05 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
> +        if(news.getPostingDate() == null || news.getPostingDate().isBefore(LocalDateTime.now())) {
А давайте хранить обе даты - публикации и последнего изменения

2020-08-24 15:20 UTC, tediik approved these changes

2020-08-24 15:20 UTC, merged