refactor/manager_page
tediik/online_store pull request #280
Opened 2021-03-02 23:17 UTC by DotsenkoS

Кабинет менеджера приведен к виду кабинета Админа. 
Поправлен код в js в соответствующих функциях. 
Доступ для страниц менеджера (/manager/**", /api/manager/**) теперь есть только у менеджера
В нескольких местах поправлен формат ответа с просто статуса на ResponseDto
В ProductsRestController поправлена ошибка в методе filterByCategoryAndSort

2021-03-03 10:26 UTC, fponin commented on src/main/resources/templates/manager-page.html
> +        <div class="col-sm-8 text-left">
пока правой навигации нет, может 10 поставить(у админа 10)?
<div class="col-sm-10 text-left">

2021-03-03 15:02 UTC, fponin reviewed
Все хорошо.

2021-03-03 16:39 UTC, fponin reviewed
Все отлично

2021-03-03 20:23 UTC, tediik requested changes

2021-03-03 20:23 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerTopicsCategoryRestController.java
> +    public ResponseEntity<ResponseDto<List<TopicsCategory>>> readAllTopicsCategories() {
слушай, а тут точно надо было убирать TopicsCategoryDto? Проверь

2021-03-03 20:23 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
> +        model.addAttribute("listCategories", categoriesService.getCategoriesWithoutParentCategory().stream().map(Categories::getCategory).collect(Collectors.toList()));
трабла в том, что это никак не увидят фронты, эту инфу должен отдавать рест-эндпоинт и мы должны получать ее через ajax-запрос, т.е. если ты берешься переделать, то тогда надо делать сразу норм

2021-03-03 20:23 UTC, tediik commented on src/main/resources/templates/manager-page.html
> +                <!--ВКЛАДКА РАССЫЛКИ  -->
Я понимаю, что там везде сделано так же, как думаешь, может стоило вынести вкладки в отдельные фрагменты, чтобы просто было проще вносить правки в файл, не?

2021-03-04 08:46 UTC, DotsenkoS commented on src/main/java/com/jm/online_store/controller/rest/manager/ManagerTopicsCategoryRestController.java
> +    public ResponseEntity<ResponseDto<List<TopicsCategory>>> readAllTopicsCategories() {
Да, тут точно - у нас в manager-categories-setting.js в функциях makeActualCategoryBody и makeArchiveCategoryBody нужны данные поля topics, которое есть в  TopicsCategory, но нет TopicsCategoryDto
Это было изменено, когда в классе ManagerTopicsCategoryRestController возвращаемое значение меняли на  ResponseDto. Тогда фронт не исправляли - возможно недопроверили что именно будет нужно на выходе, не могу сказать. В общем, с TopicsCategoryDto сейчас не будет работать, нужен именно TopicsCategoryДа, тут точно - у нас в manager-categories-setting.js в функциях makeActualCategoryBody и makeArchiveCategoryBody нужны данные поля topics, которое есть в  TopicsCategory, но нет TopicsCategoryDto
Это было изменено, когда в классе ManagerTopicsCategoryRestController возвращаемое значение меняли на  ResponseDto. Тогда фронт не исправляли - возможно недопроверили что именно будет нужно на выходе, не могу сказать. В общем, с TopicsCategoryDto сейчас не будет работать, нужен именно TopicsCategory

2021-03-04 15:19 UTC, DotsenkoS commented on src/main/resources/templates/manager-page.html
> +                <!--ВКЛАДКА РАССЫЛКИ  -->
Под конец это стало настоящей дилеммой, до сих пор не знаю как было бы лучше

2021-03-04 15:19 UTC, DotsenkoS commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
> +        model.addAttribute("listCategories", categoriesService.getCategoriesWithoutParentCategory().stream().map(Categories::getCategory).collect(Collectors.toList()));
Исправила

2021-03-04 15:26 UTC, tediik approved these changes

2021-03-04 15:26 UTC, merged