Refactor/simple controllers
tediik/online_store pull request #281
Opened 2021-03-03 13:41 UTC by BuravtsevaEkaterina

Удаление thymeleaf из 
AdminController
AuthorityController
CustomerController
GlobalStocksController
ManagerController
ProductController

2021-03-03 13:42 UTC, BuravtsevaEkaterina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Переделка обычных контроллеров - не отдаем больше никакие данные в thymeleaf, все только через рест-апи](https://trello.com/c/xNJwA1Dn/264-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%BA%D0%B0-%D0%BE%D0%B1%D1%8B%D1%87%D0%BD%D1%8B%D1%85-%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D0%BB%D0%B5%D1%80%D0%BE%D0%B2-%D0%BD%D0%B5-%D0%BE%D1%82%D0%B4%D0%B0%D0%B5%D0%BC-%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%B5-%D0%BD%D0%B8%D0%BA%D0%B0%D0%BA%D0%B8%D0%B5-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D0%B2-thymeleaf-%D0%B2%D1%81%D0%B5-%D1%82%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-%D1%80%D0%B5%D1%81%D1%82-%D0%B0%D0%BF%D0%B8)

2021-03-04 13:57 UTC, DotsenkoS commented on src/main/java/com/jm/online_store/service/interf/CustomerService.java
> +import org.springframework.transaction.annotation.Transactional;
Тут вроде не нужен этот импорт

2021-03-04 14:26 UTC, DotsenkoS commented on src/main/resources/static/js/profile-admin-manager-service.js
>          .then((res) => res.json())
data можно получить сразу после json

2021-03-04 17:54 UTC, tediik requested changes

2021-03-04 17:54 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ImageRestController.java
> +        return ResponseEntity.ok(userService.getCurrentLoggedInUser().getProfilePicture());
заверни в нашу обертку

2021-03-04 17:54 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ProfileRestController.java
> +    public ResponseEntity<ResponseDto<UserDto>> updateProfile(@RequestBody User user) {
вооот! она где проблема то эта! Короче надо поправить, мы тут тоже должны принимать UserDto с нужными полями! А не целиком класс User, представляешь сколько там полей!

2021-03-04 17:54 UTC, tediik commented on src/main/resources/static/js/manager-characteristics.js
> +//         })
если не нужно - может удалим?

2021-03-04 17:54 UTC, tediik commented on src/main/resources/static/js/products-rating.js
> +// }
если не нужно - удаляем??

2021-03-04 17:54 UTC, tediik commented on src/main/resources/static/js/products-rating.js
> +// getCategories()
удаляем?

2021-03-05 09:23 UTC, tediik requested changes

2021-03-05 09:23 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +    public User updateUserDtoProfile(UserDto userDto) {
кто напишет JavaDoc? )))

2021-03-05 09:23 UTC, tediik commented on src/main/resources/static/js/products-rating.js
> +// getCategories()
эта строчка нужна?

2021-03-06 19:21 UTC, tediik approved these changes

2021-03-06 19:21 UTC, merged