Refactor/check size userimage
tediik/online_store pull request #285
Opened 2021-03-08 14:38 UTC by fponin

Добавил handleMaxUploadSizeExceededException

2021-03-08 14:41 UTC, fponin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ограничение размера загружаемой картинки профиля - сделать чтобы брало настройку из application.yml](https://trello.com/c/gCnPY9op/321-%D0%BE%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%80%D0%B0-%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B6%D0%B0%D0%B5%D0%BC%D0%BE%D0%B9-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D0%B8-%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8F-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%87%D1%82%D0%BE%D0%B1%D1%8B-%D0%B1%D1%80%D0%B0%D0%BB%D0%BE-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D1%83-%D0%B8%D0%B7-applicationyml)

2021-03-08 14:41 UTC, fponin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ограничение размера загружаемой картинки профиля - сделать чтобы брало настройку из application.yml](https://trello.com/c/gCnPY9op/321-%D0%BE%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%80%D0%B0-%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B6%D0%B0%D0%B5%D0%BC%D0%BE%D0%B9-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D0%B8-%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8F-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%87%D1%82%D0%BE%D0%B1%D1%8B-%D0%B1%D1%80%D0%B0%D0%BB%D0%BE-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D1%83-%D0%B8%D0%B7-applicationyml)

2021-03-08 14:41 UTC, fponin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ограничение размера загружаемой картинки профиля - сделать чтобы брало настройку из application.yml](https://trello.com/c/gCnPY9op/321-%D0%BE%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%80%D0%B0-%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B6%D0%B0%D0%B5%D0%BC%D0%BE%D0%B9-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D0%B8-%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8F-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%87%D1%82%D0%BE%D0%B1%D1%8B-%D0%B1%D1%80%D0%B0%D0%BB%D0%BE-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D1%83-%D0%B8%D0%B7-applicationyml)

2021-03-08 14:43 UTC, fponin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ограничение размера загружаемой картинки профиля - сделать чтобы брало настройку из application.yml](https://trello.com/c/gCnPY9op/321-%D0%BE%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%80%D0%B0-%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B6%D0%B0%D0%B5%D0%BC%D0%BE%D0%B9-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D0%B8-%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8F-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%87%D1%82%D0%BE%D0%B1%D1%8B-%D0%B1%D1%80%D0%B0%D0%BB%D0%BE-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D1%83-%D0%B8%D0%B7-applicationyml)

2021-03-11 18:52 UTC, tediik requested changes
Непонятный jpg файл убрать из PR
А где строчка spring.servlet.multipart.max-file-size в файле application.yml?

2021-03-11 19:29 UTC, tediik approved these changes

2021-03-11 19:29 UTC, merged