feature/testing_manager_controllers
tediik/online_store pull request #287
Opened 2021-03-10 12:25 UTC by Dalan2692

2021-03-10 12:32 UTC, Dalan2692 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Тестирование отправки почты](https://trello.com/c/38SFWclS/287-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B8-%D0%BF%D0%BE%D1%87%D1%82%D1%8B)

2021-03-16 15:04 UTC, fponin commented on src/main/java/com/jm/online_store/model/News.java
>  @Setter
Если Дату добавил, то @сеттер и @геттер отдельно не нужны.

2021-03-16 15:05 UTC, Dalan2692 commented on src/main/java/com/jm/online_store/model/News.java
>  @Setter
да, уберу , скорее всего копипаст был.

2021-03-16 19:25 UTC, fponin commented on src/test/java/com/jm/online_store/controller/rest/manager/ManagerNewsRestControllerTest.java
> +    }
Стоит ли каждый раз это все инициализировать перед каждым тестом?
Может быть что-то вынести в @BeforeAll?

2021-03-16 19:29 UTC, fponin reviewed
Тесты работают.

2021-03-16 19:29 UTC, Dalan2692 commented on src/test/java/com/jm/online_store/controller/rest/manager/ManagerNewsRestControllerTest.java
> +    }
а ты пробовал с @BeforeAll? я думаю у тебя с текущим тестом будут проблемы...

2021-03-17 20:34 UTC, tediik requested changes
Опять намешал все в 1 пулл реквест, это очень плохая практика, я тебе уже говорил об этом, значит учись делить грамотно изменения по коммитам и потом раскидывать коммиты нужные в правильные отдельные ветки

2021-03-17 20:34 UTC, tediik commented on src/test/java/com/jm/online_store/controller/rest/manager/ProductsRestControllerTest.java
> +import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
честно говоря уже не первое место в тестах, где вдруг используешь астерикс импорт - у нас же принято без них, пробегись по всем тестам и поправь

2021-03-18 19:14 UTC, tediik approved these changes

2021-03-18 19:14 UTC, merged