Feature/customerNotifications
tediik/online_store pull request #288
Opened 2021-03-13 15:17 UTC by BuravtsevaEkaterina

2021-03-13 15:18 UTC, BuravtsevaEkaterina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Уведомления пользователя](https://trello.com/c/Ski417OB/223-%D1%83%D0%B2%D0%B5%D0%B4%D0%BE%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F)

2021-03-14 11:06 UTC, fponin commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerNotificationsRestController.java
> +            customer.setDayOfWeekForStockSend(dayOfWeekForStockSend);
Предлагаю не выделять отдельную переменную под DayOfWeekForStockSend, а получить его сразу в параметре метода

2021-03-14 11:46 UTC, fponin commented on src/main/java/com/jm/online_store/repository/PriceChangeNotificationRepository.java
> + * Repository для действий с сущностью PriceChangeNotifications (уведомления об изменении цены)
Ссылка из JavaDoc - {@link PriceChangeNotifications}

2021-03-14 12:13 UTC, BuravtsevaEkaterina commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerNotificationsRestController.java
> +            customer.setDayOfWeekForStockSend(dayOfWeekForStockSend);
Если получать параметром, то null выбрасывает warn и день не изменяется. 
У нас рассылка завязана на день недели (если он не выбран, рассылки нет). Получается, что если переносить в параметр, то нужен еще отдельный эндпоинт на отписку. Не уверена, что есть смысл, если можно просто null передать

2021-03-14 15:25 UTC, fponin commented on src/main/java/com/jm/online_store/service/impl/ProductServiceImpl.java
> +        priceChangeNotificationsService.addPriceChangesNotification(product, oldPrice, newPrice);
Если цена не менялась, то может не надо этого делать?

2021-03-14 15:34 UTC, fponin reviewed
Проверил.

2021-03-14 15:39 UTC, fponin commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerNotificationsRestController.java
> +            customer.setDayOfWeekForStockSend(dayOfWeekForStockSend);
Я вот так имел в виду :)
`customer.setDayOfWeekForStockSend(DayOfWeekForStockSend.valueOf(day));`

2021-03-15 17:50 UTC, tediik requested changes

2021-03-15 17:50 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerNotificationsRestController.java
> +    public ResponseEntity<ResponseDto<DayOfWeekForStockSend>> setCustomerDayOfWeekForStockSend(@RequestBody String day) {
тут бы понятнее для фронтов, в каком именно формате день задавать, строчными? прописными? Я бы ниже в коде сделал приведение к нижнему регистру безусловное как вариант

2021-03-15 17:50 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerNotificationsRestController.java
> +        day = day.replaceAll("\"", "");
вот, этот момент мне не понятен, например, что там такое с форматом, почему надо кавычки "выпиливать"?? может просто принимать день без кавычек??

2021-03-15 17:50 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerNotificationsRestController.java
> +     */
фронтам то снаружи опять будет не понятно в каком виде и что именно слать, может в описание @ApiOperation засунуть пояснение хотя бы

2021-03-15 17:50 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerNotificationsRestController.java
> +    @PutMapping("/unsubscribePriceChangesEmail")
думаю логично в этом месте и в следующем методе вынести часть /unsubscribe отдельно в url:
/unsubscribe/PriceChangesEmail

2021-03-15 17:50 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerNotificationsRestController.java
> +        return new ResponseEntity<>(new ResponseDto<>(true, answers), HttpStatus.OK);
а можно было красиво в фунциональном стиле.. ну ладно ))

2021-03-15 17:50 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/PriceChangeNotificationsServiceImpl.java
> +
Катя устала и решила, что хватит JavaDoc )))

2021-03-16 20:02 UTC, tediik approved these changes

2021-03-16 20:02 UTC, merged