Refactor/change read only status for user
tediik/online_store pull request #289
Opened 2021-03-13 18:47 UTC by fponin

Добавил поле Bollean ReadOnly в сущность User.
Добавил эндпоинт /changeProfileStatusToReadOnly/{id} меняет статус туда и обратно
Добавил CommentNotSavedException при попытке оставить коммент "ограниченному" User'y

2021-03-13 18:49 UTC, fponin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Сделать так, чтобы администратор мог блокировать любому пользователю на его усмотрение - правку/создание комментариев, оставить только чтение](https://trello.com/c/42sraS24/324-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%82%D0%B0%D0%BA-%D1%87%D1%82%D0%BE%D0%B1%D1%8B-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%BE%D1%80-%D0%BC%D0%BE%D0%B3-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BB%D1%8E%D0%B1%D0%BE%D0%BC%D1%83-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8E-%D0%BD%D0%B0-%D0%B5%D0%B3%D0%BE-%D1%83%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D1%83-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B5%D0%B2-%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%82%D0%BE%D0%BB%D1%8C)

2021-03-15 17:34 UTC, BuravtsevaEkaterina reviewed
работает

2021-03-15 17:34 UTC, BuravtsevaEkaterina commented on src/main/java/com/jm/online_store/model/User.java
> +    public boolean getAccountNonReadOnlyStatus() {
геттеры и сеттеры Lombok подставит. Так что, думаю, тут отдельно выносить не нужно

2021-03-15 17:34 UTC, BuravtsevaEkaterina commented on src/main/java/com/jm/online_store/model/User.java
> +    private Boolean isAccountNonReadOnlyStatus = true;
Есть ли необходимость использовать объект, специфических операций на ним не проводится в этом качестве. Примитив занимает меньше памяти (**b**oolean)

2021-03-15 17:34 UTC, BuravtsevaEkaterina commented on src/main/java/com/jm/online_store/service/impl/CustomerServiceImpl.java
> +     * Метод, который изменяет статус клиента на "Только Чтение"
Меняет в обе стороны на чтение и обратно

2021-03-15 17:34 UTC, BuravtsevaEkaterina commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +            customerService.changeCustomerStatusToReadOnly(id);
По таске блокировать можно любого пользователя, если я правильно понимаю, то это User. CustomerService - действия с Customer

2021-03-15 17:42 UTC, BuravtsevaEkaterina commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +    @PostMapping("/changeProfileStatusToReadOnly/{id}")
Право на блокировку только у админа должно быть

2021-03-15 18:57 UTC, fponin commented on src/main/java/com/jm/online_store/model/User.java
> +    public boolean getAccountNonReadOnlyStatus() {
Я думал он не работает, и делает только Set.
Теперь пришлось разобраться, обратился к докам - и если коротко, то метод для переменной типа boolean и начинающейся на is он у метода get название не меняет. Так и остается isNameVar.

2021-03-15 20:27 UTC, tediik requested changes

2021-03-15 20:27 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +    @ApiOperation(value = "Changes User ReadOnly status",
тогда уж не User, а конкретнее - Customer

2021-03-15 20:27 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/CustomerServiceImpl.java
> +        log.info("Права на запись у покупателя с почтой " + customerStatusChange.getEmail() + "изменены. Запись - " + customerStatusChange.isAccountNonReadOnlyStatus());
давай с шаблонами подстановки вместо конкатенации тут

2021-03-15 20:27 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/CommentServiceImpl.java
> +     *
ну вот зачем ты это везде делаешь, я борюсь с этим, выпиливаю везде где могу, и все равно вы вставляете эту пустую строчку в JavaDoc ))

2021-03-15 20:27 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CommentRestController.java
> +    public ResponseEntity<ResponseDto<?>> addComment(@RequestBody @Valid Comment comment, BindingResult bindingResult) {
тип возвращаемого значения поменял, а в JavaDoc не поменял

2021-03-15 20:27 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +        }
приведи в порядок кодстайл

2021-03-15 20:27 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerRestController.java
> +        log.debug("User with id: {}, was change - ReadOnlyStatus - " + !user.isAccountNonReadOnlyStatus(), id);
давай уж в одном стиле, без конкатенации

2021-03-16 10:04 UTC, tediik approved these changes

2021-03-16 10:04 UTC, merged