Feature/one customer page
tediik/online_store pull request #29
Opened 2020-08-20 18:27 UTC by mixed2004

сделал CustomerPage с помошъю вкладок. удалил Profile.html.  на рест пока не переводил. изменил контроллер по обновлению пользователя, т.к. при обновлении данных из формы перетирались данные юзера.

2020-09-02 17:11 UTC, AntonMoskvin requested changes, later dismissed

2020-09-02 17:11 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/OnlineStoreApplication.java
>  }
добавь пустую строчку в самом конце

2020-09-02 17:11 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/config/handler/StaticResourceConfiguration.java
> +}
добавь пустую строчку в самом конце

2020-09-02 17:11 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/config/security/MyUserDetailsService.java
>      public UserDetails loadUserByUsername(String username)
не знаю, кто это и когда делал, но поправь для корректности email вместо username

2020-09-02 17:12 UTC, AntonMoskvin commented
Так же реши конфликты

2020-09-02 19:12 UTC, tediik requested changes

2020-09-02 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/config/handler/LoginSuccessHandler.java
> +            httpServletResponse.sendRedirect("/customer");
почему так? после логина покупатель попадает на главную страницу

2020-09-02 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGoodsRestController.java
> +     */
ну в таком случае, лучше вообще не писать JavaDoc, прибери по всему файлу

2020-09-02 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGoodsRestController.java
> +    public ResponseEntity addFavouritesGoods(@RequestBody Long id, Authentication authentication) {
тут и везде - используем параметризованный ResponseEntity

2020-09-02 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGoodsRestController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
используй фабричные методы из ResponseEntity - например, тут подойдет ResponseEntity.ok();

2020-09-02 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGoodsRestController.java
> +        }
так Set в принципе сам не даст добавить дубликаты же

2020-09-02 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGoodsRestController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
это касается всего класса в целом!

2020-09-02 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/OrderRestController.java
> +    }
после метода - пустая строчка для читабельности, перед JavaDoc - тоже пустая строчка

2020-09-02 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/OrderRestController.java
> +    @GetMapping("/customer/getAllOrders")
общий url - /customer вынести в заголовок класса

2020-09-02 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGoodsRestController.java
> +    @DeleteMapping(value = "/customer/favouritesGoods")
url общий для всех - просто вынеси в заголовок класса

2020-09-02 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/model/Order.java
> +import javax.persistence.FetchType;
не увидел зачем оно тут

2020-09-02 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/model/Order.java
> +            property = "id")
где-то я уже подобное видел и подобный код там удаляли, из-за разного рода проблем, ощущение, что смерджил dev не очень корректно

2020-09-02 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/OrderServiceImpl.java
> +
лишняя

2020-09-02 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/OrderServiceImpl.java
> +        return order;
мне старый вариант больше нравился!

2020-09-02 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/service/interf/OrderService.java
> +import org.springframework.data.domain.jaxb.SpringDataJaxb;
используется?

2020-09-02 19:12 UTC, tediik commented on src/main/resources/static/js/busket.js
> +                   <path id="heart${content[key].id}" d="m219.28949,21.827393c-66.240005,0 -119.999954,53.76001 -119.999954,120c0,134.755524 135.933151,170.08728 228.562454,303.308044c87.574219,-132.
перенос строки

2020-09-02 19:44 UTC, mixed2004 commented on src/main/java/com/jm/online_store/model/Order.java
> +            property = "id")
тут вернул обратно, потому что рест не выдает данные, только айдишники

2020-09-02 21:32 UTC, tediik requested changes
Переделай методы в FavouritesGoodsRestController.java аналогично методам OrderRestController:
используем параметризованный ResponseEntity и никакого приведения типа в твоем случае быть не должно

2020-09-03 10:35 UTC, tediik approved these changes

2020-09-03 10:35 UTC, merged