Feature/filters
tediik/online_store pull request #291
Opened 2021-03-21 17:41 UTC by BuravtsevaEkaterina

Реализация функционала фильтрации товаров

2021-03-21 17:43 UTC, BuravtsevaEkaterina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Работа фильтра товаров в выбранной категории](https://trello.com/c/w364rqpH/232-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B0-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D0%BE%D0%B2-%D0%B2-%D0%B2%D1%8B%D0%B1%D1%80%D0%B0%D0%BD%D0%BD%D0%BE%D0%B9-%D0%BA%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D0%B8%D0%B8)

2021-03-24 18:25 UTC, fponin reviewed
Проверил, замечаний нет.

2021-03-24 19:46 UTC, tediik requested changes

2021-03-24 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/FilterServiceImpl.java
> +    public List<ProductDto> filterProducts(String category,
мне кажется тут правильнее - getProductsByFilter

2021-03-24 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/FilterServiceImpl.java
> +                                           List<String> bluetooth) {
а если у выбранной категории нет например параметра OS?
Задавать жестко список ожидаемых параметров тут - это плохая идея.
Надо думать над архитектурой дальше, это точно неверное решение, не расширяемое..

2021-03-24 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/FilterServiceImpl.java
> +        List<Product> products = productService.findProductsByCategoryName(category);
тащим из базы пару сотен продуктов указанной категерии со всеми их подсущностями?
Это будет очень медленная работа фильтра на большом объеме данных.
Нужно решение - фильтрующее продукты на этапе запроса в БД, чтобы тянуть только то, что нам нужно.

2021-03-24 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/FilterServiceImpl.java
> +        List<Product> products = productService.findProductsByCategoryName(productsCategory);
как я понял, ты тащишь все продукты выбранной категории, чтобы потом вытащить у них описания? Может тогда сразу запросом тянуть все описания продуктов выбранной категории - это явно "легче" для приложения.

2021-03-24 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/FilterServiceImpl.java
> +        Set<CheckboxFilter.Label> bluetooth = new TreeSet<>();
эти параметры мы не должны зашивать в код, они должны быть доступны динамически из базы - что это? описания или характеристики продуктов? вытаскивай это из базы, на выходе тут можно вообще формировать карту Map<String, TreeSet<CheckboxFilter.Label>> как вариант, где в качестве ключа будут твои brands, ram и т.д.

2021-03-24 19:46 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/FilterServiceImpl.java
> +        }
когда пересмотришь логику вверху, станет понятно, что нет необходимости в этих проверках, потому что ты будешь получать конкретный список/сет описаний/характерстик для выбранной категории, ведь логично, что у нас для одной отдельно взятой категории продукта - один и тот же набор описаний/характерстик

2021-03-29 15:30 UTC, tediik approved these changes

2021-03-29 15:30 UTC, merged