Feature/delete notification
tediik/online_store pull request #294
Opened 2021-03-31 05:26 UTC by Maksim1113

2021-03-31 19:45 UTC, fponin reviewed
Комментарии в коде.
Нужно делать то что просят в задаче.

2021-03-31 19:45 UTC, fponin commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerNotificationsRestController.java
> +     * @param id - id уведомления {@link Long}
Зачем ссылка на Long?

2021-03-31 19:45 UTC, fponin commented on src/main/java/com/jm/online_store/controller/rest/customer/CustomerNotificationsRestController.java
> +     * @param id покупателя {@link Long}
Ссылку можно на сущность делать

2021-03-31 19:45 UTC, fponin commented on src/main/java/com/jm/online_store/model/AnswerNotifications.java
> +}
В задаче было только "удаление уведомлений".
Если были отдельные договоренности, то об этом стоило упомянуть в карточке.

2021-03-31 19:45 UTC, fponin commented on src/main/java/com/jm/online_store/service/impl/CommentServiceImpl.java
>       * @return Comment
JavaDoc в проекте преимущественно на русском, если коснулся - переведи.
Удали лишние пропуски строк.(79 строка)

2021-03-31 19:45 UTC, fponin commented on src/main/java/com/jm/online_store/service/impl/CommentServiceImpl.java
> +                answerNotificationsService.addNotification(comment);
Не нужно два раза добавлять уведомление.

2021-03-31 19:45 UTC, fponin commented on src/main/java/com/jm/online_store/service/impl/ReviewServiceImpl.java
> +import com.jm.online_store.service.interf.AnswerNotificationsService;
Не нужен импорт.

2021-03-31 19:47 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/CommentServiceImpl.java
>       * @return Comment
тут не согласен, можно оставить на eng

2021-03-31 19:56 UTC, fponin commented on src/main/java/com/jm/online_store/service/impl/CommentServiceImpl.java
>       * @return Comment
Ок, я думал следует приводить к однообразию.
А так считаю ENG - best-practice

2021-04-02 09:15 UTC, tediik requested changes

2021-04-02 09:15 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/CommentServiceImpl.java
> +                answerNotificationsService.addNotification(comment);
Согласен, не нужно 2 раза добавлять уведомление!

2021-04-02 09:15 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/AnswerNotificationsServiceImpl.java
> +     *
1 лишняя строчка, убери

2021-04-02 13:25 UTC, tediik approved these changes

2021-04-02 13:25 UTC, merged