oauth authorization odnoklassniki
tediik/online_store pull request #38
Opened 2020-08-24 15:32 UTC by sirajDeveloper

oauth authorization odnoklassniki

2020-08-25 18:31 UTC, tediik requested changes
Файлы логов прошу не коммитить в проект - убери
Поправь остальные замечания.

2020-08-25 18:31 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/odnoklassniki/OAuth2Service.java
> +    private RoleService roleService;
Если не через поле - не работает?

2020-08-25 18:31 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/odnoklassniki/OAuth2Service.java
> +    private final String secretKey = "2DD0271520909F838004E332";
вынести в application.properties

2020-08-25 18:31 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/odnoklassniki/OAuth2Service.java
> +            .callback("http://localhost:9999/oauth")
неее и как прикажешь потом запускать это на другом сервере?? с реальным адресом

2020-08-25 18:31 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/odnoklassniki/OAuth2Service.java
> +            }
другого более красивого способа нет, чтобы получать эти пары?

2020-08-25 18:31 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/LoginController.java
> +
лишняя пустая строчка

2020-08-25 18:31 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/LoginController.java
> +
2 лишних пустых строчки

2020-08-25 18:31 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/AppConfig.java
> +    }
Может назвать его как-то сообразно с одноклассниками, чтобы было понятно, что этот сервис именно для этого?

2020-08-26 09:06 UTC, sirajDeveloper commented on src/main/java/com/jm/online_store/controller/simple/LoginController.java
> +
думал так более читабельно 1 отступ от сигнатуры

2020-08-26 09:06 UTC, sirajDeveloper commented on src/main/java/com/jm/online_store/config/security/odnoklassniki/OAuth2Service.java
> +            }
как еще распотрошить по переменным эту строку? или имеешь ввиду какую нибудь библиотеку юзать?

2020-08-26 09:07 UTC, sirajDeveloper commented on src/main/java/com/jm/online_store/config/security/odnoklassniki/OAuth2Service.java
> +            .callback("http://localhost:9999/oauth")
намек понял

2020-08-26 09:09 UTC, sirajDeveloper commented on src/main/java/com/jm/online_store/config/security/odnoklassniki/OAuth2Service.java
> +    private RoleService roleService;
через конструктор и так и сяк пробовал, не внедряет зависимости, с полем ок.

2020-08-26 14:17 UTC, tediik approved these changes

2020-08-26 14:17 UTC, merged