Feature/profile picture
tediik/online_store pull request #39
Opened 2020-08-24 16:04 UTC by Yurikru

2020-08-25 18:56 UTC, tediik requested changes
Есть замечания и точно будут конфликты

2020-08-25 18:56 UTC, tediik commented on src/main/java/com/jm/online_store/config/handler/StaticResourceConfiguration.java
> +                "classpath:/static/", "classpath:/public/", "classpath:/uploads/", "file:uploads/");
а тут действительно надо все-все путяти перечислять и я нашел, что "file:uploads/" аж 2 раза!

2020-08-25 18:56 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +    }
т.е. удаление и загрузка новой аватарки должны сопровождаться перезагрузкой страницы?

2020-08-25 18:56 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +                log.debug("Failed to store file {} {}", fileNameAndPath, e.getMessage());
log.debug("Failed to store file: {}, because: {}", fileNameAndPath, e.getMessage());

2020-08-25 18:56 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +    public void updateUserImage(Long userId, MultipartFile file) {
JavaDoc

2020-08-25 18:56 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +    public void deleteUserImage(Long userId) {
JavaDoc

2020-08-25 18:56 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +            log.debug("Failed to delete file {} {} ", fileNameAndPath.getFileName().toString(), e.getMessage());
log.debug("Failed to delete file: {}, because: {} ", fileNameAndPath.getFileName().toString(), e.getMessage());

2020-08-25 18:56 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +    public void setDefaultUserAvatar(Long userId) {
Javadoc

2020-08-25 18:56 UTC, tediik commented on src/main/resources/application.properties
> +logging.level.root=info
нет, давай все же пока оставлять всегда в debug

2020-08-26 09:47 UTC, Yurikru commented on src/main/java/com/jm/online_store/config/handler/StaticResourceConfiguration.java
> +                "classpath:/static/", "classpath:/public/", "classpath:/uploads/", "file:uploads/");
Действительно все не нужны, пока хватит только uploads

2020-08-26 09:47 UTC, Yurikru commented on src/main/java/com/jm/online_store/controller/simple/CustomerController.java
> +    }
Ну а как иначе? Это ведь не rest... что то я не смекну ))

2020-08-27 11:12 UTC, Yurikru commented
Переделал обновление картинки без перегрузки страницы, добавил Jquery&Ajax. Поправил остальные замечания

2020-08-27 11:24 UTC, tediik approved these changes

2020-08-27 11:24 UTC, merged