Feature/user basket
tediik/online_store pull request #41
Opened 2020-08-25 11:38 UTC by mixed2004

Сделал корзину покупателя. как смог облагородил)  добавил значки "Р" в конце цены и стоимости. сделал кнопку формирования заказа из корзины. корзина после заказа очищается. формируется новый заказ со статусом "в корзине".

2020-08-25 19:20 UTC, tediik requested changes
Много замечаний и у меня пока нет однозначного понимания, что сама структура правильная, а также, что ты не путаешь корзину и избранные товары.
Файлы логов не должны попадать в PR - удали.

2020-08-25 19:20 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/BusketRestController.java
> +        User autorityUser = userService.findById(((User) authentication.getPrincipal()).getId()).get();
эту строчку положи в метод приватный и в каждом своем методе уже вызывай тот метод для получения авторизованного юзера

2020-08-25 19:20 UTC, tediik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +        List<Basket> basketList = new ArrayList<>();
не понял почему у покупателя может быть несколько корзин

2020-08-25 19:20 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/BusketRestController.java
> +    public ResponseEntity<List<Basket>> getFavouritesGoods(Authentication authentication) {
почему getFavouritesGoods - это же список избранных товаров, это не относится никак к корзине

2020-08-25 19:20 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/BusketRestController.java
> +
лишняя пустая строка

2020-08-25 19:20 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/BusketRestController.java
> +}
так у них же код почти 1 в 1, может сделаем метод общий и просто будем передавать какую-нибудь булеву составляющую, чтобы понять вычитать или складывать?

2020-08-25 19:20 UTC, tediik commented on src/main/java/com/jm/online_store/model/Basket.java
> +@Setter
Аннотация Data не работает?

2020-08-25 19:20 UTC, tediik commented on src/main/java/com/jm/online_store/model/Basket.java
> +    @ManyToOne(fetch = FetchType.EAGER)
@ManyToOne итак по умолчанию EAGER, но меня терзают сомнения, что тут нужна ManyToMany??

2020-08-25 19:20 UTC, tediik commented on src/main/java/com/jm/online_store/model/User.java
> +    @OneToMany(fetch = FetchType.LAZY)
OneToMany по умолчанию уже LAZY, убирай

2020-08-27 19:13 UTC, tediik requested changes
Реши конфликты, есть замечания и + сделай так, чтобы лог-файлы сюда не коммитились, пожалуйста

2020-08-27 19:13 UTC, tediik commented on src/main/java/com/jm/online_store/service/interf/BasketService.java
> +public interface BasketService {
вот тут и в некоторых других местах - такие JavaDoc прям избыточны, их суть - помогать но не раздражать, есть вещи, которые понятны итак с первого взгляда.

2020-08-27 19:13 UTC, tediik commented on src/main/resources/static/js/busket.js
> +    <tr>
выравняй код, чего они у тебя вперед то выехали? если див вложен в td - значит отступ вглубь, если в этот див вложен button - значит он еще глубже, приведи код в порядок

2020-08-28 06:08 UTC, mixed2004 commented on src/main/java/com/jm/online_store/controller/rest/BusketRestController.java
> +        User autorityUser = userService.findById(((User) authentication.getPrincipal()).getId()).get();
сделано

2020-08-28 06:08 UTC, mixed2004 commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +        List<Basket> basketList = new ArrayList<>();
обсуждалось

2020-08-28 06:09 UTC, mixed2004 commented on src/main/java/com/jm/online_store/controller/rest/BusketRestController.java
> +    public ResponseEntity<List<Basket>> getFavouritesGoods(Authentication authentication) {
исправлено

2020-08-28 06:09 UTC, mixed2004 commented on src/main/java/com/jm/online_store/controller/rest/BusketRestController.java
> +
исправлено

2020-08-28 06:09 UTC, mixed2004 commented on src/main/java/com/jm/online_store/controller/rest/BusketRestController.java
> +}
исправлено

2020-08-28 06:10 UTC, mixed2004 commented on src/main/java/com/jm/online_store/model/Basket.java
> +@Setter
Data не всегда работает, поэтому оставил так

2020-08-28 06:10 UTC, mixed2004 commented on src/main/java/com/jm/online_store/model/Basket.java
> +    @ManyToOne(fetch = FetchType.EAGER)
EAGER убрал, структуру оставил туже, считаю, что она более подходит

2020-08-28 06:11 UTC, mixed2004 commented on src/main/java/com/jm/online_store/model/User.java
> +    @OneToMany(fetch = FetchType.LAZY)
исправлено

2020-08-28 06:11 UTC, mixed2004 commented on src/main/java/com/jm/online_store/service/interf/BasketService.java
> +public interface BasketService {
убрано, Была установка добавлять доки для классов и методов.

2020-08-28 06:12 UTC, mixed2004 commented on src/main/resources/static/js/busket.js
> +    <tr>
исправлено

2020-08-28 07:29 UTC, tediik approved these changes

2020-08-28 07:29 UTC, merged