Twitter auth
tediik/online_store pull request #54
Opened 2020-08-30 12:07 UTC by AntonMoskvin

Авторизация через Твиттер:
1. Твиттер не предоставляет email, поэтому пришлось указать пример
2. Твиттер не предоставляет фамилию, поэтому указал поле логина в качестве фамилии
3. Позволил себе поправить переменную в параметрах метода findByEmail (вместо username указал email, была опечатка) т.к этот метод я использую.

2020-08-30 12:29 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +    @Autowired
можно убрать @Autowired над полем у тебя же есть @AllArgsConstructor
Напиши просто private final UserService userService;

2020-08-30 12:30 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +    @Autowired
ну и тут тоже

2020-08-30 12:33 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +        System.out.println("Fetching the Request Token...");
а почему не log.debug?

2020-08-30 12:34 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +        System.out.println("Trading the Request Token for an Access Token...");
ну и тут log.debug и там дальше тоже много sout. Лучше наверное log использовать.

2020-08-30 12:35 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +
лишня строчка.

2020-08-30 12:46 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/LoginController.java
> +
лишняя строчка

2020-08-30 12:50 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/TwitterController.java
> +//
Для чего закоментил целый класс?

2020-08-30 12:59 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +    @Autowired
если сделать private надо инициализировать 1 раз при создании, а они только в конце используются

2020-08-30 13:00 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +
убрал

2020-08-30 13:00 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/controller/simple/LoginController.java
> +
убрал

2020-08-30 13:01 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/controller/simple/TwitterController.java
> +//
удалил, откуда то затесался, не заметил

2020-08-30 13:09 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +    @Autowired
так они у тебя и есть private. Я к тому что бы ижектить зависимость не по полю а через конструктор

2020-08-30 13:10 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +        System.out.println("Fetching the Request Token...");
сделал

2020-08-30 13:10 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +        System.out.println("Trading the Request Token for an Access Token...");
сделал

2020-08-30 20:23 UTC, tediik requested changes

2020-08-30 20:23 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +    @Autowired
замечание коллеги не исправлено!

2020-08-30 20:23 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +                .build(TwitterApi.instance());
Вынести в application.properties

2020-08-30 20:23 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +    @SuppressWarnings("PMD.SystemPrintln")
Это что??

2020-08-30 20:23 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +        String email = "test@example.ru";
у нас вроде поле email - уникальное? как будут хранится несколько юзеров с 1 email?

2020-08-31 07:09 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +    @Autowired
ой я имел в виду final не получится сделать

2020-08-31 07:54 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +    @Autowired
поправил

2020-08-31 07:54 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/config/security/Twitter/TwitterAuth.java
> +    @Autowired
поправил

2020-08-31 08:08 UTC, AntonMoskvin commented
Поправил замечания, убрал лишнее. Твиттер не дает доступ к почте, вместо этого сделал добавление пользователя по имени. Добавил соответствующий метод в репозиторий и сервис.

2020-08-31 11:27 UTC, tediik approved these changes

2020-08-31 11:27 UTC, merged