Added VKontakte auth of user
tediik/online_store pull request #56
Opened 2020-08-30 21:53 UTC by DaveShedar

Добавлена авторизация пользователя через ВКонтакте api

2020-09-02 09:46 UTC, tediik requested changes

2020-09-02 09:46 UTC, tediik commented on pom.xml
> +			<version>20190722</version>
чем не устраивает встроенный в Спринг Бут Jackson???

2020-09-02 09:46 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/vk/VkApiClient.java
> +//@NoArgsConstructor
никакого лишнего кода, убрать

2020-09-02 09:46 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/vk/VkApiClient.java
> +    }
кодстайл тут и по всему классу проверь

2020-09-02 09:46 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/vk/VkApiClient.java
> +    @Value("${spring.auth.vk.client_id}")
от предыдущего поля отступаем 1 строчку, чтобы визуально отделялся JavaDoc

2020-09-02 09:46 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/vk/VkApiClient.java
> +            Set< Role > customerRoles = new HashSet<>();
это что за кодстайл такой?

2020-09-02 09:46 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/vk/VkApiClient.java
> +            Set< Role > customerRoles = new HashSet<>();
Используй встроенный Jackson

2020-09-02 09:46 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/vk/VkApiClient.java
> +            res += line;
оформи с { }

2020-09-02 09:46 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/vk/VkApiClient.java
> +        CloseableHttpClient httpClient = HttpClients.createDefault();
нужно ли каждый раз создавать нового клиента или достаточно будет создать 1 раз при инициализации класса?

2020-09-02 09:46 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/vk/VkApiClient.java
> +            }
какая-то громоздкая работа с этим httpClient получается и мне пока это что-то не нравится, я бы предпочел использование RestTemplate для запросов

2020-09-02 09:46 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/vk/VkApiClient.java
> +            e.printStackTrace();
плюсом или даже вместо - залогируй ошибку

2020-09-02 09:46 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/vk/VkApiClient.java
> +            e.printStackTrace();
плюсом или даже вместо - залогируй ошибку

2020-09-02 09:46 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/LoginController.java
> +        model.addAttribute("link", vkApiClient.getVkAuthUrl());
vkAuthLink или authUrlVK

2020-09-04 22:55 UTC, DaveShedar commented
Скорректировал согласно замечаниям.

2020-09-05 19:45 UTC, tediik requested changes
Поправь замечания

2020-09-05 19:45 UTC, tediik commented on pom.xml
> +
почему 2 раза? нам точно нужна кастомная зависимость, та, что уже встроена в СпрингБут не подходит?

2020-09-05 19:45 UTC, tediik commented on src/main/resources/application.properties
> +
строчка лишняя

2020-09-05 19:45 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/vk/VkApiClient.java
> +        Set< Role > customerRoles = new HashSet<>();
Я же писал - странный кодстайл, пиши везде Optional<Role> и далее в таком же стиле!

2020-09-05 19:45 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/vk/VkApiClient.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
достаточно указать private final ObjectMapper objectMapper - учитывая Ломбок, который подставит сам конструктор тут у тебя - СпрингБут автоматически тебе бин ObjectMapper заинжектит

2020-09-05 19:45 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/vk/VkApiClient.java
> +    public String getUserInfoUrl(){
тут и дальше - перед открывающей скобкой всегда пробел
public String getUserInfoUrl() {

2020-09-07 16:21 UTC, DaveShedar commented
Переделал согласно замечаний.

2020-09-07 17:30 UTC, tediik requested changes
Вадим, ты перетер часть валидного кода! Это негоже! Я тебя чему месяц учил!? Исправляй замечания

2020-09-07 17:30 UTC, tediik commented on pom.xml
> -		</dependency>
Проверь ВЕСЬ файл, ты удалил много нужного кода, ощущение, что ты не смерджил со свежим девом или криво смерджил

2020-09-07 17:30 UTC, tediik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> - * в файле "application.yml" с "update" на "create" или "create-drop".
нет! ты точно или старый дев лил или криво смерджил! это было валидное изменение, а ты его затер!

2020-09-07 17:30 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/SecurityConfig.java
> -                .antMatchers("/boss/**").access("hasAnyRole('ROLE_ADMIN', 'ROLE_MANAGER')")
почему убрал?

2020-09-07 17:30 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/SchedulingServiceImpl.java
> +     * Метод выполняется с регулярностью заданным параметром ${emailStockSending.delay} в файле application.properties
неверно, перезатер

2020-09-07 19:44 UTC, DaveShedar commented
Вероятно связано с ошибками при мердже.

2020-09-08 15:20 UTC, tediik requested changes

2020-09-08 15:20 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/vk/VkApiClient.java
> +        userEmail = jsonObject.getString("email");
Я прошу прощения, что сразу не увидел этот код, но надо переписать с использованием Jackson, который уже встроен в Спринг Бут, соответственно твою кастомную зависимость из pom.xml надо убрать

2020-09-08 15:20 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/vk/VkApiClient.java
> +        String lastName = jsonObject.getJsonArray("response").getJsonObject(0).getString("last_name");
Я прошу прощения, что сразу не увидел этот код, но надо переписать с использованием Jackson, который уже встроен в Спринг Бут, соответственно твою кастомную зависимость из pom.xml надо убрать

2020-09-09 11:33 UTC, closed without merging