Feature/role based render page
tediik/online_store pull request #58
Opened 2020-09-01 01:10 UTC by neuromanzer

2020-09-01 14:41 UTC, dshishkaryan commented on src/main/resources/static/js/mainPage.js
> +            $('#role-redirect').attr("href", "http://localhost:9999/customer/profile");
здесь надо убрать ссылки, заменить на относительные.

2020-09-01 14:42 UTC, dshishkaryan commented on src/main/resources/static/js/mainPage.js
> +            $('#role-redirect').attr("href", "http://localhost:9999/customer/profile");
тоже ссылки на относительные

2020-09-01 14:42 UTC, dshishkaryan commented on src/main/resources/static/js/mainPage.js
> +            $('#profile-main-link').attr("href", "http://localhost:9999/manager");
и тут

2020-09-01 14:46 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/config/handler/CurrentUserInterceptor.java
> +public class CurrentUserInterceptor implements HandlerInterceptor {
можно реализовать проще через рест, брать authentication.principal. Как лучше наверное у Эдуарда лучше узнать.

2020-09-01 14:46 UTC, dshishkaryan commented on src/main/resources/static/js/mainPage.js
> +function roleBasedRenderPage(e) {
пустая функция для чего?

2020-09-01 14:49 UTC, dshishkaryan commented on src/main/resources/templates/mainPage.html
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
вот эти скрипты от бутстрапа мне кажется все же лучше вниз переносить как в документации указано. https://getbootstrap.com/docs/4.5/getting-started/introduction/

2020-09-01 14:50 UTC, dshishkaryan commented on src/main/resources/templates/mainPage.html
> +
хорошо бы пустые строчки поудалять. И не свои тоже.

2020-09-01 19:12 UTC, tediik requested changes

2020-09-01 19:12 UTC, tediik commented on src/main/resources/static/js/mainPage.js
> +
Потом мы добавим в кабинеты юзера и админа, менеджера что-то еще и будем писать кучу hide() и т.д. Лучше сделать отдельную страничку для профиля покупателя и профиля менеджера / админа

2020-09-01 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/config/handler/CurrentUserInterceptor.java
> +public class CurrentUserInterceptor implements HandlerInterceptor {
Я пока тоже не понимаю надобности делать через HandlerInterceptor - надо будет голосовое пояснение на созвоне или в переделку

2020-09-01 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/config/handler/LoginSuccessHandler.java
> -            httpServletResponse.sendRedirect("/manager");
Я не просил этого в таске, как раз админ заходит под собой чтобы попасть в кабинет админа, а покупателю главное - страница с товарами, тоже касается и менеджера - после логина он попадает в свой кабинет

2020-09-01 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/config/handler/StaticResourceConfiguration.java
> +    }
Пока спорный момент

2020-09-01 19:12 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/SecurityConfig.java
> +                .antMatchers("/customer/**").access("hasAnyRole('ROLE_CUSTOMER','ROLE_ADMIN', 'ROLE_MANAGER')")
Я все же думаю логичнее оставить /customer/** только для покупателя и сделать отдельный url для профиля админа и менеджера, можно ли их (А и М) повесить на 1 url - не знаю, подумай.

2020-09-01 19:12 UTC, tediik commented on src/main/resources/static/js/mainPage.js
> +    $('#user-email').text($.cookie('email'));
это можно отдать по запросу на рест-контроллер

2020-09-01 19:12 UTC, tediik commented on src/main/resources/templates/mainPage.html
> +    <div sec:authorize="hasAnyAuthority('ROLE_CUSTOMER', 'ROLE_ADMIN', 'ROLE_MANAGER')" class="btn loginbutton">
эти вещи делаются гораздо проще, посмотри тут:
https://www.codeflow.site/ru/article/spring-security-taglibs
и переделай, нет нужды указывать всех-всех "вошедших"

2020-09-03 18:49 UTC, tediik approved these changes

2020-09-03 18:50 UTC, merged