test/mailSenderService
tediik/online_store pull request #59
Opened 2020-09-01 16:40 UTC by sirajDeveloper

Тест для mailSenderServiceImpl. Тестируем отправку сообщения, используется тестовый сервер green mail

2020-09-01 17:19 UTC, AntonMoskvin commented
проверил, тест проходит

2020-09-01 18:23 UTC, AntonMoskvin requested changes

2020-09-01 18:23 UTC, AntonMoskvin commented on src/test/java/com/jm/online_store/service/impl/MailSenderServiceImplTest.java
>  @RunWith(SpringRunner.class)
@RunWith используется с JUnit < 5 версии

2020-09-01 18:23 UTC, AntonMoskvin commented on src/test/java/com/jm/online_store/service/impl/MailSenderServiceImplTest.java
>  @RunWith(SpringRunner.class)
@SpringBootTest Используется для интеграционного тестирования, тесты проходят и без данной аннотации. Убери

2020-09-01 18:23 UTC, AntonMoskvin commented on src/test/java/com/jm/online_store/service/impl/MailSenderServiceImplTest.java
>  @RunWith(SpringRunner.class)
@ActiveProfiles("test") У нас нет профилей, что бы выделять какой либо. Убери, соответственно лишние импорты тоже.

2020-09-01 18:23 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/service/impl/MailSenderServiceImpl.java
>  @RequiredArgsConstructor
Замени на @Data для лаконичности

2020-09-01 18:23 UTC, AntonMoskvin commented on src/test/java/com/jm/online_store/service/impl/MailSenderServiceImplTest.java
> +}
добавь пустую строчку

2020-09-01 18:32 UTC, sirajDeveloper commented on src/test/java/com/jm/online_store/service/impl/MailSenderServiceImplTest.java
>  @RunWith(SpringRunner.class)
без @SpringBootTest не внедряется зависимость в private MailSenderServiceImpl senderService;

2020-09-01 18:42 UTC, AntonMoskvin commented on src/test/java/com/jm/online_store/service/impl/MailSenderServiceImplTest.java
>  @RunWith(SpringRunner.class)
Согласен, аннотация @SpringBootTest нужна, погорячился с выводами.

2020-09-01 18:46 UTC, AntonMoskvin requested changes

2020-09-01 18:46 UTC, AntonMoskvin commented on src/test/java/com/jm/online_store/service/impl/MailSenderServiceImplTest.java
> +}
Я имел в виду после закрытия скобки. Гитхаб подсказывает

2020-09-01 18:46 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/service/impl/MailSenderServiceImpl.java
>  import lombok.Setter;
эти импорты соответственно не не нужны

2020-09-01 18:46 UTC, AntonMoskvin commented on src/main/java/com/jm/online_store/service/impl/MailSenderServiceImpl.java
>  @RequiredArgsConstructor
@Data включает и RequiredArgsConstructor тоже

2020-09-02 06:12 UTC, sirajDeveloper commented on src/test/java/com/jm/online_store/service/impl/MailSenderServiceImplTest.java
> +}
да я поставил вроде

2020-09-02 10:02 UTC, tediik requested changes

2020-09-02 10:02 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/MailSenderServiceImpl.java
> +    private JavaMailSender mailSender;
хмм.. а почему убрал final?

2020-09-02 11:33 UTC, sirajDeveloper commented on src/main/java/com/jm/online_store/service/impl/MailSenderServiceImpl.java
> +    private JavaMailSender mailSender;
Чтобы можно было сетать JavaMailSender. Когда в тесте мы заходим в тестируемый метод send, в этом методе используется определенный в классе JavaMailSender. Но в тестовом методе я внедряю другой обьект JavaMailSender и переопределяю setPort и setHost.  И далее в тестовом классе делаю

2020-09-02 11:40 UTC, sirajDeveloper commented on src/main/java/com/jm/online_store/service/impl/MailSenderServiceImpl.java
> +    private JavaMailSender mailSender;
Чтобы иметь вомзожность сетать JavaMailender. В тестовом классе назначаем порт и хост 
`javaMailSender.setPort(3025);
 javaMailSender.setHost("localhost");`
далее
`senderService.setMailSender(javaMailSender);`

2020-09-02 22:00 UTC, tediik approved these changes

2020-09-02 22:02 UTC, tediik approved these changes

2020-09-02 22:02 UTC, merged