87-добавление-данных-в-профилелюбом-имя-фамилия-затирает-дефолтный-ав…
tediik/online_store pull request #65
Opened 2020-09-04 15:44 UTC by neuromanzer

…атар-смена-пароля-у-того-же-юзера-затирает-ранее-занесенные-в

переписана логика апдейта юзера в профиле

2020-09-05 14:50 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/rest/AuthorityRestController.java
> +
лишня строка

2020-09-05 14:51 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/AllUsersController.java
> +//@RequiredArgsConstructor
если не нужен то лучше убрать

2020-09-05 14:53 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/AllUsersController.java
> +    @ResponseBody
судя по методам это у тебя рест контроллер получается. Его лучше перенести в пакет рест и дооформить что бы ResponseEntity возвращал

2020-09-05 14:53 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/AuthorityController.java
строка лишняя

2020-09-05 14:54 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/AuthorityController.java
>      @PostMapping("/profile")
я бы тут поменял бы на @PutMapping т.к. не новый объект а update

2020-09-05 14:55 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/AuthorityController.java
> +        if (!userService.changePassword(user.getId(), oldPassword, newPassword)) {
всю логику лучше перенести в сервисный слой

2020-09-05 14:55 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/AuthorityController.java
> -
строка пустая

2020-09-05 14:55 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/AuthorityController.java
> -
еще строка

2020-09-05 14:58 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/AuthorityController.java
> +        if (!userService.changePassword(user.getId(), oldPassword, newPassword)) {
Всю логику лучше в сервисный слой перенести если возможно

2020-09-05 15:00 UTC, neuromanzer commented on src/main/java/com/jm/online_store/controller/simple/AuthorityController.java
> +        if (!userService.changePassword(user.getId(), oldPassword, newPassword)) {
тут логика как раз в сервисе

2020-09-05 15:01 UTC, neuromanzer commented on src/main/java/com/jm/online_store/controller/rest/AuthorityRestController.java
> +
+

2020-09-05 15:01 UTC, neuromanzer commented on src/main/java/com/jm/online_store/controller/simple/AllUsersController.java
> +//@RequiredArgsConstructor
+

2020-09-05 15:10 UTC, neuromanzer commented on src/main/java/com/jm/online_store/controller/simple/AuthorityController.java
+

2020-09-05 15:16 UTC, neuromanzer commented on src/main/java/com/jm/online_store/controller/simple/AuthorityController.java
>      @PostMapping("/profile")
с @PutMapping кидает ошибку

2020-09-08 12:00 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/AllUsersController.java
> +    @ResponseBody
У тебя получается что это рест контроллер но лежит при этом в папке simple.

2020-09-08 12:03 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/simple/AuthorityController.java
>      @PostMapping("/profile")
Ну ошибка скорей всего из за того что с фронта POST а тут поменял на PUT

2020-09-08 14:26 UTC, tediik requested changes

2020-09-08 14:26 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AuthorityRestController.java
> +            return ResponseEntity.ok("duplicatedEmailError");
пишем, что ошибка, но кидаем статус 200?

2020-09-08 14:26 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/AllUsersController.java
> +    @ResponseBody
если есть @ResponseBody, при том во всех методах - явно просится переделать на rest-контроллер

2020-09-08 14:26 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +     * <p>
это что тут делает? ))

2020-09-08 17:46 UTC, tediik requested changes

2020-09-08 17:46 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/AllUsersRestController.java
> +    }
ну мы же не так делаем рест-контроллеры
1. убрать @ResponseBody
2. возвращать ResponseEntity<String> (в этом конкретном твоем случае)
3. соответственно строки с return - переписать с оглядкой на предыдущий пункт

2020-09-08 18:43 UTC, tediik approved these changes

2020-09-08 18:43 UTC, merged