Главная страница магазина
tediik/online_store pull request #75
Opened 2020-09-09 07:21 UTC by FroJuniK

Главная

2020-09-09 08:51 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/config/handler/StaticResourceConfiguration.java
> +
лишняя строка

2020-09-09 10:17 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/rest/MainPageRestController.java
> +    @Autowired
Через конструктор не получится заинжектить?

2020-09-09 10:19 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/rest/MainPageRestController.java
> +        return ResponseEntity.ok().body(categoriesBySuperCategories);
Здесь можно ResponseEntity.ok(categoriesBySuperCategories);

2020-09-09 10:31 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/rest/ProductRestController.java
> +    public static void setProductId(Long productId) {
Мне кажется productId Логичнее передовать через @PathVariable непосредственно запросом в маппинг.
 @GetMapping("/product/{id}")
    public ResponseEntity<Product> getProduct(@PathVariable Long id) {
        Product product = productService.findProductById(productId).get();
        return ResponseEntity.ok(product);
    }
    как то так

2020-09-09 10:43 UTC, dshishkaryan commented on src/main/java/com/jm/online_store/controller/rest/SubcategoryPageRestController.java
> +    public static void setCategoryName(String categoryName) {
Это мне кажется тоже можно передавать через @PathVariable

2020-09-10 18:02 UTC, tediik requested changes
Ксю, ты проделала огромную работу, я тобой горжусь.
Осталось довести начатое до конца!

2020-09-10 18:02 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/MainPageRestController.java
> +    }
Мне искренне жаль твой труд, но придется переписать, это плохой архитектурный подход, давай так:
public ResponseEntity<Map<String, Map<String, String>>> getCategories() {

В мапах с подкатегориями будет ключ - кириллица и значение на латинице.

Придется переписать работу с этим делом на фронте, но так как это сейчас - оставлять негоже.

2020-09-10 18:02 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/MainPageRestController.java
> +        List<Product> products = productService.findAllByIdBefore(16L);
я надеюсь это не привязка к id продукта, а именно его количество же? Тогда логичнее передавать туда цифру 15, если это привязка к id - это плохо, завтра эти продукты будут не нужны, их удалят и в БД id с 1 по 15 будут не закреплены ни за кем

2020-09-10 18:02 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/SubcategoryPageRestController.java
> +        return ResponseEntity.ok(category);
у Optional есть удобные методы, чтобы не городить такие проверки - ifPresentOrElse()

https://habr.com/ru/post/347748/
https://www.sirotin.eu/DOWNLOAD/OptionalInJavaPoster.pdf

2020-09-10 18:02 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/SubcategoryPageRestController.java
> +        return ResponseEntity.ok(categories);
лучше тогда написать сразу return ResponseEntity.ok(categoriesService.getAllCategories());

2020-09-10 18:02 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/ProductRestController.java
> +    }
у Optional есть удобные методы, чтобы не городить такие проверки - ifPresentOrElse()

2020-09-10 18:02 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/ProductController.java
> +        return "productPage";
стоп. А зачем мы вообще получали параметр @PathVariable(value = "id") Long productId
если нигде его не использовали?

2020-09-10 18:02 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/SubcategoryPageController.java
> +}
тут я тоже не понял - зачем нам получать параметр @PathVariable(value = "categoryName") String categoryName

2020-09-10 18:02 UTC, tediik commented on src/main/java/com/jm/online_store/repository/ProductRepository.java
> +    List<Product> findAllByIdBefore(Long id);
как уже писал ранее, такой подход не подойдет, не жизнеспособен в суровой реальности production

2020-09-10 18:02 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/ProductServiceImpl.java
> +        return productRepository.findAllByIdBefore(id);
ранее обсуждалось

2020-09-10 18:02 UTC, tediik commented on src/main/resources/templates/mainPage.html
> +                             src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
воу! а почему так? первый раз такое вижу

2020-09-10 18:27 UTC, FroJuniK commented on src/main/resources/templates/mainPage.html
> +                             src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
С сайта bootstrap из examples 🤷

2020-09-13 20:01 UTC, tediik approved these changes

2020-09-13 20:01 UTC, merged