Feature/f bregistration
tediik/online_store pull request #8
Opened 2020-08-13 11:06 UTC by Yurikru

Finished FB registration procees. On succesfull FB authorization FB user is saved to DB with Role_Customer and password "1".

2020-08-13 15:28 UTC, tediik requested changes

2020-08-13 15:28 UTC, tediik commented on pom.xml
> -		</dependency>
Почему удаляешь эту и другие зависимости? Я чет не очень понял этот момент! Может неправильно смерджил?

2020-08-13 15:28 UTC, tediik commented on pom.xml
> -		</dependency>
Проверь весь pom.xml

2020-08-13 15:28 UTC, tediik commented on src/main/java/com/jm/online_store/OnlineStoreApplication.java
> +import org.springframework.boot.context.properties.EnableConfigurationProperties;
Что за импорты?

2020-08-13 15:28 UTC, tediik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +//}
Не надо его комментировать! Чтобы его отключить надо закомментировать только строчку @PostConstruct

2020-08-13 15:28 UTC, tediik commented on src/main/java/com/jm/online_store/config/facebook/FacebookOAuth2UserService.java
> +package com.jm.online_store.config.facebook;
Почему сервис лежит в конфигурации??

2020-08-13 15:28 UTC, tediik commented on src/main/java/com/jm/online_store/config/facebook/FacebookOAuth2UserService.java
> +
Куда столько пустых строчек?

2020-08-13 15:28 UTC, tediik commented on src/main/java/com/jm/online_store/config/facebook/FacebookOAuth2UserService.java
> +
Да, ё маё )))

2020-08-13 15:28 UTC, tediik commented on src/main/java/com/jm/online_store/config/facebook/FacebookOAuth2UserService.java
> +
убирай, где кодстайл вообще?

2020-08-13 15:28 UTC, tediik commented on src/main/java/com/jm/online_store/config/facebook/FacebookOAuth2UserService.java
> +            userRepository.save(newUser);
Может лучше вызвать соответсвтующий конструктор, а ежели его нет - написать его в классе User

2020-08-13 15:28 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/SecurityConfig.java
> +                .antMatchers("/resources/**", "/static/**", "/css/**", "/js/**", "/images/**","/assets/**","/fonts/**","/dis/**","/vendor1/**");
уверен, что /resources/**" и "/static/**" не "закрывают" уже и "/css/**", "/js/**", "/images/**" ??

2020-08-13 15:28 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/SecurityConfig.java
> +                .antMatchers("/login", "/resources/**", "/static/**", "/css/**", "/js/**", "/images/**","/assets/**","/fonts/**","/dis/**","/vendor1/**")
Оппа!? И сюда тоже??

2020-08-13 15:28 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/SecurityConfig.java
> -                .antMatchers("/customer").access("hasAnyRole('ROLE_CUSTOMER','ROLE_ADMIN')")
а кабинет покупателя не тут висит?

2020-08-13 15:28 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/LoginController.java
> +
Эммм??

2020-08-13 15:28 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/LoginController.java
> +
Зачем?

2020-08-13 15:28 UTC, tediik commented on src/main/java/com/jm/online_store/service/UserService.java
> +
Кодстайл

2020-08-13 15:28 UTC, tediik commented on src/main/resources/application.properties
> +#logging.level.root=error
Это ненужный код?? С какой целью закомментирован?

2020-08-13 15:28 UTC, tediik commented on src/main/resources/templates/index.html
> +    <script src="/static/main.js"></script>
Уже поправлено у Ксении, обнови dev

2020-08-13 15:28 UTC, tediik commented on src/main/resources/templates/index.html
> +
кодстайл

2020-08-13 20:25 UTC, Yurikru commented on pom.xml
> -		</dependency>
Проверил, да был косяк при мердже. Добавил все зависимости из dev, и добавил свои Oautg

2020-08-13 20:26 UTC, Yurikru commented on src/main/java/com/jm/online_store/OnlineStoreApplication.java
> +import org.springframework.boot.context.properties.EnableConfigurationProperties;
Убрал ))

2020-08-13 20:26 UTC, Yurikru commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> +//}
Понял! Закоментил только аннотацию

2020-08-13 20:27 UTC, Yurikru commented on src/main/java/com/jm/online_store/config/facebook/FacebookOAuth2UserService.java
> +package com.jm.online_store.config.facebook;
Перенес фейсбук авторизацию в парку секьюрити

2020-08-13 20:52 UTC, Yurikru commented on src/main/resources/templates/index.html
> +    <script src="/static/main.js"></script>
Сделал

2020-08-13 20:57 UTC, Yurikru commented on src/main/resources/application.properties
> +#logging.level.root=error
Убрал...

2020-08-14 14:59 UTC, tediik requested changes
Поправь еще замечаения по кодстайлу и + реши как обсудили цикличную зависимость

2020-08-14 14:59 UTC, tediik commented on src/main/java/com/jm/online_store/service/UserService.java
> +
Три лишних строчки - убери

2020-08-14 14:59 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/LoginController.java
> +
8 лишних строчек в конце - зачем?

2020-08-14 14:59 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/LoginController.java
> +
+1 лишняя строчка в конце файла - убери

2020-08-15 21:39 UTC, tediik reviewed
Косяки конечно есть по кодстайлу, но будем заливать уже

2020-08-15 21:41 UTC, tediik approved these changes

2020-08-15 21:41 UTC, merged