Added Tests of UserServiceImpl class;
tediik/online_store pull request #84
Opened 2020-09-15 18:55 UTC by DaveShedar

2020-09-16 07:35 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +    private UserRepository userRepository = mock(UserRepository.class);
Здесь можно использовать аннотации для создания моков

2020-09-16 07:37 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        user3 = new User("ira@mail.ru", "123",
совсем не понял зачем создается user3 а следующей строкой в юзер3 записывается новый юзер

2020-09-16 07:38 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        Role customerRole111 = new Role("ROLE_CUSTOMER");
лучше избегать названий не несущих смыла таких как customerRole111

2020-09-16 07:39 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        Optional<Role> custRole = Optional.of(customerRole111);
такого рода сокращения на сколько слышал тоже не приветствуются, но тут на усмотрение Эдуарда.

2020-09-16 07:42 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        when(passwordEncoder.encode(user3.getPassword())).thenReturn("Encoded password");
дальше по тесту нигде не смотрится Encoded password, так может тогда и не нужна эта строчка?

2020-09-16 07:43 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        when(userRepository.save(user3)).thenReturn(user3);
аналогично предыдущему комменту.

2020-09-16 07:49 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        verify(passwordEncoder, times(1)).encode(any());
Когда мой тест проверяли, сказали что безсмысленно такие тесты делать. Проверять просто сколько раз вызвался метод.

2020-09-16 07:55 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        assertNotNull(userService.updateUserProfile(user3));
мне кажется в этом тесте можно не только на null проверить. Плюс во всех тестах хорошо бы писать еще месаджи. assertNotNull(userService.updateUserProfile(user3), "вот тут пишется мессадж");

2020-09-16 07:59 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        when(userRepository.findById(user3.getId())).thenReturn(Optional.ofNullable(user3));
вот тут тоже, возвращается юзер3 а дальше он и не нужен, тогда строчка по сути эта и не нужна. На сколько я понял тесты, тут ты описываешь что ожидаешь, дальше ты моделируешь реальное и сравниваешь результаты например.

2020-09-16 08:01 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        boolean res = userService.activateUser(token, request);
эту строку можно целиком в асерт запихнуть без объявления переменной res. И лучше опять таки не сокращать названия, совсем не понятно что значит res. Сложно будет другим читать твой код,

2020-09-16 08:10 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +    public void updateUserImageTest() throws IOException {
здесь опять у тебя по сути только проверяется что в результате выполнения возвращается строка и она не null. Мне кажется здесь можно более осмысоенные тесты сделать.
1. в этом методе есть if, с первого взгляда мне кажется можно сделать проверку выполнения if.
2. там возвращается строка File.separator + "uploads" + File.separator + "images" + File.separator + uniqueFilename; ее тоже можно проверить не просто как null а что она содержит некий путь.

2020-09-16 08:13 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        boolean result = userService.changePassword(3L, "oldPassword", "newPassword");
для такой проверки есть assertEquals

2020-09-16 08:22 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        Assert.notNull(updateUser,"Проверка, что NotNull");
здесь можно сделать проверку что пользователь который вернулся из сервиса после обновления равен пользователю который вернулся из репозитория

2020-09-17 19:36 UTC, DaveShedar commented
Добавил проверку на Exceptions. Сократил код.

2020-09-18 07:13 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +    public void shouldAddUserSuccessfully() {
честно говоря сложно понять что тестипует данный тест. Отчасти из за того что везде фигурируют user1, user2, user3 ит.д. и приходится постоянно листать вверх и пытаться разобраться что это за юзер, у которого нет email или еще что то. Однозначно если так делаеь надо давать осмысленные имена, например userWithIncorrectEmailAdress

2020-09-18 07:13 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +
лишняя строчка и ниже тоже есть.

2020-09-18 07:14 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        userService.addUser(user3);
непонятно для чего строка, результат нигде не проверяется.

2020-09-18 07:14 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +    private UserRepository userRepository = mock(UserRepository.class);
Я предполагаю, что Эдуард все же попросит использовать аннотации. Сужу по своему опыту.

2020-09-18 07:21 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        assertThrows(InvalidEmailException.class, () -> {
Я бы тесты с киданием эксепшенов выделил бы в отдельный тест. Но не знаю правильно ли это, остается на суд Эдуарда.

2020-09-18 07:24 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        verify(passwordEncoder, times(3)).encode(any());
по моим предположениям, этот тест должен тестировать сколько раз метод encode вызывается в реальности в методе например addUser. У тебя я так понимаю он следит сколько раз encode вызывается непосредственно в тесте. Не могу предположить для чего нам эта информация, но может в этом есть какой то смысл.

2020-09-18 07:28 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        assertThrows(NullPointerException.class, () -> {
assertThrows(NullPointerException.class, () -> {
            userService.updateUserAdminPanel(user2);
        }, "Expected exception doesn't match actual"); и фигурные скобки тут лишние мне кажется {}

2020-09-18 07:29 UTC, dshishkaryan commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        userService.regNewAccount(user3);
вот эта строчка не понял зачем

2020-09-18 07:57 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        user3 = new User("ira@mail.ru", "123",
поправил

2020-09-18 08:45 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +    private UserRepository userRepository = mock(UserRepository.class);
я просмотрел, уже похожие тесты, никто не использует @InjectMocks, кучу времени убил так и не получилось его прикрутить. Если уже Эдуард скажет, что нужно прикручивать, буду копать.

2020-09-18 08:45 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        Role customerRole111 = new Role("ROLE_CUSTOMER");
это все убрал, как ненужное.

2020-09-18 08:45 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        Optional<Role> custRole = Optional.of(customerRole111);
скорректировал.

2020-09-18 08:49 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        when(passwordEncoder.encode(user3.getPassword())).thenReturn("Encoded password");
да, верно, убрал.

2020-09-18 08:50 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        when(userRepository.save(user3)).thenReturn(user3);
убрал.

2020-09-18 08:52 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        verify(passwordEncoder, times(1)).encode(any());
тяжело проверить добавляет ли он пользователя или нет на сервисе с заглушкой, но так хоть я проверяю, что в методе все действия проходят без ошибок. Насколько это верно, нужно мнение Эдуарда.

2020-09-18 08:53 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        verify(passwordEncoder, times(1)).encode(any());
сейчас уже добавил и проверку на исключения, в добавлении пользователя оставил это, а в следующем методе уже убрал.

2020-09-18 08:55 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        assertNotNull(userService.updateUserProfile(user3));
добавил сообщения

2020-09-18 09:04 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        when(userRepository.findById(user3.getId())).thenReturn(Optional.ofNullable(user3));
Да все верно, я добавляю одного пользователя, и он например, находит другого, или не находит, и тогда у меня случаются события, как-то различные исключения. Полностью исправил этот метод.

2020-09-18 09:06 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        boolean res = userService.activateUser(token, request);
исправил, res обозначал result, согласен, что следует дописать 3 буквы для лучшего понимания кода.

2020-09-18 09:10 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +    public void updateUserImageTest() throws IOException {
добавил сюда еще проверку на исключение. проверить по 2 пункту очень тяжело с MockMultipartFile, поскольку в нем проверяется только наличие имени файла, а все остальное заглушки, и проверка на них всегда проходит. Наверное, с этой целью и написали MockMultipartFile.

2020-09-18 09:17 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        Assert.notNull(updateUser,"Проверка, что NotNull");
непонятно как это сделать, если возвращается из сервиса void. Можно искусственно создать добавление в некий список, потом взять его от туда и проверить, но это проверяет не работу метода, а работу репозитория.

2020-09-18 14:01 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        assertThrows(NullPointerException.class, () -> {
Да, все верно, сразу не увидел. Удалил.

2020-09-18 14:03 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        verify(passwordEncoder, times(3)).encode(any());
мы же проводим тест на каждый метод в отдельности, поэтому и проверяю, сколько раз он вызывается. у меня был случай, когда контроллер при обращении к нему вызывался несколько раз, может как раз для таких случаев (хотя может и несколько и не уместный пример).

2020-09-18 14:07 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        userService.addUser(user3);
не знаю насколько это правильное решение, но я проверяю, что выбрасываются исключения, а в целом работу метода, в котором он вызывает другие классы и доходит до логического завершения - нет. Если его удалить, в целом только сократиться код.

2020-09-18 14:08 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +
сократил.

2020-09-18 14:13 UTC, DaveShedar commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +    public void shouldAddUserSuccessfully() {
подписал над строками, что выполняется при данных вызовах.

2020-09-18 14:28 UTC, DaveShedar commented
Поправил по комментариям.

2020-09-19 17:13 UTC, tediik requested changes

2020-09-19 17:13 UTC, tediik commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        userService.addUser(user3);
согласен, тут ничего вообще не проверяется - убрать

2020-09-19 17:13 UTC, tediik commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        when(userRepository.save(user3)).thenReturn(user3);
when ничего не проверяет, он задает что делать мок объекту при вызове определенного метода с определенным параметром.
И учитывая, что ниже ты нигде не будешь использовать вызов метода save с юзером user3, то эта строчка бессмыслена

2020-09-19 17:13 UTC, tediik commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        verify(passwordEncoder, times(3)).encode(any());
это оставь, в принципе пусть будет

2020-09-19 17:13 UTC, tediik commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +    public void shouldAddUserSuccessfully() {
Код в котором столько комментов как у тебя в этом тесте - плохой код, потому что код должен рассказывать о себе сам, сам себя документировать. Поэтому я согласен, надо дать нормальные понятные длинные имена этим юзерам и убрать большую часть твоих комментов почти над каждой строчкой теста

2020-09-19 17:13 UTC, tediik commented on src/test/java/com/jm/online_store/service/impl/UserServiceImplTest.java
> +        boolean res = userService.activateUser(token, request);
странный подход с отдельной переменной, запихни сразу в assertTrue

2020-09-21 10:36 UTC, tediik approved these changes

2020-09-21 10:36 UTC, merged