feature/addNews
tediik/online_store pull request #9
Opened 2020-08-14 15:56 UTC by sirajDeveloper

"add news and add news-control"

2020-08-16 21:59 UTC, tediik requested changes

2020-08-16 21:59 UTC, tediik commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> -    @PostConstruct
чем не угодил @PostConstruct?? Верни

2020-08-16 21:59 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/SecurityConfig.java
> +                                                                "/activate/**").permitAll()
Лесенка красивая, но нет, сделай в строчку, если длинная - разбей на 2

2020-08-16 21:59 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
> +    NewsService newsService;
модификатор доступа? убрать и сделать через конструктор, используй Ломбок

2020-08-16 21:59 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/NewsController.java
> +    NewsService newsService;
Ломбок, через конструктор, модификатор доступа.

2020-08-16 21:59 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
> +    }
Не понятно назначение методов для работы с новостями в этом контроллере, если у тебя есть контроллер NewsController

2020-08-16 21:59 UTC, tediik commented on src/main/java/com/jm/online_store/repository/NewsRepository.java
> +    @Query("select a from News a where a.postingDate <= :postingDate")
Операторы заглавными, псевдоним для News - n, а не a.

2020-08-16 21:59 UTC, tediik commented on src/main/java/com/jm/online_store/repository/NewsRepository.java
> +    List<News> findAllWithPostingDateTimeAfter(
По моему можно было обойтись и без запроса самописного, просто правильно составить имя метода, пробовал?

2020-08-16 21:59 UTC, tediik commented on src/main/java/com/jm/online_store/service/NewsServiceImpl.java
> +    NewsRepository newsRepository;
Ломбок, конструктор, модификатор

2020-08-16 21:59 UTC, tediik commented on src/main/java/com/jm/online_store/service/NewsServiceImpl.java
> +
лишняя строчка

2020-08-16 21:59 UTC, tediik commented on src/main/java/com/jm/online_store/service/RoleService.java
> -
тут оставь пустую строчку, надо отделить импорты от объявления интерфейса

2020-08-16 21:59 UTC, tediik commented on src/main/java/com/jm/online_store/service/UserServiceImpl.java
> +        Set<Role> userSetRoles = Collections.singleton(roleRepository.findByName("ROLE_CUSTOMER").get());
Этого тут по идее конечно быть не должно, ну будут конфликты - решишь

2020-08-17 04:25 UTC, sirajDeveloper commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
> +    }
новости показываются для покупателей на /news, и в кабинете менеджера список опубликованных и не опубл новостей на /manager/news.

2020-08-17 04:42 UTC, sirajDeveloper commented on src/main/java/com/jm/online_store/config/DataInitializer.java
> -    @PostConstruct
с ним багалось, закоментировал, но здесь почему то как удаленное показывает, наверное потому что импорт на него удалил.

2020-08-17 10:00 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/ManagerController.java
> +    }
ок, оставим пока

2020-08-17 10:04 UTC, tediik approved these changes

2020-08-17 10:05 UTC, merged