bugFix/EmailRegistration
tediik/online_store pull request #90
Opened 2020-09-20 22:09 UTC by IrekNabiullin

Исправлен bug, который выдавал ошибку в программе при вводе несуществующего email при регистрации.
В классе MyUserDetailsService переписан метод loadUserByUsername() и добавлен метод mapRolesToAuthorities.

Исправлен баг - при регистрации нового пользователя программа отправляла уведомление на e-mail пользователя с просьбой подтвердить регистрацию, но не было никакого уведомления об этом на экранею. В файле mainPage.js в методе register() команда toastr.success(...) заменена на команду alert('Ссылка для подтверждения регистрации отправлена на вашу почту').

Также исправлена ошибка, выдававашая WARN при загрузке программы. В файле настроек application.yml указана опция open-in-view: false.

2020-09-20 22:20 UTC, IrekNabiullin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Проверить работу регистрации через email](https://trello.com/c/YjphLhsD/118-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%B8%D1%82%D1%8C-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%83-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-email)

2020-09-21 09:12 UTC, Yurikru commented on src/main/java/com/jm/online_store/config/security/MyUserDetailsService.java
> +//            return userRepository.findByEmail(email).get();
Return value have to be commented?

2020-09-21 09:12 UTC, Yurikru commented on src/main/java/com/jm/online_store/config/security/MyUserDetailsService.java
> +
Empty lines should be removed

2020-09-21 09:13 UTC, Yurikru commented on src/main/java/com/jm/online_store/controller/rest/MainPageRestController.java
> +//            return new ResponseEntity("notValidEmailError", HttpStatus.NOT_ACCEPTABLE);
again, should return type be commented?

2020-10-04 20:46 UTC, tediik requested changes

2020-10-04 20:46 UTC, tediik commented on src/main/java/com/jm/online_store/config/security/MyUserDetailsService.java
> +    }
Так вроде мы используем Optional чтобы не обрабатывать null, а тут какой то антипатерн

2020-10-04 20:46 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/FavouritesGoodsRestController.java
> +        return userService.findByEmail(authentication.getName()).orElseThrow(UserNotFoundException::new);
слушай, этот функционал у нас используется аж в 3-4 местах, может мы вынесем это в 1 сервис в 1 метод и будем его вызывать там где надо нам?

2020-10-04 20:46 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/MainPageController.java
> +     */
прибери JavaDoc - лишние пробелы ни к чему, для параметров должно быть описание, return вообще не заполнен.

2020-10-04 20:46 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/MainPageController.java
> +            System.out.println("catch (Exception ex) {Ваш Email уже был подтвержден.}");
нет, или убирай вообще или логируй!

2020-10-04 20:46 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/MailSenderServiceImpl.java
> +            System.out.println("Warning! Message rejected under suspicion of SPAM!");
логируй

2020-10-05 12:52 UTC, tediik requested changes
Замечания не исправлены

2020-10-06 19:08 UTC, IrekNabiullin commented on src/main/java/com/jm/online_store/config/security/MyUserDetailsService.java
> +    }
Исправил

2020-10-06 19:46 UTC, IrekNabiullin commented on src/main/java/com/jm/online_store/controller/simple/MainPageController.java
> +     */
исправил

2020-10-06 19:46 UTC, IrekNabiullin commented on src/main/java/com/jm/online_store/controller/simple/MainPageController.java
> +            System.out.println("catch (Exception ex) {Ваш Email уже был подтвержден.}");
залогировал

2020-10-06 19:46 UTC, IrekNabiullin commented on src/main/java/com/jm/online_store/service/impl/MailSenderServiceImpl.java
> +            System.out.println("Warning! Message rejected under suspicion of SPAM!");
залогировал

2020-10-07 12:46 UTC, tediik requested changes

2020-10-07 12:46 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/ProductServiceImpl.java
> +            log.debug("ProductServiceImpl.getProductDTO.userfromDB = " + userFromDB.getEmail());
используй общепринятую у нас на проекте форму методов логирования - с подстановочными шаблонами {}, чтобы никакой конкатенации

2020-10-07 12:46 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        log.debug("getCurrentLoggedInUser.auth = " + auth.getPrincipal().toString());
используй общепринятую у нас на проекте форму методов логирования - с подстановочными шаблонами {}, чтобы никакой конкатенации

2020-10-07 12:46 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +//        return findByEmail(username).get();
если код готов и проверен, значит закоментированное "про запас" нам не нужно, убираем

2020-10-07 12:46 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/MainPageController.java
> +            log.debug("catch (Exception ex) {Ваш Email уже был подтвержден.}");
странное сообщение, тебе не кажется?

2020-10-07 12:46 UTC, tediik commented on src/main/java/com/jm/online_store/controller/simple/MainPageController.java
> +        } catch (Exception ex) {
У нас вроде метод userService.activateUser не кидает исключений? Какое именно исключение ты тут ожидаешь? Всегда устанавливай конкретный тип.

2020-10-07 14:38 UTC, IrekNabiullin commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +//        return findByEmail(username).get();
Да, пропустил это комментарий. Много пришлось вычищать. Исправлено

2020-10-07 21:19 UTC, IrekNabiullin commented on src/main/java/com/jm/online_store/service/impl/ProductServiceImpl.java
> +            log.debug("ProductServiceImpl.getProductDTO.userfromDB = " + userFromDB.getEmail());
исправлено. Этот лог не важен, удалил.

2020-10-07 21:19 UTC, IrekNabiullin commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        log.debug("getCurrentLoggedInUser.auth = " + auth.getPrincipal().toString());
исправлено, залогировал с помощью {}

2020-10-07 22:27 UTC, IrekNabiullin commented on src/main/java/com/jm/online_store/controller/simple/MainPageController.java
> +            log.debug("catch (Exception ex) {Ваш Email уже был подтвержден.}");
Это я оставлял на доработку. При повторном щелчке на ссылку регистрации прилетал сначала json, потом заменил на это сообщение. Исправил. Теперь нормально перекидывает юзера в личный кабинет.

2020-10-07 22:30 UTC, IrekNabiullin commented on src/main/java/com/jm/online_store/controller/simple/MainPageController.java
> +        } catch (Exception ex) {
Исправил на EmailAlreadyExistsException .

2020-10-08 11:45 UTC, tediik approved these changes

2020-10-08 11:45 UTC, merged