Изменил rest контроллер, на странице customerPage.html добавил id что…
tediik/online_store pull request #93
Opened 2020-09-22 18:41 UTC by vladstar25

…бы привязть событие. В profile.js сделал обработку формы и обработку ответа с сервера.

2020-09-22 23:59 UTC, Zheeka18 commented on src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
> +            return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
Мы стараемся в проекте создавать RespoonseEntity через фабричные методы, там для всех основных типов ответов они есть

2020-09-22 23:59 UTC, Zheeka18 commented on src/main/resources/static/js/profile.js
> +            alert ("Подтвердите смену email. Вам на почту отправлено письмо.");
Зачем убрал toastr и вместо него alert ?

2020-09-23 04:25 UTC, vladstar25 commented on src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
> +            return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
Поправил

2020-09-23 17:25 UTC, tediik requested changes

2020-09-23 17:25 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
> +            return ResponseEntity.ok().body("ok");
Разве нельзя написать: ResponseEntity.ok("ok");

2020-09-23 17:25 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/CustomerRestController.java
> +            return ResponseEntity.ok().body("ok");
Хотя вообще зачем передавать Ок? Он же не несет никакой информации!? Передали статус 200 и хватит с нас

2020-09-23 17:25 UTC, tediik commented on src/main/resources/static/js/profile.js
> +            document.location.href = "/customer";
ошибки бывают очень разные, я бы на твоем месте конкретно тут ловил именно ту ошибку, которую мы сами отправляем с бэка - 400, и тогда уже можно выдать тост нужный, либо ловить все ошибки, как у тебя сейчас, но тогда брать из ошибки тело сообщения (у нас это "duplicatedEmailError" - что согласись будет смотрется коряво) и выводить в тостер это полученное в ошибке сообщение - так будет информативнее

2020-09-24 16:57 UTC, tediik approved these changes

2020-09-24 16:57 UTC, merged