Feature/password validator
tediik/online_store pull request #97
Opened 2020-09-26 14:25 UTC by vladstar25

Проверка пароля для регистрации пользователя работает

2020-09-26 15:15 UTC, Zheeka18 commented on src/main/java/com/jm/online_store/controller/rest/MainPageRestController.java
> +        }
Используем фабричные методы у ResponseEntity. Почему вовращаем ок, если всё не ок.

2020-09-26 15:15 UTC, Zheeka18 commented on src/main/resources/templates/mainPage.html
> +                    </div>
В плане юзабилити стоит сообщить пользователю какого формата должен быть пароль

2020-09-28 14:35 UTC, tediik requested changes

2020-09-28 14:35 UTC, tediik commented on src/main/java/com/jm/online_store/util/ValidationUtils.java
> +        System.out.println(matcher.matches());
?? либо убирай, либо логируй

2020-09-28 14:35 UTC, tediik commented on src/main/resources/templates/mainPage.html
> +                    </div>
Какой именно сложности пароль не соответствует? Почему не замечаем замечания коллег?
Дай посетителю нормальные пояснения.

2020-09-28 14:35 UTC, tediik commented on src/main/java/com/jm/online_store/util/ValidationUtils.java
> +
чет я не понял смысла в этом! убирай

2020-09-28 14:35 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/MainPageRestController.java
> +        }
Замечание остается актуальным

2020-09-28 14:35 UTC, tediik commented on src/main/java/com/jm/online_store/service/impl/UserServiceImpl.java
> +        }
почему нельзя переиспользовать код из ValidationUtils ??

2020-09-29 10:43 UTC, tediik approved these changes

2020-09-29 10:44 UTC, merged