Filter list of users by selected role.
tediik/online_store pull request #98
Opened 2020-09-26 17:52 UTC by DaveShedar

2020-09-26 19:15 UTC, tediik requested changes

2020-09-26 19:15 UTC, tediik commented on src/main/java/com/jm/online_store/controller/rest/UserFilterController.java
> +public class UserFilterController {
название не совсем отражает суть, да и вообще по смыслу все это происходит с ролями и на страничке Админа, поэтому засунь все это в AdminRestController, а этот вообще удали.

2020-09-26 19:15 UTC, tediik commented on src/main/resources/templates/adminPage.html
> +                        </div>
ты отступ о котором я говорил точно тут предусмотрел??

2020-09-26 23:04 UTC, DaveShedar commented
Замечания исправил.

2020-09-27 22:04 UTC, tediik approved these changes

2020-09-27 22:04 UTC, merged